/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1DevicesOauthPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesOauthPostRequest{}

// V1DevicesOauthPostRequest struct for V1DevicesOauthPostRequest
type V1DevicesOauthPostRequest struct {
	// OAuth grant type
	GrantType string `json:"grant_type"`
	// OAuth scope containing device type, UUID, and hostname
	Scope string `json:"scope"`
	// OAuth state parameter
	State *string `json:"state,omitempty"`
	// OAuth code verifier
	CodeVerify *string `json:"code_verify,omitempty"`
	// Platform type
	Pt *string `json:"pt,omitempty"`
	// Boot mode
	Bm *string `json:"bm,omitempty"`
}

type _V1DevicesOauthPostRequest V1DevicesOauthPostRequest

// NewV1DevicesOauthPostRequest instantiates a new V1DevicesOauthPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesOauthPostRequest(grantType string, scope string) *V1DevicesOauthPostRequest {
	this := V1DevicesOauthPostRequest{}
	this.GrantType = grantType
	this.Scope = scope
	return &this
}

// NewV1DevicesOauthPostRequestWithDefaults instantiates a new V1DevicesOauthPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesOauthPostRequestWithDefaults() *V1DevicesOauthPostRequest {
	this := V1DevicesOauthPostRequest{}
	return &this
}

// GetGrantType returns the GrantType field value
func (o *V1DevicesOauthPostRequest) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *V1DevicesOauthPostRequest) SetGrantType(v string) {
	o.GrantType = v
}

// GetScope returns the Scope field value
func (o *V1DevicesOauthPostRequest) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *V1DevicesOauthPostRequest) SetScope(v string) {
	o.Scope = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V1DevicesOauthPostRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V1DevicesOauthPostRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *V1DevicesOauthPostRequest) SetState(v string) {
	o.State = &v
}

// GetCodeVerify returns the CodeVerify field value if set, zero value otherwise.
func (o *V1DevicesOauthPostRequest) GetCodeVerify() string {
	if o == nil || IsNil(o.CodeVerify) {
		var ret string
		return ret
	}
	return *o.CodeVerify
}

// GetCodeVerifyOk returns a tuple with the CodeVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetCodeVerifyOk() (*string, bool) {
	if o == nil || IsNil(o.CodeVerify) {
		return nil, false
	}
	return o.CodeVerify, true
}

// HasCodeVerify returns a boolean if a field has been set.
func (o *V1DevicesOauthPostRequest) HasCodeVerify() bool {
	if o != nil && !IsNil(o.CodeVerify) {
		return true
	}

	return false
}

// SetCodeVerify gets a reference to the given string and assigns it to the CodeVerify field.
func (o *V1DevicesOauthPostRequest) SetCodeVerify(v string) {
	o.CodeVerify = &v
}

// GetPt returns the Pt field value if set, zero value otherwise.
func (o *V1DevicesOauthPostRequest) GetPt() string {
	if o == nil || IsNil(o.Pt) {
		var ret string
		return ret
	}
	return *o.Pt
}

// GetPtOk returns a tuple with the Pt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetPtOk() (*string, bool) {
	if o == nil || IsNil(o.Pt) {
		return nil, false
	}
	return o.Pt, true
}

// HasPt returns a boolean if a field has been set.
func (o *V1DevicesOauthPostRequest) HasPt() bool {
	if o != nil && !IsNil(o.Pt) {
		return true
	}

	return false
}

// SetPt gets a reference to the given string and assigns it to the Pt field.
func (o *V1DevicesOauthPostRequest) SetPt(v string) {
	o.Pt = &v
}

// GetBm returns the Bm field value if set, zero value otherwise.
func (o *V1DevicesOauthPostRequest) GetBm() string {
	if o == nil || IsNil(o.Bm) {
		var ret string
		return ret
	}
	return *o.Bm
}

// GetBmOk returns a tuple with the Bm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesOauthPostRequest) GetBmOk() (*string, bool) {
	if o == nil || IsNil(o.Bm) {
		return nil, false
	}
	return o.Bm, true
}

// HasBm returns a boolean if a field has been set.
func (o *V1DevicesOauthPostRequest) HasBm() bool {
	if o != nil && !IsNil(o.Bm) {
		return true
	}

	return false
}

// SetBm gets a reference to the given string and assigns it to the Bm field.
func (o *V1DevicesOauthPostRequest) SetBm(v string) {
	o.Bm = &v
}

func (o V1DevicesOauthPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesOauthPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grant_type"] = o.GrantType
	toSerialize["scope"] = o.Scope
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.CodeVerify) {
		toSerialize["code_verify"] = o.CodeVerify
	}
	if !IsNil(o.Pt) {
		toSerialize["pt"] = o.Pt
	}
	if !IsNil(o.Bm) {
		toSerialize["bm"] = o.Bm
	}
	return toSerialize, nil
}

func (o *V1DevicesOauthPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grant_type",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1DevicesOauthPostRequest := _V1DevicesOauthPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1DevicesOauthPostRequest)

	if err != nil {
		return err
	}

	*o = V1DevicesOauthPostRequest(varV1DevicesOauthPostRequest)

	return err
}

type NullableV1DevicesOauthPostRequest struct {
	value *V1DevicesOauthPostRequest
	isSet bool
}

func (v NullableV1DevicesOauthPostRequest) Get() *V1DevicesOauthPostRequest {
	return v.value
}

func (v *NullableV1DevicesOauthPostRequest) Set(val *V1DevicesOauthPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesOauthPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesOauthPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesOauthPostRequest(val *V1DevicesOauthPostRequest) *NullableV1DevicesOauthPostRequest {
	return &NullableV1DevicesOauthPostRequest{value: val, isSet: true}
}

func (v NullableV1DevicesOauthPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesOauthPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


