/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DeviceRoutingOspfv2AreaNbrGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DeviceRoutingOspfv2AreaNbrGetResponse{}

// V1DeviceRoutingOspfv2AreaNbrGetResponse struct for V1DeviceRoutingOspfv2AreaNbrGetResponse
type V1DeviceRoutingOspfv2AreaNbrGetResponse struct {
	Nbrs []RoutingOspfNbr `json:"nbrs,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo,omitempty"`
	// Reference to the resultset being queried, this should be sent by the service as part of a previous request and so can be opaque to the client.
	Token *string `json:"token,omitempty"`
}

// NewV1DeviceRoutingOspfv2AreaNbrGetResponse instantiates a new V1DeviceRoutingOspfv2AreaNbrGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DeviceRoutingOspfv2AreaNbrGetResponse() *V1DeviceRoutingOspfv2AreaNbrGetResponse {
	this := V1DeviceRoutingOspfv2AreaNbrGetResponse{}
	return &this
}

// NewV1DeviceRoutingOspfv2AreaNbrGetResponseWithDefaults instantiates a new V1DeviceRoutingOspfv2AreaNbrGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DeviceRoutingOspfv2AreaNbrGetResponseWithDefaults() *V1DeviceRoutingOspfv2AreaNbrGetResponse {
	this := V1DeviceRoutingOspfv2AreaNbrGetResponse{}
	return &this
}

// GetNbrs returns the Nbrs field value if set, zero value otherwise.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetNbrs() []RoutingOspfNbr {
	if o == nil || IsNil(o.Nbrs) {
		var ret []RoutingOspfNbr
		return ret
	}
	return o.Nbrs
}

// GetNbrsOk returns a tuple with the Nbrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetNbrsOk() ([]RoutingOspfNbr, bool) {
	if o == nil || IsNil(o.Nbrs) {
		return nil, false
	}
	return o.Nbrs, true
}

// HasNbrs returns a boolean if a field has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) HasNbrs() bool {
	if o != nil && !IsNil(o.Nbrs) {
		return true
	}

	return false
}

// SetNbrs gets a reference to the given []RoutingOspfNbr and assigns it to the Nbrs field.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) SetNbrs(v []RoutingOspfNbr) {
	o.Nbrs = v
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetPageInfo() CommonPageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret CommonPageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetPageInfoOk() (*CommonPageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given CommonPageInfo and assigns it to the PageInfo field.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) SetPageInfo(v CommonPageInfo) {
	o.PageInfo = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *V1DeviceRoutingOspfv2AreaNbrGetResponse) SetToken(v string) {
	o.Token = &v
}

func (o V1DeviceRoutingOspfv2AreaNbrGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DeviceRoutingOspfv2AreaNbrGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nbrs) {
		toSerialize["nbrs"] = o.Nbrs
	}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableV1DeviceRoutingOspfv2AreaNbrGetResponse struct {
	value *V1DeviceRoutingOspfv2AreaNbrGetResponse
	isSet bool
}

func (v NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) Get() *V1DeviceRoutingOspfv2AreaNbrGetResponse {
	return v.value
}

func (v *NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) Set(val *V1DeviceRoutingOspfv2AreaNbrGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DeviceRoutingOspfv2AreaNbrGetResponse(val *V1DeviceRoutingOspfv2AreaNbrGetResponse) *NullableV1DeviceRoutingOspfv2AreaNbrGetResponse {
	return &NullableV1DeviceRoutingOspfv2AreaNbrGetResponse{value: val, isSet: true}
}

func (v NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DeviceRoutingOspfv2AreaNbrGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


