/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2ExtranetsMonitoringConsumersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ExtranetsMonitoringConsumersPostRequest{}

// V2ExtranetsMonitoringConsumersPostRequest struct for V2ExtranetsMonitoringConsumersPostRequest
type V2ExtranetsMonitoringConsumersPostRequest struct {
	Id *int64 `json:"id,omitempty"`
}

// NewV2ExtranetsMonitoringConsumersPostRequest instantiates a new V2ExtranetsMonitoringConsumersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ExtranetsMonitoringConsumersPostRequest() *V2ExtranetsMonitoringConsumersPostRequest {
	this := V2ExtranetsMonitoringConsumersPostRequest{}
	return &this
}

// NewV2ExtranetsMonitoringConsumersPostRequestWithDefaults instantiates a new V2ExtranetsMonitoringConsumersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ExtranetsMonitoringConsumersPostRequestWithDefaults() *V2ExtranetsMonitoringConsumersPostRequest {
	this := V2ExtranetsMonitoringConsumersPostRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V2ExtranetsMonitoringConsumersPostRequest) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ExtranetsMonitoringConsumersPostRequest) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V2ExtranetsMonitoringConsumersPostRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V2ExtranetsMonitoringConsumersPostRequest) SetId(v int64) {
	o.Id = &v
}

func (o V2ExtranetsMonitoringConsumersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ExtranetsMonitoringConsumersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableV2ExtranetsMonitoringConsumersPostRequest struct {
	value *V2ExtranetsMonitoringConsumersPostRequest
	isSet bool
}

func (v NullableV2ExtranetsMonitoringConsumersPostRequest) Get() *V2ExtranetsMonitoringConsumersPostRequest {
	return v.value
}

func (v *NullableV2ExtranetsMonitoringConsumersPostRequest) Set(val *V2ExtranetsMonitoringConsumersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ExtranetsMonitoringConsumersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ExtranetsMonitoringConsumersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ExtranetsMonitoringConsumersPostRequest(val *V2ExtranetsMonitoringConsumersPostRequest) *NullableV2ExtranetsMonitoringConsumersPostRequest {
	return &NullableV2ExtranetsMonitoringConsumersPostRequest{value: val, isSet: true}
}

func (v NullableV2ExtranetsMonitoringConsumersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ExtranetsMonitoringConsumersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


