/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesDeviceIdInterfacesGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesDeviceIdInterfacesGetRequest{}

// V1DevicesDeviceIdInterfacesGetRequest struct for V1DevicesDeviceIdInterfacesGetRequest
type V1DevicesDeviceIdInterfacesGetRequest struct {
	PageRequest *CommonPageRequest `json:"pageRequest,omitempty"`
}

// NewV1DevicesDeviceIdInterfacesGetRequest instantiates a new V1DevicesDeviceIdInterfacesGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesDeviceIdInterfacesGetRequest() *V1DevicesDeviceIdInterfacesGetRequest {
	this := V1DevicesDeviceIdInterfacesGetRequest{}
	return &this
}

// NewV1DevicesDeviceIdInterfacesGetRequestWithDefaults instantiates a new V1DevicesDeviceIdInterfacesGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesDeviceIdInterfacesGetRequestWithDefaults() *V1DevicesDeviceIdInterfacesGetRequest {
	this := V1DevicesDeviceIdInterfacesGetRequest{}
	return &this
}

// GetPageRequest returns the PageRequest field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdInterfacesGetRequest) GetPageRequest() CommonPageRequest {
	if o == nil || IsNil(o.PageRequest) {
		var ret CommonPageRequest
		return ret
	}
	return *o.PageRequest
}

// GetPageRequestOk returns a tuple with the PageRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdInterfacesGetRequest) GetPageRequestOk() (*CommonPageRequest, bool) {
	if o == nil || IsNil(o.PageRequest) {
		return nil, false
	}
	return o.PageRequest, true
}

// HasPageRequest returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdInterfacesGetRequest) HasPageRequest() bool {
	if o != nil && !IsNil(o.PageRequest) {
		return true
	}

	return false
}

// SetPageRequest gets a reference to the given CommonPageRequest and assigns it to the PageRequest field.
func (o *V1DevicesDeviceIdInterfacesGetRequest) SetPageRequest(v CommonPageRequest) {
	o.PageRequest = &v
}

func (o V1DevicesDeviceIdInterfacesGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesDeviceIdInterfacesGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageRequest) {
		toSerialize["pageRequest"] = o.PageRequest
	}
	return toSerialize, nil
}

type NullableV1DevicesDeviceIdInterfacesGetRequest struct {
	value *V1DevicesDeviceIdInterfacesGetRequest
	isSet bool
}

func (v NullableV1DevicesDeviceIdInterfacesGetRequest) Get() *V1DevicesDeviceIdInterfacesGetRequest {
	return v.value
}

func (v *NullableV1DevicesDeviceIdInterfacesGetRequest) Set(val *V1DevicesDeviceIdInterfacesGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesDeviceIdInterfacesGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesDeviceIdInterfacesGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesDeviceIdInterfacesGetRequest(val *V1DevicesDeviceIdInterfacesGetRequest) *NullableV1DevicesDeviceIdInterfacesGetRequest {
	return &NullableV1DevicesDeviceIdInterfacesGetRequest{value: val, isSet: true}
}

func (v NullableV1DevicesDeviceIdInterfacesGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesDeviceIdInterfacesGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


