/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableL4PortListConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableL4PortListConfig{}

// ManaV2NullableL4PortListConfig struct for ManaV2NullableL4PortListConfig
type ManaV2NullableL4PortListConfig struct {
	List *ManaV2L4PortListConfig `json:"list,omitempty"`
}

// NewManaV2NullableL4PortListConfig instantiates a new ManaV2NullableL4PortListConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableL4PortListConfig() *ManaV2NullableL4PortListConfig {
	this := ManaV2NullableL4PortListConfig{}
	return &this
}

// NewManaV2NullableL4PortListConfigWithDefaults instantiates a new ManaV2NullableL4PortListConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableL4PortListConfigWithDefaults() *ManaV2NullableL4PortListConfig {
	this := ManaV2NullableL4PortListConfig{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise.
func (o *ManaV2NullableL4PortListConfig) GetList() ManaV2L4PortListConfig {
	if o == nil || IsNil(o.List) {
		var ret ManaV2L4PortListConfig
		return ret
	}
	return *o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableL4PortListConfig) GetListOk() (*ManaV2L4PortListConfig, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *ManaV2NullableL4PortListConfig) HasList() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given ManaV2L4PortListConfig and assigns it to the List field.
func (o *ManaV2NullableL4PortListConfig) SetList(v ManaV2L4PortListConfig) {
	o.List = &v
}

func (o ManaV2NullableL4PortListConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableL4PortListConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}
	return toSerialize, nil
}

type NullableManaV2NullableL4PortListConfig struct {
	value *ManaV2NullableL4PortListConfig
	isSet bool
}

func (v NullableManaV2NullableL4PortListConfig) Get() *ManaV2NullableL4PortListConfig {
	return v.value
}

func (v *NullableManaV2NullableL4PortListConfig) Set(val *ManaV2NullableL4PortListConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableL4PortListConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableL4PortListConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableL4PortListConfig(val *ManaV2NullableL4PortListConfig) *NullableManaV2NullableL4PortListConfig {
	return &NullableManaV2NullableL4PortListConfig{value: val, isSet: true}
}

func (v NullableManaV2NullableL4PortListConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableL4PortListConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


