/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1LanSegmentsGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1LanSegmentsGetRequest{}

// V1LanSegmentsGetRequest struct for V1LanSegmentsGetRequest
type V1LanSegmentsGetRequest struct {
	DeviceId *int64 `json:"deviceId,omitempty"`
	Filter *string `json:"filter,omitempty"`
	PageRequest *CommonPageRequest `json:"pageRequest,omitempty"`
}

// NewV1LanSegmentsGetRequest instantiates a new V1LanSegmentsGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1LanSegmentsGetRequest() *V1LanSegmentsGetRequest {
	this := V1LanSegmentsGetRequest{}
	return &this
}

// NewV1LanSegmentsGetRequestWithDefaults instantiates a new V1LanSegmentsGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1LanSegmentsGetRequestWithDefaults() *V1LanSegmentsGetRequest {
	this := V1LanSegmentsGetRequest{}
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *V1LanSegmentsGetRequest) GetDeviceId() int64 {
	if o == nil || IsNil(o.DeviceId) {
		var ret int64
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LanSegmentsGetRequest) GetDeviceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *V1LanSegmentsGetRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given int64 and assigns it to the DeviceId field.
func (o *V1LanSegmentsGetRequest) SetDeviceId(v int64) {
	o.DeviceId = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *V1LanSegmentsGetRequest) GetFilter() string {
	if o == nil || IsNil(o.Filter) {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LanSegmentsGetRequest) GetFilterOk() (*string, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *V1LanSegmentsGetRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *V1LanSegmentsGetRequest) SetFilter(v string) {
	o.Filter = &v
}

// GetPageRequest returns the PageRequest field value if set, zero value otherwise.
func (o *V1LanSegmentsGetRequest) GetPageRequest() CommonPageRequest {
	if o == nil || IsNil(o.PageRequest) {
		var ret CommonPageRequest
		return ret
	}
	return *o.PageRequest
}

// GetPageRequestOk returns a tuple with the PageRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LanSegmentsGetRequest) GetPageRequestOk() (*CommonPageRequest, bool) {
	if o == nil || IsNil(o.PageRequest) {
		return nil, false
	}
	return o.PageRequest, true
}

// HasPageRequest returns a boolean if a field has been set.
func (o *V1LanSegmentsGetRequest) HasPageRequest() bool {
	if o != nil && !IsNil(o.PageRequest) {
		return true
	}

	return false
}

// SetPageRequest gets a reference to the given CommonPageRequest and assigns it to the PageRequest field.
func (o *V1LanSegmentsGetRequest) SetPageRequest(v CommonPageRequest) {
	o.PageRequest = &v
}

func (o V1LanSegmentsGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1LanSegmentsGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.PageRequest) {
		toSerialize["pageRequest"] = o.PageRequest
	}
	return toSerialize, nil
}

type NullableV1LanSegmentsGetRequest struct {
	value *V1LanSegmentsGetRequest
	isSet bool
}

func (v NullableV1LanSegmentsGetRequest) Get() *V1LanSegmentsGetRequest {
	return v.value
}

func (v *NullableV1LanSegmentsGetRequest) Set(val *V1LanSegmentsGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1LanSegmentsGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1LanSegmentsGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1LanSegmentsGetRequest(val *V1LanSegmentsGetRequest) *NullableV1LanSegmentsGetRequest {
	return &NullableV1LanSegmentsGetRequest{value: val, isSet: true}
}

func (v NullableV1LanSegmentsGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1LanSegmentsGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


