/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response{}

// V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response struct for V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response
type V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response struct {
	DefaultOriginates *map[string]string `json:"defaultOriginates,omitempty"`
}

// NewV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response instantiates a new V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response() *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response {
	this := V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response{}
	return &this
}

// NewV1DevicesDeviceIdOspfv2DefaultOriginateGet200ResponseWithDefaults instantiates a new V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesDeviceIdOspfv2DefaultOriginateGet200ResponseWithDefaults() *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response {
	this := V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response{}
	return &this
}

// GetDefaultOriginates returns the DefaultOriginates field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) GetDefaultOriginates() map[string]string {
	if o == nil || IsNil(o.DefaultOriginates) {
		var ret map[string]string
		return ret
	}
	return *o.DefaultOriginates
}

// GetDefaultOriginatesOk returns a tuple with the DefaultOriginates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) GetDefaultOriginatesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DefaultOriginates) {
		return nil, false
	}
	return o.DefaultOriginates, true
}

// HasDefaultOriginates returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) HasDefaultOriginates() bool {
	if o != nil && !IsNil(o.DefaultOriginates) {
		return true
	}

	return false
}

// SetDefaultOriginates gets a reference to the given map[string]string and assigns it to the DefaultOriginates field.
func (o *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) SetDefaultOriginates(v map[string]string) {
	o.DefaultOriginates = &v
}

func (o V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultOriginates) {
		toSerialize["defaultOriginates"] = o.DefaultOriginates
	}
	return toSerialize, nil
}

type NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response struct {
	value *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response
	isSet bool
}

func (v NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) Get() *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response {
	return v.value
}

func (v *NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) Set(val *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response(val *V1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) *NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response {
	return &NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response{value: val, isSet: true}
}

func (v NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesDeviceIdOspfv2DefaultOriginateGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


