/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue{}

// V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue struct for V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue
type V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue struct {
	Ruleset *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset `json:"ruleset,omitempty"`
}

// NewV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue instantiates a new V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue() *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue {
	this := V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue{}
	return &this
}

// NewV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueWithDefaults instantiates a new V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueWithDefaults() *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue {
	this := V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue{}
	return &this
}

// GetRuleset returns the Ruleset field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) GetRuleset() V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset {
	if o == nil || IsNil(o.Ruleset) {
		var ret V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset
		return ret
	}
	return *o.Ruleset
}

// GetRulesetOk returns a tuple with the Ruleset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) GetRulesetOk() (*V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset, bool) {
	if o == nil || IsNil(o.Ruleset) {
		return nil, false
	}
	return o.Ruleset, true
}

// HasRuleset returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) HasRuleset() bool {
	if o != nil && !IsNil(o.Ruleset) {
		return true
	}

	return false
}

// SetRuleset gets a reference to the given V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset and assigns it to the Ruleset field.
func (o *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) SetRuleset(v V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValueRuleset) {
	o.Ruleset = &v
}

func (o V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ruleset) {
		toSerialize["ruleset"] = o.Ruleset
	}
	return toSerialize, nil
}

type NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue struct {
	value *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue
	isSet bool
}

func (v NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) Get() *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue {
	return v.value
}

func (v *NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) Set(val *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue(val *V1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) *NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue {
	return &NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue{value: val, isSet: true}
}

func (v NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesDeviceIdConfigPutRequestEdgeNatPolicyNatRulesetsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


