/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetsB2bIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bIdPutRequest{}

// V1ExtranetsB2bIdPutRequest struct for V1ExtranetsB2bIdPutRequest
type V1ExtranetsB2bIdPutRequest struct {
	Policy ManaV2B2bExtranetProducerPolicy `json:"policy"`
}

type _V1ExtranetsB2bIdPutRequest V1ExtranetsB2bIdPutRequest

// NewV1ExtranetsB2bIdPutRequest instantiates a new V1ExtranetsB2bIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bIdPutRequest(policy ManaV2B2bExtranetProducerPolicy) *V1ExtranetsB2bIdPutRequest {
	this := V1ExtranetsB2bIdPutRequest{}
	this.Policy = policy
	return &this
}

// NewV1ExtranetsB2bIdPutRequestWithDefaults instantiates a new V1ExtranetsB2bIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bIdPutRequestWithDefaults() *V1ExtranetsB2bIdPutRequest {
	this := V1ExtranetsB2bIdPutRequest{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *V1ExtranetsB2bIdPutRequest) GetPolicy() ManaV2B2bExtranetProducerPolicy {
	if o == nil {
		var ret ManaV2B2bExtranetProducerPolicy
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bIdPutRequest) GetPolicyOk() (*ManaV2B2bExtranetProducerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *V1ExtranetsB2bIdPutRequest) SetPolicy(v ManaV2B2bExtranetProducerPolicy) {
	o.Policy = v
}

func (o V1ExtranetsB2bIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	return toSerialize, nil
}

func (o *V1ExtranetsB2bIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetsB2bIdPutRequest := _V1ExtranetsB2bIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetsB2bIdPutRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetsB2bIdPutRequest(varV1ExtranetsB2bIdPutRequest)

	return err
}

type NullableV1ExtranetsB2bIdPutRequest struct {
	value *V1ExtranetsB2bIdPutRequest
	isSet bool
}

func (v NullableV1ExtranetsB2bIdPutRequest) Get() *V1ExtranetsB2bIdPutRequest {
	return v.value
}

func (v *NullableV1ExtranetsB2bIdPutRequest) Set(val *V1ExtranetsB2bIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bIdPutRequest(val *V1ExtranetsB2bIdPutRequest) *NullableV1ExtranetsB2bIdPutRequest {
	return &NullableV1ExtranetsB2bIdPutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


