/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1AuthDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthDeleteResponse{}

// V1AuthDeleteResponse struct for V1AuthDeleteResponse
type V1AuthDeleteResponse struct {
	AffectedUsers []string `json:"affectedUsers,omitempty"`
	AllGroups *bool `json:"allGroups,omitempty"`
}

// NewV1AuthDeleteResponse instantiates a new V1AuthDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthDeleteResponse() *V1AuthDeleteResponse {
	this := V1AuthDeleteResponse{}
	return &this
}

// NewV1AuthDeleteResponseWithDefaults instantiates a new V1AuthDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthDeleteResponseWithDefaults() *V1AuthDeleteResponse {
	this := V1AuthDeleteResponse{}
	return &this
}

// GetAffectedUsers returns the AffectedUsers field value if set, zero value otherwise.
func (o *V1AuthDeleteResponse) GetAffectedUsers() []string {
	if o == nil || IsNil(o.AffectedUsers) {
		var ret []string
		return ret
	}
	return o.AffectedUsers
}

// GetAffectedUsersOk returns a tuple with the AffectedUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthDeleteResponse) GetAffectedUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.AffectedUsers) {
		return nil, false
	}
	return o.AffectedUsers, true
}

// HasAffectedUsers returns a boolean if a field has been set.
func (o *V1AuthDeleteResponse) HasAffectedUsers() bool {
	if o != nil && !IsNil(o.AffectedUsers) {
		return true
	}

	return false
}

// SetAffectedUsers gets a reference to the given []string and assigns it to the AffectedUsers field.
func (o *V1AuthDeleteResponse) SetAffectedUsers(v []string) {
	o.AffectedUsers = v
}

// GetAllGroups returns the AllGroups field value if set, zero value otherwise.
func (o *V1AuthDeleteResponse) GetAllGroups() bool {
	if o == nil || IsNil(o.AllGroups) {
		var ret bool
		return ret
	}
	return *o.AllGroups
}

// GetAllGroupsOk returns a tuple with the AllGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthDeleteResponse) GetAllGroupsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllGroups) {
		return nil, false
	}
	return o.AllGroups, true
}

// HasAllGroups returns a boolean if a field has been set.
func (o *V1AuthDeleteResponse) HasAllGroups() bool {
	if o != nil && !IsNil(o.AllGroups) {
		return true
	}

	return false
}

// SetAllGroups gets a reference to the given bool and assigns it to the AllGroups field.
func (o *V1AuthDeleteResponse) SetAllGroups(v bool) {
	o.AllGroups = &v
}

func (o V1AuthDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AffectedUsers) {
		toSerialize["affectedUsers"] = o.AffectedUsers
	}
	if !IsNil(o.AllGroups) {
		toSerialize["allGroups"] = o.AllGroups
	}
	return toSerialize, nil
}

type NullableV1AuthDeleteResponse struct {
	value *V1AuthDeleteResponse
	isSet bool
}

func (v NullableV1AuthDeleteResponse) Get() *V1AuthDeleteResponse {
	return v.value
}

func (v *NullableV1AuthDeleteResponse) Set(val *V1AuthDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthDeleteResponse(val *V1AuthDeleteResponse) *NullableV1AuthDeleteResponse {
	return &NullableV1AuthDeleteResponse{value: val, isSet: true}
}

func (v NullableV1AuthDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


