/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceApplicationProfileSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceApplicationProfileSummary{}

// AssuranceApplicationProfileSummary struct for AssuranceApplicationProfileSummary
type AssuranceApplicationProfileSummary struct {
	BucketSummaryList []AssuranceBucketSummary `json:"bucketSummaryList,omitempty"`
}

// NewAssuranceApplicationProfileSummary instantiates a new AssuranceApplicationProfileSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceApplicationProfileSummary() *AssuranceApplicationProfileSummary {
	this := AssuranceApplicationProfileSummary{}
	return &this
}

// NewAssuranceApplicationProfileSummaryWithDefaults instantiates a new AssuranceApplicationProfileSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceApplicationProfileSummaryWithDefaults() *AssuranceApplicationProfileSummary {
	this := AssuranceApplicationProfileSummary{}
	return &this
}

// GetBucketSummaryList returns the BucketSummaryList field value if set, zero value otherwise.
func (o *AssuranceApplicationProfileSummary) GetBucketSummaryList() []AssuranceBucketSummary {
	if o == nil || IsNil(o.BucketSummaryList) {
		var ret []AssuranceBucketSummary
		return ret
	}
	return o.BucketSummaryList
}

// GetBucketSummaryListOk returns a tuple with the BucketSummaryList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApplicationProfileSummary) GetBucketSummaryListOk() ([]AssuranceBucketSummary, bool) {
	if o == nil || IsNil(o.BucketSummaryList) {
		return nil, false
	}
	return o.BucketSummaryList, true
}

// HasBucketSummaryList returns a boolean if a field has been set.
func (o *AssuranceApplicationProfileSummary) HasBucketSummaryList() bool {
	if o != nil && !IsNil(o.BucketSummaryList) {
		return true
	}

	return false
}

// SetBucketSummaryList gets a reference to the given []AssuranceBucketSummary and assigns it to the BucketSummaryList field.
func (o *AssuranceApplicationProfileSummary) SetBucketSummaryList(v []AssuranceBucketSummary) {
	o.BucketSummaryList = v
}

func (o AssuranceApplicationProfileSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceApplicationProfileSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BucketSummaryList) {
		toSerialize["bucketSummaryList"] = o.BucketSummaryList
	}
	return toSerialize, nil
}

type NullableAssuranceApplicationProfileSummary struct {
	value *AssuranceApplicationProfileSummary
	isSet bool
}

func (v NullableAssuranceApplicationProfileSummary) Get() *AssuranceApplicationProfileSummary {
	return v.value
}

func (v *NullableAssuranceApplicationProfileSummary) Set(val *AssuranceApplicationProfileSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceApplicationProfileSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceApplicationProfileSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceApplicationProfileSummary(val *AssuranceApplicationProfileSummary) *NullableAssuranceApplicationProfileSummary {
	return &NullableAssuranceApplicationProfileSummary{value: val, isSet: true}
}

func (v NullableAssuranceApplicationProfileSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceApplicationProfileSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


