/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1EnterprisesGet200ResponseEnterprisesInnerCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EnterprisesGet200ResponseEnterprisesInnerCounts{}

// V1EnterprisesGet200ResponseEnterprisesInnerCounts struct for V1EnterprisesGet200ResponseEnterprisesInnerCounts
type V1EnterprisesGet200ResponseEnterprisesInnerCounts struct {
	ActiveDownCount *int64 `json:"activeDownCount,omitempty"`
	ActiveUpCount *int64 `json:"activeUpCount,omitempty"`
	DeactivatedDownCount *int64 `json:"deactivatedDownCount,omitempty"`
	DownSitesCount *int64 `json:"downSitesCount,omitempty"`
	EmptySitesCount *int64 `json:"emptySitesCount,omitempty"`
	ImpairedSitesCount *int64 `json:"impairedSitesCount,omitempty"`
	StagingDownCount *int64 `json:"stagingDownCount,omitempty"`
	StagingUpCount *int64 `json:"stagingUpCount,omitempty"`
	TotalCustomers *int64 `json:"totalCustomers,omitempty"`
	TotalEdges *int64 `json:"totalEdges,omitempty"`
	TotalMsps *int64 `json:"totalMsps,omitempty"`
	TotalSites *int64 `json:"totalSites,omitempty"`
	UpSitesCount *int64 `json:"upSitesCount,omitempty"`
}

// NewV1EnterprisesGet200ResponseEnterprisesInnerCounts instantiates a new V1EnterprisesGet200ResponseEnterprisesInnerCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EnterprisesGet200ResponseEnterprisesInnerCounts() *V1EnterprisesGet200ResponseEnterprisesInnerCounts {
	this := V1EnterprisesGet200ResponseEnterprisesInnerCounts{}
	return &this
}

// NewV1EnterprisesGet200ResponseEnterprisesInnerCountsWithDefaults instantiates a new V1EnterprisesGet200ResponseEnterprisesInnerCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EnterprisesGet200ResponseEnterprisesInnerCountsWithDefaults() *V1EnterprisesGet200ResponseEnterprisesInnerCounts {
	this := V1EnterprisesGet200ResponseEnterprisesInnerCounts{}
	return &this
}

// GetActiveDownCount returns the ActiveDownCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetActiveDownCount() int64 {
	if o == nil || IsNil(o.ActiveDownCount) {
		var ret int64
		return ret
	}
	return *o.ActiveDownCount
}

// GetActiveDownCountOk returns a tuple with the ActiveDownCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetActiveDownCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ActiveDownCount) {
		return nil, false
	}
	return o.ActiveDownCount, true
}

// HasActiveDownCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasActiveDownCount() bool {
	if o != nil && !IsNil(o.ActiveDownCount) {
		return true
	}

	return false
}

// SetActiveDownCount gets a reference to the given int64 and assigns it to the ActiveDownCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetActiveDownCount(v int64) {
	o.ActiveDownCount = &v
}

// GetActiveUpCount returns the ActiveUpCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetActiveUpCount() int64 {
	if o == nil || IsNil(o.ActiveUpCount) {
		var ret int64
		return ret
	}
	return *o.ActiveUpCount
}

// GetActiveUpCountOk returns a tuple with the ActiveUpCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetActiveUpCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ActiveUpCount) {
		return nil, false
	}
	return o.ActiveUpCount, true
}

// HasActiveUpCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasActiveUpCount() bool {
	if o != nil && !IsNil(o.ActiveUpCount) {
		return true
	}

	return false
}

// SetActiveUpCount gets a reference to the given int64 and assigns it to the ActiveUpCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetActiveUpCount(v int64) {
	o.ActiveUpCount = &v
}

// GetDeactivatedDownCount returns the DeactivatedDownCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetDeactivatedDownCount() int64 {
	if o == nil || IsNil(o.DeactivatedDownCount) {
		var ret int64
		return ret
	}
	return *o.DeactivatedDownCount
}

// GetDeactivatedDownCountOk returns a tuple with the DeactivatedDownCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetDeactivatedDownCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DeactivatedDownCount) {
		return nil, false
	}
	return o.DeactivatedDownCount, true
}

// HasDeactivatedDownCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasDeactivatedDownCount() bool {
	if o != nil && !IsNil(o.DeactivatedDownCount) {
		return true
	}

	return false
}

// SetDeactivatedDownCount gets a reference to the given int64 and assigns it to the DeactivatedDownCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetDeactivatedDownCount(v int64) {
	o.DeactivatedDownCount = &v
}

// GetDownSitesCount returns the DownSitesCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetDownSitesCount() int64 {
	if o == nil || IsNil(o.DownSitesCount) {
		var ret int64
		return ret
	}
	return *o.DownSitesCount
}

// GetDownSitesCountOk returns a tuple with the DownSitesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetDownSitesCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DownSitesCount) {
		return nil, false
	}
	return o.DownSitesCount, true
}

// HasDownSitesCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasDownSitesCount() bool {
	if o != nil && !IsNil(o.DownSitesCount) {
		return true
	}

	return false
}

// SetDownSitesCount gets a reference to the given int64 and assigns it to the DownSitesCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetDownSitesCount(v int64) {
	o.DownSitesCount = &v
}

// GetEmptySitesCount returns the EmptySitesCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetEmptySitesCount() int64 {
	if o == nil || IsNil(o.EmptySitesCount) {
		var ret int64
		return ret
	}
	return *o.EmptySitesCount
}

// GetEmptySitesCountOk returns a tuple with the EmptySitesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetEmptySitesCountOk() (*int64, bool) {
	if o == nil || IsNil(o.EmptySitesCount) {
		return nil, false
	}
	return o.EmptySitesCount, true
}

// HasEmptySitesCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasEmptySitesCount() bool {
	if o != nil && !IsNil(o.EmptySitesCount) {
		return true
	}

	return false
}

// SetEmptySitesCount gets a reference to the given int64 and assigns it to the EmptySitesCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetEmptySitesCount(v int64) {
	o.EmptySitesCount = &v
}

// GetImpairedSitesCount returns the ImpairedSitesCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetImpairedSitesCount() int64 {
	if o == nil || IsNil(o.ImpairedSitesCount) {
		var ret int64
		return ret
	}
	return *o.ImpairedSitesCount
}

// GetImpairedSitesCountOk returns a tuple with the ImpairedSitesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetImpairedSitesCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ImpairedSitesCount) {
		return nil, false
	}
	return o.ImpairedSitesCount, true
}

// HasImpairedSitesCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasImpairedSitesCount() bool {
	if o != nil && !IsNil(o.ImpairedSitesCount) {
		return true
	}

	return false
}

// SetImpairedSitesCount gets a reference to the given int64 and assigns it to the ImpairedSitesCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetImpairedSitesCount(v int64) {
	o.ImpairedSitesCount = &v
}

// GetStagingDownCount returns the StagingDownCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetStagingDownCount() int64 {
	if o == nil || IsNil(o.StagingDownCount) {
		var ret int64
		return ret
	}
	return *o.StagingDownCount
}

// GetStagingDownCountOk returns a tuple with the StagingDownCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetStagingDownCountOk() (*int64, bool) {
	if o == nil || IsNil(o.StagingDownCount) {
		return nil, false
	}
	return o.StagingDownCount, true
}

// HasStagingDownCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasStagingDownCount() bool {
	if o != nil && !IsNil(o.StagingDownCount) {
		return true
	}

	return false
}

// SetStagingDownCount gets a reference to the given int64 and assigns it to the StagingDownCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetStagingDownCount(v int64) {
	o.StagingDownCount = &v
}

// GetStagingUpCount returns the StagingUpCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetStagingUpCount() int64 {
	if o == nil || IsNil(o.StagingUpCount) {
		var ret int64
		return ret
	}
	return *o.StagingUpCount
}

// GetStagingUpCountOk returns a tuple with the StagingUpCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetStagingUpCountOk() (*int64, bool) {
	if o == nil || IsNil(o.StagingUpCount) {
		return nil, false
	}
	return o.StagingUpCount, true
}

// HasStagingUpCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasStagingUpCount() bool {
	if o != nil && !IsNil(o.StagingUpCount) {
		return true
	}

	return false
}

// SetStagingUpCount gets a reference to the given int64 and assigns it to the StagingUpCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetStagingUpCount(v int64) {
	o.StagingUpCount = &v
}

// GetTotalCustomers returns the TotalCustomers field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalCustomers() int64 {
	if o == nil || IsNil(o.TotalCustomers) {
		var ret int64
		return ret
	}
	return *o.TotalCustomers
}

// GetTotalCustomersOk returns a tuple with the TotalCustomers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalCustomersOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCustomers) {
		return nil, false
	}
	return o.TotalCustomers, true
}

// HasTotalCustomers returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasTotalCustomers() bool {
	if o != nil && !IsNil(o.TotalCustomers) {
		return true
	}

	return false
}

// SetTotalCustomers gets a reference to the given int64 and assigns it to the TotalCustomers field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetTotalCustomers(v int64) {
	o.TotalCustomers = &v
}

// GetTotalEdges returns the TotalEdges field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalEdges() int64 {
	if o == nil || IsNil(o.TotalEdges) {
		var ret int64
		return ret
	}
	return *o.TotalEdges
}

// GetTotalEdgesOk returns a tuple with the TotalEdges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalEdgesOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalEdges) {
		return nil, false
	}
	return o.TotalEdges, true
}

// HasTotalEdges returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasTotalEdges() bool {
	if o != nil && !IsNil(o.TotalEdges) {
		return true
	}

	return false
}

// SetTotalEdges gets a reference to the given int64 and assigns it to the TotalEdges field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetTotalEdges(v int64) {
	o.TotalEdges = &v
}

// GetTotalMsps returns the TotalMsps field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalMsps() int64 {
	if o == nil || IsNil(o.TotalMsps) {
		var ret int64
		return ret
	}
	return *o.TotalMsps
}

// GetTotalMspsOk returns a tuple with the TotalMsps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalMspsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalMsps) {
		return nil, false
	}
	return o.TotalMsps, true
}

// HasTotalMsps returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasTotalMsps() bool {
	if o != nil && !IsNil(o.TotalMsps) {
		return true
	}

	return false
}

// SetTotalMsps gets a reference to the given int64 and assigns it to the TotalMsps field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetTotalMsps(v int64) {
	o.TotalMsps = &v
}

// GetTotalSites returns the TotalSites field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalSites() int64 {
	if o == nil || IsNil(o.TotalSites) {
		var ret int64
		return ret
	}
	return *o.TotalSites
}

// GetTotalSitesOk returns a tuple with the TotalSites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetTotalSitesOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalSites) {
		return nil, false
	}
	return o.TotalSites, true
}

// HasTotalSites returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasTotalSites() bool {
	if o != nil && !IsNil(o.TotalSites) {
		return true
	}

	return false
}

// SetTotalSites gets a reference to the given int64 and assigns it to the TotalSites field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetTotalSites(v int64) {
	o.TotalSites = &v
}

// GetUpSitesCount returns the UpSitesCount field value if set, zero value otherwise.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetUpSitesCount() int64 {
	if o == nil || IsNil(o.UpSitesCount) {
		var ret int64
		return ret
	}
	return *o.UpSitesCount
}

// GetUpSitesCountOk returns a tuple with the UpSitesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) GetUpSitesCountOk() (*int64, bool) {
	if o == nil || IsNil(o.UpSitesCount) {
		return nil, false
	}
	return o.UpSitesCount, true
}

// HasUpSitesCount returns a boolean if a field has been set.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) HasUpSitesCount() bool {
	if o != nil && !IsNil(o.UpSitesCount) {
		return true
	}

	return false
}

// SetUpSitesCount gets a reference to the given int64 and assigns it to the UpSitesCount field.
func (o *V1EnterprisesGet200ResponseEnterprisesInnerCounts) SetUpSitesCount(v int64) {
	o.UpSitesCount = &v
}

func (o V1EnterprisesGet200ResponseEnterprisesInnerCounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EnterprisesGet200ResponseEnterprisesInnerCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActiveDownCount) {
		toSerialize["activeDownCount"] = o.ActiveDownCount
	}
	if !IsNil(o.ActiveUpCount) {
		toSerialize["activeUpCount"] = o.ActiveUpCount
	}
	if !IsNil(o.DeactivatedDownCount) {
		toSerialize["deactivatedDownCount"] = o.DeactivatedDownCount
	}
	if !IsNil(o.DownSitesCount) {
		toSerialize["downSitesCount"] = o.DownSitesCount
	}
	if !IsNil(o.EmptySitesCount) {
		toSerialize["emptySitesCount"] = o.EmptySitesCount
	}
	if !IsNil(o.ImpairedSitesCount) {
		toSerialize["impairedSitesCount"] = o.ImpairedSitesCount
	}
	if !IsNil(o.StagingDownCount) {
		toSerialize["stagingDownCount"] = o.StagingDownCount
	}
	if !IsNil(o.StagingUpCount) {
		toSerialize["stagingUpCount"] = o.StagingUpCount
	}
	if !IsNil(o.TotalCustomers) {
		toSerialize["totalCustomers"] = o.TotalCustomers
	}
	if !IsNil(o.TotalEdges) {
		toSerialize["totalEdges"] = o.TotalEdges
	}
	if !IsNil(o.TotalMsps) {
		toSerialize["totalMsps"] = o.TotalMsps
	}
	if !IsNil(o.TotalSites) {
		toSerialize["totalSites"] = o.TotalSites
	}
	if !IsNil(o.UpSitesCount) {
		toSerialize["upSitesCount"] = o.UpSitesCount
	}
	return toSerialize, nil
}

type NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts struct {
	value *V1EnterprisesGet200ResponseEnterprisesInnerCounts
	isSet bool
}

func (v NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) Get() *V1EnterprisesGet200ResponseEnterprisesInnerCounts {
	return v.value
}

func (v *NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) Set(val *V1EnterprisesGet200ResponseEnterprisesInnerCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EnterprisesGet200ResponseEnterprisesInnerCounts(val *V1EnterprisesGet200ResponseEnterprisesInnerCounts) *NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts {
	return &NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts{value: val, isSet: true}
}

func (v NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EnterprisesGet200ResponseEnterprisesInnerCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


