/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the StatsmonV2SystemStatsSelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsmonV2SystemStatsSelector{}

// StatsmonV2SystemStatsSelector struct for StatsmonV2SystemStatsSelector
type StatsmonV2SystemStatsSelector struct {
	Type *string `json:"type,omitempty"`
}

// NewStatsmonV2SystemStatsSelector instantiates a new StatsmonV2SystemStatsSelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsmonV2SystemStatsSelector() *StatsmonV2SystemStatsSelector {
	this := StatsmonV2SystemStatsSelector{}
	return &this
}

// NewStatsmonV2SystemStatsSelectorWithDefaults instantiates a new StatsmonV2SystemStatsSelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsmonV2SystemStatsSelectorWithDefaults() *StatsmonV2SystemStatsSelector {
	this := StatsmonV2SystemStatsSelector{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *StatsmonV2SystemStatsSelector) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2SystemStatsSelector) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *StatsmonV2SystemStatsSelector) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *StatsmonV2SystemStatsSelector) SetType(v string) {
	o.Type = &v
}

func (o StatsmonV2SystemStatsSelector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsmonV2SystemStatsSelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableStatsmonV2SystemStatsSelector struct {
	value *StatsmonV2SystemStatsSelector
	isSet bool
}

func (v NullableStatsmonV2SystemStatsSelector) Get() *StatsmonV2SystemStatsSelector {
	return v.value
}

func (v *NullableStatsmonV2SystemStatsSelector) Set(val *StatsmonV2SystemStatsSelector) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsmonV2SystemStatsSelector) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsmonV2SystemStatsSelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsmonV2SystemStatsSelector(val *StatsmonV2SystemStatsSelector) *NullableStatsmonV2SystemStatsSelector {
	return &NullableStatsmonV2SystemStatsSelector{value: val, isSet: true}
}

func (v NullableStatsmonV2SystemStatsSelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsmonV2SystemStatsSelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


