/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest{}

// V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest struct for V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest
type V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest struct {
	// the id of a producer/service (required)
	Id int64 `json:"id"`
	// whether the entity is a b2b entity (true for b2b entity, false for local extranet entity) (required)
	IsB2B bool `json:"isB2B"`
	// whether the entity is a provider or consumer (required)
	IsProvider bool `json:"isProvider"`
	TimeWindow StatsmonTimeWindow `json:"timeWindow"`
}

type _V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest

// NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest instantiates a new V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest(id int64, isB2B bool, isProvider bool, timeWindow StatsmonTimeWindow) *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest {
	this := V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest{}
	this.Id = id
	this.IsB2B = isB2B
	this.IsProvider = isProvider
	this.TimeWindow = timeWindow
	return &this
}

// NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequestWithDefaults instantiates a new V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequestWithDefaults() *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest {
	this := V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest{}
	return &this
}

// GetId returns the Id field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) SetId(v int64) {
	o.Id = v
}

// GetIsB2B returns the IsB2B field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetIsB2B() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsB2B
}

// GetIsB2BOk returns a tuple with the IsB2B field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetIsB2BOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsB2B, true
}

// SetIsB2B sets field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) SetIsB2B(v bool) {
	o.IsB2B = v
}

// GetIsProvider returns the IsProvider field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetIsProvider() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsProvider
}

// GetIsProviderOk returns a tuple with the IsProvider field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetIsProviderOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsProvider, true
}

// SetIsProvider sets field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) SetIsProvider(v bool) {
	o.IsProvider = v
}

// GetTimeWindow returns the TimeWindow field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetTimeWindow() StatsmonTimeWindow {
	if o == nil {
		var ret StatsmonTimeWindow
		return ret
	}

	return o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) GetTimeWindowOk() (*StatsmonTimeWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeWindow, true
}

// SetTimeWindow sets field value
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) SetTimeWindow(v StatsmonTimeWindow) {
	o.TimeWindow = v
}

func (o V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["isB2B"] = o.IsB2B
	toSerialize["isProvider"] = o.IsProvider
	toSerialize["timeWindow"] = o.TimeWindow
	return toSerialize, nil
}

func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"isB2B",
		"isProvider",
		"timeWindow",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest := _V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest(varV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest)

	return err
}

type NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest struct {
	value *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest
	isSet bool
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) Get() *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) Set(val *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest(val *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest {
	return &NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


