/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesInventorySerialNumPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesInventorySerialNumPost200Response{}

// V1DevicesInventorySerialNumPost200Response struct for V1DevicesInventorySerialNumPost200Response
type V1DevicesInventorySerialNumPost200Response struct {
	Inventory []V1DevicesInventoryGet200ResponseInventoryInner `json:"inventory,omitempty"`
}

// NewV1DevicesInventorySerialNumPost200Response instantiates a new V1DevicesInventorySerialNumPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesInventorySerialNumPost200Response() *V1DevicesInventorySerialNumPost200Response {
	this := V1DevicesInventorySerialNumPost200Response{}
	return &this
}

// NewV1DevicesInventorySerialNumPost200ResponseWithDefaults instantiates a new V1DevicesInventorySerialNumPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesInventorySerialNumPost200ResponseWithDefaults() *V1DevicesInventorySerialNumPost200Response {
	this := V1DevicesInventorySerialNumPost200Response{}
	return &this
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *V1DevicesInventorySerialNumPost200Response) GetInventory() []V1DevicesInventoryGet200ResponseInventoryInner {
	if o == nil || IsNil(o.Inventory) {
		var ret []V1DevicesInventoryGet200ResponseInventoryInner
		return ret
	}
	return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesInventorySerialNumPost200Response) GetInventoryOk() ([]V1DevicesInventoryGet200ResponseInventoryInner, bool) {
	if o == nil || IsNil(o.Inventory) {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *V1DevicesInventorySerialNumPost200Response) HasInventory() bool {
	if o != nil && !IsNil(o.Inventory) {
		return true
	}

	return false
}

// SetInventory gets a reference to the given []V1DevicesInventoryGet200ResponseInventoryInner and assigns it to the Inventory field.
func (o *V1DevicesInventorySerialNumPost200Response) SetInventory(v []V1DevicesInventoryGet200ResponseInventoryInner) {
	o.Inventory = v
}

func (o V1DevicesInventorySerialNumPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesInventorySerialNumPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Inventory) {
		toSerialize["inventory"] = o.Inventory
	}
	return toSerialize, nil
}

type NullableV1DevicesInventorySerialNumPost200Response struct {
	value *V1DevicesInventorySerialNumPost200Response
	isSet bool
}

func (v NullableV1DevicesInventorySerialNumPost200Response) Get() *V1DevicesInventorySerialNumPost200Response {
	return v.value
}

func (v *NullableV1DevicesInventorySerialNumPost200Response) Set(val *V1DevicesInventorySerialNumPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesInventorySerialNumPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesInventorySerialNumPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesInventorySerialNumPost200Response(val *V1DevicesInventorySerialNumPost200Response) *NullableV1DevicesInventorySerialNumPost200Response {
	return &NullableV1DevicesInventorySerialNumPost200Response{value: val, isSet: true}
}

func (v NullableV1DevicesInventorySerialNumPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesInventorySerialNumPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


