/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalAppsGraphiantGet200ResponseEntriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalAppsGraphiantGet200ResponseEntriesInner{}

// V1GlobalAppsGraphiantGet200ResponseEntriesInner struct for V1GlobalAppsGraphiantGet200ResponseEntriesInner
type V1GlobalAppsGraphiantGet200ResponseEntriesInner struct {
	App *V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList `json:"app,omitempty"`
	AppListReferenceCount *int32 `json:"appListReferenceCount,omitempty"`
	PolicyReferenceCount *int32 `json:"policyReferenceCount,omitempty"`
}

// NewV1GlobalAppsGraphiantGet200ResponseEntriesInner instantiates a new V1GlobalAppsGraphiantGet200ResponseEntriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalAppsGraphiantGet200ResponseEntriesInner() *V1GlobalAppsGraphiantGet200ResponseEntriesInner {
	this := V1GlobalAppsGraphiantGet200ResponseEntriesInner{}
	return &this
}

// NewV1GlobalAppsGraphiantGet200ResponseEntriesInnerWithDefaults instantiates a new V1GlobalAppsGraphiantGet200ResponseEntriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalAppsGraphiantGet200ResponseEntriesInnerWithDefaults() *V1GlobalAppsGraphiantGet200ResponseEntriesInner {
	this := V1GlobalAppsGraphiantGet200ResponseEntriesInner{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetApp() V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList {
	if o == nil || IsNil(o.App) {
		var ret V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetAppOk() (*V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList and assigns it to the App field.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) SetApp(v V1GlobalAppsAppListsGet200ResponseEntriesInnerAppList) {
	o.App = &v
}

// GetAppListReferenceCount returns the AppListReferenceCount field value if set, zero value otherwise.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetAppListReferenceCount() int32 {
	if o == nil || IsNil(o.AppListReferenceCount) {
		var ret int32
		return ret
	}
	return *o.AppListReferenceCount
}

// GetAppListReferenceCountOk returns a tuple with the AppListReferenceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetAppListReferenceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AppListReferenceCount) {
		return nil, false
	}
	return o.AppListReferenceCount, true
}

// HasAppListReferenceCount returns a boolean if a field has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) HasAppListReferenceCount() bool {
	if o != nil && !IsNil(o.AppListReferenceCount) {
		return true
	}

	return false
}

// SetAppListReferenceCount gets a reference to the given int32 and assigns it to the AppListReferenceCount field.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) SetAppListReferenceCount(v int32) {
	o.AppListReferenceCount = &v
}

// GetPolicyReferenceCount returns the PolicyReferenceCount field value if set, zero value otherwise.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetPolicyReferenceCount() int32 {
	if o == nil || IsNil(o.PolicyReferenceCount) {
		var ret int32
		return ret
	}
	return *o.PolicyReferenceCount
}

// GetPolicyReferenceCountOk returns a tuple with the PolicyReferenceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) GetPolicyReferenceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyReferenceCount) {
		return nil, false
	}
	return o.PolicyReferenceCount, true
}

// HasPolicyReferenceCount returns a boolean if a field has been set.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) HasPolicyReferenceCount() bool {
	if o != nil && !IsNil(o.PolicyReferenceCount) {
		return true
	}

	return false
}

// SetPolicyReferenceCount gets a reference to the given int32 and assigns it to the PolicyReferenceCount field.
func (o *V1GlobalAppsGraphiantGet200ResponseEntriesInner) SetPolicyReferenceCount(v int32) {
	o.PolicyReferenceCount = &v
}

func (o V1GlobalAppsGraphiantGet200ResponseEntriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalAppsGraphiantGet200ResponseEntriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.AppListReferenceCount) {
		toSerialize["appListReferenceCount"] = o.AppListReferenceCount
	}
	if !IsNil(o.PolicyReferenceCount) {
		toSerialize["policyReferenceCount"] = o.PolicyReferenceCount
	}
	return toSerialize, nil
}

type NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner struct {
	value *V1GlobalAppsGraphiantGet200ResponseEntriesInner
	isSet bool
}

func (v NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) Get() *V1GlobalAppsGraphiantGet200ResponseEntriesInner {
	return v.value
}

func (v *NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) Set(val *V1GlobalAppsGraphiantGet200ResponseEntriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalAppsGraphiantGet200ResponseEntriesInner(val *V1GlobalAppsGraphiantGet200ResponseEntriesInner) *NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner {
	return &NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner{value: val, isSet: true}
}

func (v NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalAppsGraphiantGet200ResponseEntriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


