/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceGetclassifiedapplicationlistGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceGetclassifiedapplicationlistGetResponse{}

// V2AssuranceGetclassifiedapplicationlistGetResponse struct for V2AssuranceGetclassifiedapplicationlistGetResponse
type V2AssuranceGetclassifiedapplicationlistGetResponse struct {
	ClassifiedApplicationList []AssuranceClassifiedApplication `json:"classifiedApplicationList,omitempty"`
}

// NewV2AssuranceGetclassifiedapplicationlistGetResponse instantiates a new V2AssuranceGetclassifiedapplicationlistGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceGetclassifiedapplicationlistGetResponse() *V2AssuranceGetclassifiedapplicationlistGetResponse {
	this := V2AssuranceGetclassifiedapplicationlistGetResponse{}
	return &this
}

// NewV2AssuranceGetclassifiedapplicationlistGetResponseWithDefaults instantiates a new V2AssuranceGetclassifiedapplicationlistGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceGetclassifiedapplicationlistGetResponseWithDefaults() *V2AssuranceGetclassifiedapplicationlistGetResponse {
	this := V2AssuranceGetclassifiedapplicationlistGetResponse{}
	return &this
}

// GetClassifiedApplicationList returns the ClassifiedApplicationList field value if set, zero value otherwise.
func (o *V2AssuranceGetclassifiedapplicationlistGetResponse) GetClassifiedApplicationList() []AssuranceClassifiedApplication {
	if o == nil || IsNil(o.ClassifiedApplicationList) {
		var ret []AssuranceClassifiedApplication
		return ret
	}
	return o.ClassifiedApplicationList
}

// GetClassifiedApplicationListOk returns a tuple with the ClassifiedApplicationList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceGetclassifiedapplicationlistGetResponse) GetClassifiedApplicationListOk() ([]AssuranceClassifiedApplication, bool) {
	if o == nil || IsNil(o.ClassifiedApplicationList) {
		return nil, false
	}
	return o.ClassifiedApplicationList, true
}

// HasClassifiedApplicationList returns a boolean if a field has been set.
func (o *V2AssuranceGetclassifiedapplicationlistGetResponse) HasClassifiedApplicationList() bool {
	if o != nil && !IsNil(o.ClassifiedApplicationList) {
		return true
	}

	return false
}

// SetClassifiedApplicationList gets a reference to the given []AssuranceClassifiedApplication and assigns it to the ClassifiedApplicationList field.
func (o *V2AssuranceGetclassifiedapplicationlistGetResponse) SetClassifiedApplicationList(v []AssuranceClassifiedApplication) {
	o.ClassifiedApplicationList = v
}

func (o V2AssuranceGetclassifiedapplicationlistGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceGetclassifiedapplicationlistGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClassifiedApplicationList) {
		toSerialize["classifiedApplicationList"] = o.ClassifiedApplicationList
	}
	return toSerialize, nil
}

type NullableV2AssuranceGetclassifiedapplicationlistGetResponse struct {
	value *V2AssuranceGetclassifiedapplicationlistGetResponse
	isSet bool
}

func (v NullableV2AssuranceGetclassifiedapplicationlistGetResponse) Get() *V2AssuranceGetclassifiedapplicationlistGetResponse {
	return v.value
}

func (v *NullableV2AssuranceGetclassifiedapplicationlistGetResponse) Set(val *V2AssuranceGetclassifiedapplicationlistGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceGetclassifiedapplicationlistGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceGetclassifiedapplicationlistGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceGetclassifiedapplicationlistGetResponse(val *V2AssuranceGetclassifiedapplicationlistGetResponse) *NullableV2AssuranceGetclassifiedapplicationlistGetResponse {
	return &NullableV2AssuranceGetclassifiedapplicationlistGetResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceGetclassifiedapplicationlistGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceGetclassifiedapplicationlistGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


