/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the StatsmonV2Edge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsmonV2Edge{}

// StatsmonV2Edge struct for StatsmonV2Edge
type StatsmonV2Edge struct {
	A *int32 `json:"a,omitempty"`
	B *int32 `json:"b,omitempty"`
	CircuitsInfo []StatsmonV2EdgeedgeCircuitInfo `json:"circuitsInfo,omitempty"`
	Connections []StatsmonV2Connection `json:"connections,omitempty"`
	Name *string `json:"name,omitempty"`
	Quality *string `json:"quality,omitempty"`
}

// NewStatsmonV2Edge instantiates a new StatsmonV2Edge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsmonV2Edge() *StatsmonV2Edge {
	this := StatsmonV2Edge{}
	return &this
}

// NewStatsmonV2EdgeWithDefaults instantiates a new StatsmonV2Edge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsmonV2EdgeWithDefaults() *StatsmonV2Edge {
	this := StatsmonV2Edge{}
	return &this
}

// GetA returns the A field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetA() int32 {
	if o == nil || IsNil(o.A) {
		var ret int32
		return ret
	}
	return *o.A
}

// GetAOk returns a tuple with the A field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetAOk() (*int32, bool) {
	if o == nil || IsNil(o.A) {
		return nil, false
	}
	return o.A, true
}

// HasA returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasA() bool {
	if o != nil && !IsNil(o.A) {
		return true
	}

	return false
}

// SetA gets a reference to the given int32 and assigns it to the A field.
func (o *StatsmonV2Edge) SetA(v int32) {
	o.A = &v
}

// GetB returns the B field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetB() int32 {
	if o == nil || IsNil(o.B) {
		var ret int32
		return ret
	}
	return *o.B
}

// GetBOk returns a tuple with the B field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetBOk() (*int32, bool) {
	if o == nil || IsNil(o.B) {
		return nil, false
	}
	return o.B, true
}

// HasB returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasB() bool {
	if o != nil && !IsNil(o.B) {
		return true
	}

	return false
}

// SetB gets a reference to the given int32 and assigns it to the B field.
func (o *StatsmonV2Edge) SetB(v int32) {
	o.B = &v
}

// GetCircuitsInfo returns the CircuitsInfo field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetCircuitsInfo() []StatsmonV2EdgeedgeCircuitInfo {
	if o == nil || IsNil(o.CircuitsInfo) {
		var ret []StatsmonV2EdgeedgeCircuitInfo
		return ret
	}
	return o.CircuitsInfo
}

// GetCircuitsInfoOk returns a tuple with the CircuitsInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetCircuitsInfoOk() ([]StatsmonV2EdgeedgeCircuitInfo, bool) {
	if o == nil || IsNil(o.CircuitsInfo) {
		return nil, false
	}
	return o.CircuitsInfo, true
}

// HasCircuitsInfo returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasCircuitsInfo() bool {
	if o != nil && !IsNil(o.CircuitsInfo) {
		return true
	}

	return false
}

// SetCircuitsInfo gets a reference to the given []StatsmonV2EdgeedgeCircuitInfo and assigns it to the CircuitsInfo field.
func (o *StatsmonV2Edge) SetCircuitsInfo(v []StatsmonV2EdgeedgeCircuitInfo) {
	o.CircuitsInfo = v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetConnections() []StatsmonV2Connection {
	if o == nil || IsNil(o.Connections) {
		var ret []StatsmonV2Connection
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetConnectionsOk() ([]StatsmonV2Connection, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []StatsmonV2Connection and assigns it to the Connections field.
func (o *StatsmonV2Edge) SetConnections(v []StatsmonV2Connection) {
	o.Connections = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StatsmonV2Edge) SetName(v string) {
	o.Name = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *StatsmonV2Edge) GetQuality() string {
	if o == nil || IsNil(o.Quality) {
		var ret string
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2Edge) GetQualityOk() (*string, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *StatsmonV2Edge) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given string and assigns it to the Quality field.
func (o *StatsmonV2Edge) SetQuality(v string) {
	o.Quality = &v
}

func (o StatsmonV2Edge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsmonV2Edge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.A) {
		toSerialize["a"] = o.A
	}
	if !IsNil(o.B) {
		toSerialize["b"] = o.B
	}
	if !IsNil(o.CircuitsInfo) {
		toSerialize["circuitsInfo"] = o.CircuitsInfo
	}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	return toSerialize, nil
}

type NullableStatsmonV2Edge struct {
	value *StatsmonV2Edge
	isSet bool
}

func (v NullableStatsmonV2Edge) Get() *StatsmonV2Edge {
	return v.value
}

func (v *NullableStatsmonV2Edge) Set(val *StatsmonV2Edge) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsmonV2Edge) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsmonV2Edge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsmonV2Edge(val *StatsmonV2Edge) *NullableStatsmonV2Edge {
	return &NullableStatsmonV2Edge{value: val, isSet: true}
}

func (v NullableStatsmonV2Edge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsmonV2Edge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


