/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1TroubleshootingDeviceDeviceIdPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1TroubleshootingDeviceDeviceIdPost200Response{}

// V1TroubleshootingDeviceDeviceIdPost200Response struct for V1TroubleshootingDeviceDeviceIdPost200Response
type V1TroubleshootingDeviceDeviceIdPost200Response struct {
	MaintenanceMode *bool `json:"MaintenanceMode,omitempty"`
	ColrActive *bool `json:"colrActive,omitempty"`
	ControlPlane *V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane `json:"controlPlane,omitempty"`
	DataPlane *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane `json:"dataPlane,omitempty"`
	Issues []V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner `json:"issues,omitempty"`
	LifecycleStatus *string `json:"lifecycleStatus,omitempty"`
	Status *string `json:"status,omitempty"`
	SwVersion *string `json:"swVersion,omitempty"`
	SwVersionV2 *V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion `json:"swVersionV2,omitempty"`
	SystemPlane *V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane `json:"systemPlane,omitempty"`
	UpSinceTs *V1AlarmHistoryGet200ResponseHistoryInnerTime `json:"upSinceTs,omitempty"`
}

// NewV1TroubleshootingDeviceDeviceIdPost200Response instantiates a new V1TroubleshootingDeviceDeviceIdPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1TroubleshootingDeviceDeviceIdPost200Response() *V1TroubleshootingDeviceDeviceIdPost200Response {
	this := V1TroubleshootingDeviceDeviceIdPost200Response{}
	return &this
}

// NewV1TroubleshootingDeviceDeviceIdPost200ResponseWithDefaults instantiates a new V1TroubleshootingDeviceDeviceIdPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1TroubleshootingDeviceDeviceIdPost200ResponseWithDefaults() *V1TroubleshootingDeviceDeviceIdPost200Response {
	this := V1TroubleshootingDeviceDeviceIdPost200Response{}
	return &this
}

// GetMaintenanceMode returns the MaintenanceMode field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetMaintenanceMode() bool {
	if o == nil || IsNil(o.MaintenanceMode) {
		var ret bool
		return ret
	}
	return *o.MaintenanceMode
}

// GetMaintenanceModeOk returns a tuple with the MaintenanceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetMaintenanceModeOk() (*bool, bool) {
	if o == nil || IsNil(o.MaintenanceMode) {
		return nil, false
	}
	return o.MaintenanceMode, true
}

// HasMaintenanceMode returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasMaintenanceMode() bool {
	if o != nil && !IsNil(o.MaintenanceMode) {
		return true
	}

	return false
}

// SetMaintenanceMode gets a reference to the given bool and assigns it to the MaintenanceMode field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetMaintenanceMode(v bool) {
	o.MaintenanceMode = &v
}

// GetColrActive returns the ColrActive field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetColrActive() bool {
	if o == nil || IsNil(o.ColrActive) {
		var ret bool
		return ret
	}
	return *o.ColrActive
}

// GetColrActiveOk returns a tuple with the ColrActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetColrActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.ColrActive) {
		return nil, false
	}
	return o.ColrActive, true
}

// HasColrActive returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasColrActive() bool {
	if o != nil && !IsNil(o.ColrActive) {
		return true
	}

	return false
}

// SetColrActive gets a reference to the given bool and assigns it to the ColrActive field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetColrActive(v bool) {
	o.ColrActive = &v
}

// GetControlPlane returns the ControlPlane field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetControlPlane() V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane {
	if o == nil || IsNil(o.ControlPlane) {
		var ret V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane
		return ret
	}
	return *o.ControlPlane
}

// GetControlPlaneOk returns a tuple with the ControlPlane field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetControlPlaneOk() (*V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane, bool) {
	if o == nil || IsNil(o.ControlPlane) {
		return nil, false
	}
	return o.ControlPlane, true
}

// HasControlPlane returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasControlPlane() bool {
	if o != nil && !IsNil(o.ControlPlane) {
		return true
	}

	return false
}

// SetControlPlane gets a reference to the given V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane and assigns it to the ControlPlane field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetControlPlane(v V1TroubleshootingDeviceDeviceIdPost200ResponseControlPlane) {
	o.ControlPlane = &v
}

// GetDataPlane returns the DataPlane field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetDataPlane() V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane {
	if o == nil || IsNil(o.DataPlane) {
		var ret V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane
		return ret
	}
	return *o.DataPlane
}

// GetDataPlaneOk returns a tuple with the DataPlane field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetDataPlaneOk() (*V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane, bool) {
	if o == nil || IsNil(o.DataPlane) {
		return nil, false
	}
	return o.DataPlane, true
}

// HasDataPlane returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasDataPlane() bool {
	if o != nil && !IsNil(o.DataPlane) {
		return true
	}

	return false
}

// SetDataPlane gets a reference to the given V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane and assigns it to the DataPlane field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetDataPlane(v V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) {
	o.DataPlane = &v
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetIssues() []V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner {
	if o == nil || IsNil(o.Issues) {
		var ret []V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner
		return ret
	}
	return o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetIssuesOk() ([]V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner, bool) {
	if o == nil || IsNil(o.Issues) {
		return nil, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given []V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner and assigns it to the Issues field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetIssues(v []V1BackboneHealthDeviceDeviceIdPost200ResponseIssuesInner) {
	o.Issues = v
}

// GetLifecycleStatus returns the LifecycleStatus field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetLifecycleStatus() string {
	if o == nil || IsNil(o.LifecycleStatus) {
		var ret string
		return ret
	}
	return *o.LifecycleStatus
}

// GetLifecycleStatusOk returns a tuple with the LifecycleStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetLifecycleStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LifecycleStatus) {
		return nil, false
	}
	return o.LifecycleStatus, true
}

// HasLifecycleStatus returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasLifecycleStatus() bool {
	if o != nil && !IsNil(o.LifecycleStatus) {
		return true
	}

	return false
}

// SetLifecycleStatus gets a reference to the given string and assigns it to the LifecycleStatus field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetLifecycleStatus(v string) {
	o.LifecycleStatus = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetStatus(v string) {
	o.Status = &v
}

// GetSwVersion returns the SwVersion field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSwVersion() string {
	if o == nil || IsNil(o.SwVersion) {
		var ret string
		return ret
	}
	return *o.SwVersion
}

// GetSwVersionOk returns a tuple with the SwVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSwVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SwVersion) {
		return nil, false
	}
	return o.SwVersion, true
}

// HasSwVersion returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasSwVersion() bool {
	if o != nil && !IsNil(o.SwVersion) {
		return true
	}

	return false
}

// SetSwVersion gets a reference to the given string and assigns it to the SwVersion field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetSwVersion(v string) {
	o.SwVersion = &v
}

// GetSwVersionV2 returns the SwVersionV2 field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSwVersionV2() V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion {
	if o == nil || IsNil(o.SwVersionV2) {
		var ret V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion
		return ret
	}
	return *o.SwVersionV2
}

// GetSwVersionV2Ok returns a tuple with the SwVersionV2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSwVersionV2Ok() (*V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion, bool) {
	if o == nil || IsNil(o.SwVersionV2) {
		return nil, false
	}
	return o.SwVersionV2, true
}

// HasSwVersionV2 returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasSwVersionV2() bool {
	if o != nil && !IsNil(o.SwVersionV2) {
		return true
	}

	return false
}

// SetSwVersionV2 gets a reference to the given V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion and assigns it to the SwVersionV2 field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetSwVersionV2(v V1EdgesHardwareAssignedGet200ResponseEdgesSummaryInnerUpgradeSummaryLastRunningVersion) {
	o.SwVersionV2 = &v
}

// GetSystemPlane returns the SystemPlane field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSystemPlane() V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane {
	if o == nil || IsNil(o.SystemPlane) {
		var ret V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane
		return ret
	}
	return *o.SystemPlane
}

// GetSystemPlaneOk returns a tuple with the SystemPlane field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetSystemPlaneOk() (*V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane, bool) {
	if o == nil || IsNil(o.SystemPlane) {
		return nil, false
	}
	return o.SystemPlane, true
}

// HasSystemPlane returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasSystemPlane() bool {
	if o != nil && !IsNil(o.SystemPlane) {
		return true
	}

	return false
}

// SetSystemPlane gets a reference to the given V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane and assigns it to the SystemPlane field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetSystemPlane(v V1TroubleshootingDeviceDeviceIdPost200ResponseSystemPlane) {
	o.SystemPlane = &v
}

// GetUpSinceTs returns the UpSinceTs field value if set, zero value otherwise.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetUpSinceTs() V1AlarmHistoryGet200ResponseHistoryInnerTime {
	if o == nil || IsNil(o.UpSinceTs) {
		var ret V1AlarmHistoryGet200ResponseHistoryInnerTime
		return ret
	}
	return *o.UpSinceTs
}

// GetUpSinceTsOk returns a tuple with the UpSinceTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) GetUpSinceTsOk() (*V1AlarmHistoryGet200ResponseHistoryInnerTime, bool) {
	if o == nil || IsNil(o.UpSinceTs) {
		return nil, false
	}
	return o.UpSinceTs, true
}

// HasUpSinceTs returns a boolean if a field has been set.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) HasUpSinceTs() bool {
	if o != nil && !IsNil(o.UpSinceTs) {
		return true
	}

	return false
}

// SetUpSinceTs gets a reference to the given V1AlarmHistoryGet200ResponseHistoryInnerTime and assigns it to the UpSinceTs field.
func (o *V1TroubleshootingDeviceDeviceIdPost200Response) SetUpSinceTs(v V1AlarmHistoryGet200ResponseHistoryInnerTime) {
	o.UpSinceTs = &v
}

func (o V1TroubleshootingDeviceDeviceIdPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1TroubleshootingDeviceDeviceIdPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaintenanceMode) {
		toSerialize["MaintenanceMode"] = o.MaintenanceMode
	}
	if !IsNil(o.ColrActive) {
		toSerialize["colrActive"] = o.ColrActive
	}
	if !IsNil(o.ControlPlane) {
		toSerialize["controlPlane"] = o.ControlPlane
	}
	if !IsNil(o.DataPlane) {
		toSerialize["dataPlane"] = o.DataPlane
	}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	if !IsNil(o.LifecycleStatus) {
		toSerialize["lifecycleStatus"] = o.LifecycleStatus
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SwVersion) {
		toSerialize["swVersion"] = o.SwVersion
	}
	if !IsNil(o.SwVersionV2) {
		toSerialize["swVersionV2"] = o.SwVersionV2
	}
	if !IsNil(o.SystemPlane) {
		toSerialize["systemPlane"] = o.SystemPlane
	}
	if !IsNil(o.UpSinceTs) {
		toSerialize["upSinceTs"] = o.UpSinceTs
	}
	return toSerialize, nil
}

type NullableV1TroubleshootingDeviceDeviceIdPost200Response struct {
	value *V1TroubleshootingDeviceDeviceIdPost200Response
	isSet bool
}

func (v NullableV1TroubleshootingDeviceDeviceIdPost200Response) Get() *V1TroubleshootingDeviceDeviceIdPost200Response {
	return v.value
}

func (v *NullableV1TroubleshootingDeviceDeviceIdPost200Response) Set(val *V1TroubleshootingDeviceDeviceIdPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1TroubleshootingDeviceDeviceIdPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1TroubleshootingDeviceDeviceIdPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1TroubleshootingDeviceDeviceIdPost200Response(val *V1TroubleshootingDeviceDeviceIdPost200Response) *NullableV1TroubleshootingDeviceDeviceIdPost200Response {
	return &NullableV1TroubleshootingDeviceDeviceIdPost200Response{value: val, isSet: true}
}

func (v NullableV1TroubleshootingDeviceDeviceIdPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1TroubleshootingDeviceDeviceIdPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


