/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalRoutingPoliciesPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalRoutingPoliciesPostResponse{}

// V1GlobalRoutingPoliciesPostResponse struct for V1GlobalRoutingPoliciesPostResponse
type V1GlobalRoutingPoliciesPostResponse struct {
	RoutingPolicies []ManaV2RoutingPolicy `json:"routingPolicies,omitempty"`
}

// NewV1GlobalRoutingPoliciesPostResponse instantiates a new V1GlobalRoutingPoliciesPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalRoutingPoliciesPostResponse() *V1GlobalRoutingPoliciesPostResponse {
	this := V1GlobalRoutingPoliciesPostResponse{}
	return &this
}

// NewV1GlobalRoutingPoliciesPostResponseWithDefaults instantiates a new V1GlobalRoutingPoliciesPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalRoutingPoliciesPostResponseWithDefaults() *V1GlobalRoutingPoliciesPostResponse {
	this := V1GlobalRoutingPoliciesPostResponse{}
	return &this
}

// GetRoutingPolicies returns the RoutingPolicies field value if set, zero value otherwise.
func (o *V1GlobalRoutingPoliciesPostResponse) GetRoutingPolicies() []ManaV2RoutingPolicy {
	if o == nil || IsNil(o.RoutingPolicies) {
		var ret []ManaV2RoutingPolicy
		return ret
	}
	return o.RoutingPolicies
}

// GetRoutingPoliciesOk returns a tuple with the RoutingPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalRoutingPoliciesPostResponse) GetRoutingPoliciesOk() ([]ManaV2RoutingPolicy, bool) {
	if o == nil || IsNil(o.RoutingPolicies) {
		return nil, false
	}
	return o.RoutingPolicies, true
}

// HasRoutingPolicies returns a boolean if a field has been set.
func (o *V1GlobalRoutingPoliciesPostResponse) HasRoutingPolicies() bool {
	if o != nil && !IsNil(o.RoutingPolicies) {
		return true
	}

	return false
}

// SetRoutingPolicies gets a reference to the given []ManaV2RoutingPolicy and assigns it to the RoutingPolicies field.
func (o *V1GlobalRoutingPoliciesPostResponse) SetRoutingPolicies(v []ManaV2RoutingPolicy) {
	o.RoutingPolicies = v
}

func (o V1GlobalRoutingPoliciesPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalRoutingPoliciesPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoutingPolicies) {
		toSerialize["routingPolicies"] = o.RoutingPolicies
	}
	return toSerialize, nil
}

type NullableV1GlobalRoutingPoliciesPostResponse struct {
	value *V1GlobalRoutingPoliciesPostResponse
	isSet bool
}

func (v NullableV1GlobalRoutingPoliciesPostResponse) Get() *V1GlobalRoutingPoliciesPostResponse {
	return v.value
}

func (v *NullableV1GlobalRoutingPoliciesPostResponse) Set(val *V1GlobalRoutingPoliciesPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalRoutingPoliciesPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalRoutingPoliciesPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalRoutingPoliciesPostResponse(val *V1GlobalRoutingPoliciesPostResponse) *NullableV1GlobalRoutingPoliciesPostResponse {
	return &NullableV1GlobalRoutingPoliciesPostResponse{value: val, isSet: true}
}

func (v NullableV1GlobalRoutingPoliciesPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalRoutingPoliciesPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


