/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2ExtranetSitesConsumptionOverviewPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ExtranetSitesConsumptionOverviewPost200Response{}

// V2ExtranetSitesConsumptionOverviewPost200Response struct for V2ExtranetSitesConsumptionOverviewPost200Response
type V2ExtranetSitesConsumptionOverviewPost200Response struct {
	LanSegments []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner `json:"lanSegments,omitempty"`
	Regions []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner `json:"regions,omitempty"`
	Sites []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner `json:"sites,omitempty"`
	TotalUsage *float64 `json:"totalUsage,omitempty"`
}

// NewV2ExtranetSitesConsumptionOverviewPost200Response instantiates a new V2ExtranetSitesConsumptionOverviewPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ExtranetSitesConsumptionOverviewPost200Response() *V2ExtranetSitesConsumptionOverviewPost200Response {
	this := V2ExtranetSitesConsumptionOverviewPost200Response{}
	return &this
}

// NewV2ExtranetSitesConsumptionOverviewPost200ResponseWithDefaults instantiates a new V2ExtranetSitesConsumptionOverviewPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ExtranetSitesConsumptionOverviewPost200ResponseWithDefaults() *V2ExtranetSitesConsumptionOverviewPost200Response {
	this := V2ExtranetSitesConsumptionOverviewPost200Response{}
	return &this
}

// GetLanSegments returns the LanSegments field value if set, zero value otherwise.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetLanSegments() []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner {
	if o == nil || IsNil(o.LanSegments) {
		var ret []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner
		return ret
	}
	return o.LanSegments
}

// GetLanSegmentsOk returns a tuple with the LanSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetLanSegmentsOk() ([]V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner, bool) {
	if o == nil || IsNil(o.LanSegments) {
		return nil, false
	}
	return o.LanSegments, true
}

// HasLanSegments returns a boolean if a field has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) HasLanSegments() bool {
	if o != nil && !IsNil(o.LanSegments) {
		return true
	}

	return false
}

// SetLanSegments gets a reference to the given []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner and assigns it to the LanSegments field.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) SetLanSegments(v []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner) {
	o.LanSegments = v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetRegions() []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner {
	if o == nil || IsNil(o.Regions) {
		var ret []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetRegionsOk() ([]V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner and assigns it to the Regions field.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) SetRegions(v []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner) {
	o.Regions = v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetSites() []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner {
	if o == nil || IsNil(o.Sites) {
		var ret []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetSitesOk() ([]V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner and assigns it to the Sites field.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) SetSites(v []V1ExtranetB2bMonitoringPeeringServiceConsumptionOverviewPost200ResponseFirstLevelInner) {
	o.Sites = v
}

// GetTotalUsage returns the TotalUsage field value if set, zero value otherwise.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetTotalUsage() float64 {
	if o == nil || IsNil(o.TotalUsage) {
		var ret float64
		return ret
	}
	return *o.TotalUsage
}

// GetTotalUsageOk returns a tuple with the TotalUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) GetTotalUsageOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalUsage) {
		return nil, false
	}
	return o.TotalUsage, true
}

// HasTotalUsage returns a boolean if a field has been set.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) HasTotalUsage() bool {
	if o != nil && !IsNil(o.TotalUsage) {
		return true
	}

	return false
}

// SetTotalUsage gets a reference to the given float64 and assigns it to the TotalUsage field.
func (o *V2ExtranetSitesConsumptionOverviewPost200Response) SetTotalUsage(v float64) {
	o.TotalUsage = &v
}

func (o V2ExtranetSitesConsumptionOverviewPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ExtranetSitesConsumptionOverviewPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LanSegments) {
		toSerialize["lanSegments"] = o.LanSegments
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	if !IsNil(o.TotalUsage) {
		toSerialize["totalUsage"] = o.TotalUsage
	}
	return toSerialize, nil
}

type NullableV2ExtranetSitesConsumptionOverviewPost200Response struct {
	value *V2ExtranetSitesConsumptionOverviewPost200Response
	isSet bool
}

func (v NullableV2ExtranetSitesConsumptionOverviewPost200Response) Get() *V2ExtranetSitesConsumptionOverviewPost200Response {
	return v.value
}

func (v *NullableV2ExtranetSitesConsumptionOverviewPost200Response) Set(val *V2ExtranetSitesConsumptionOverviewPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ExtranetSitesConsumptionOverviewPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ExtranetSitesConsumptionOverviewPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ExtranetSitesConsumptionOverviewPost200Response(val *V2ExtranetSitesConsumptionOverviewPost200Response) *NullableV2ExtranetSitesConsumptionOverviewPost200Response {
	return &NullableV2ExtranetSitesConsumptionOverviewPost200Response{value: val, isSet: true}
}

func (v NullableV2ExtranetSitesConsumptionOverviewPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ExtranetSitesConsumptionOverviewPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


