/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesSessionStatusPostResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesSessionStatusPostResponseData{}

// V1DevicesSessionStatusPostResponseData struct for V1DevicesSessionStatusPostResponseData
type V1DevicesSessionStatusPostResponseData struct {
	CoreBgpNeighborsCount *int32 `json:"coreBgpNeighborsCount,omitempty"`
	DeviceId *int64 `json:"deviceId,omitempty"`
	OdpBgpNeighborsCount *int32 `json:"odpBgpNeighborsCount,omitempty"`
	WanInterfacesCount *int32 `json:"wanInterfacesCount,omitempty"`
}

// NewV1DevicesSessionStatusPostResponseData instantiates a new V1DevicesSessionStatusPostResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesSessionStatusPostResponseData() *V1DevicesSessionStatusPostResponseData {
	this := V1DevicesSessionStatusPostResponseData{}
	return &this
}

// NewV1DevicesSessionStatusPostResponseDataWithDefaults instantiates a new V1DevicesSessionStatusPostResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesSessionStatusPostResponseDataWithDefaults() *V1DevicesSessionStatusPostResponseData {
	this := V1DevicesSessionStatusPostResponseData{}
	return &this
}

// GetCoreBgpNeighborsCount returns the CoreBgpNeighborsCount field value if set, zero value otherwise.
func (o *V1DevicesSessionStatusPostResponseData) GetCoreBgpNeighborsCount() int32 {
	if o == nil || IsNil(o.CoreBgpNeighborsCount) {
		var ret int32
		return ret
	}
	return *o.CoreBgpNeighborsCount
}

// GetCoreBgpNeighborsCountOk returns a tuple with the CoreBgpNeighborsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesSessionStatusPostResponseData) GetCoreBgpNeighborsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CoreBgpNeighborsCount) {
		return nil, false
	}
	return o.CoreBgpNeighborsCount, true
}

// HasCoreBgpNeighborsCount returns a boolean if a field has been set.
func (o *V1DevicesSessionStatusPostResponseData) HasCoreBgpNeighborsCount() bool {
	if o != nil && !IsNil(o.CoreBgpNeighborsCount) {
		return true
	}

	return false
}

// SetCoreBgpNeighborsCount gets a reference to the given int32 and assigns it to the CoreBgpNeighborsCount field.
func (o *V1DevicesSessionStatusPostResponseData) SetCoreBgpNeighborsCount(v int32) {
	o.CoreBgpNeighborsCount = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *V1DevicesSessionStatusPostResponseData) GetDeviceId() int64 {
	if o == nil || IsNil(o.DeviceId) {
		var ret int64
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesSessionStatusPostResponseData) GetDeviceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *V1DevicesSessionStatusPostResponseData) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given int64 and assigns it to the DeviceId field.
func (o *V1DevicesSessionStatusPostResponseData) SetDeviceId(v int64) {
	o.DeviceId = &v
}

// GetOdpBgpNeighborsCount returns the OdpBgpNeighborsCount field value if set, zero value otherwise.
func (o *V1DevicesSessionStatusPostResponseData) GetOdpBgpNeighborsCount() int32 {
	if o == nil || IsNil(o.OdpBgpNeighborsCount) {
		var ret int32
		return ret
	}
	return *o.OdpBgpNeighborsCount
}

// GetOdpBgpNeighborsCountOk returns a tuple with the OdpBgpNeighborsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesSessionStatusPostResponseData) GetOdpBgpNeighborsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OdpBgpNeighborsCount) {
		return nil, false
	}
	return o.OdpBgpNeighborsCount, true
}

// HasOdpBgpNeighborsCount returns a boolean if a field has been set.
func (o *V1DevicesSessionStatusPostResponseData) HasOdpBgpNeighborsCount() bool {
	if o != nil && !IsNil(o.OdpBgpNeighborsCount) {
		return true
	}

	return false
}

// SetOdpBgpNeighborsCount gets a reference to the given int32 and assigns it to the OdpBgpNeighborsCount field.
func (o *V1DevicesSessionStatusPostResponseData) SetOdpBgpNeighborsCount(v int32) {
	o.OdpBgpNeighborsCount = &v
}

// GetWanInterfacesCount returns the WanInterfacesCount field value if set, zero value otherwise.
func (o *V1DevicesSessionStatusPostResponseData) GetWanInterfacesCount() int32 {
	if o == nil || IsNil(o.WanInterfacesCount) {
		var ret int32
		return ret
	}
	return *o.WanInterfacesCount
}

// GetWanInterfacesCountOk returns a tuple with the WanInterfacesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesSessionStatusPostResponseData) GetWanInterfacesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WanInterfacesCount) {
		return nil, false
	}
	return o.WanInterfacesCount, true
}

// HasWanInterfacesCount returns a boolean if a field has been set.
func (o *V1DevicesSessionStatusPostResponseData) HasWanInterfacesCount() bool {
	if o != nil && !IsNil(o.WanInterfacesCount) {
		return true
	}

	return false
}

// SetWanInterfacesCount gets a reference to the given int32 and assigns it to the WanInterfacesCount field.
func (o *V1DevicesSessionStatusPostResponseData) SetWanInterfacesCount(v int32) {
	o.WanInterfacesCount = &v
}

func (o V1DevicesSessionStatusPostResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesSessionStatusPostResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CoreBgpNeighborsCount) {
		toSerialize["coreBgpNeighborsCount"] = o.CoreBgpNeighborsCount
	}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.OdpBgpNeighborsCount) {
		toSerialize["odpBgpNeighborsCount"] = o.OdpBgpNeighborsCount
	}
	if !IsNil(o.WanInterfacesCount) {
		toSerialize["wanInterfacesCount"] = o.WanInterfacesCount
	}
	return toSerialize, nil
}

type NullableV1DevicesSessionStatusPostResponseData struct {
	value *V1DevicesSessionStatusPostResponseData
	isSet bool
}

func (v NullableV1DevicesSessionStatusPostResponseData) Get() *V1DevicesSessionStatusPostResponseData {
	return v.value
}

func (v *NullableV1DevicesSessionStatusPostResponseData) Set(val *V1DevicesSessionStatusPostResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesSessionStatusPostResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesSessionStatusPostResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesSessionStatusPostResponseData(val *V1DevicesSessionStatusPostResponseData) *NullableV1DevicesSessionStatusPostResponseData {
	return &NullableV1DevicesSessionStatusPostResponseData{value: val, isSet: true}
}

func (v NullableV1DevicesSessionStatusPostResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesSessionStatusPostResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


