/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableSnmpEngineEndpointsAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableSnmpEngineEndpointsAddress{}

// ManaV2NullableSnmpEngineEndpointsAddress struct for ManaV2NullableSnmpEngineEndpointsAddress
type ManaV2NullableSnmpEngineEndpointsAddress struct {
	Address *string `json:"address,omitempty"`
}

// NewManaV2NullableSnmpEngineEndpointsAddress instantiates a new ManaV2NullableSnmpEngineEndpointsAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableSnmpEngineEndpointsAddress() *ManaV2NullableSnmpEngineEndpointsAddress {
	this := ManaV2NullableSnmpEngineEndpointsAddress{}
	return &this
}

// NewManaV2NullableSnmpEngineEndpointsAddressWithDefaults instantiates a new ManaV2NullableSnmpEngineEndpointsAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableSnmpEngineEndpointsAddressWithDefaults() *ManaV2NullableSnmpEngineEndpointsAddress {
	this := ManaV2NullableSnmpEngineEndpointsAddress{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ManaV2NullableSnmpEngineEndpointsAddress) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableSnmpEngineEndpointsAddress) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ManaV2NullableSnmpEngineEndpointsAddress) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ManaV2NullableSnmpEngineEndpointsAddress) SetAddress(v string) {
	o.Address = &v
}

func (o ManaV2NullableSnmpEngineEndpointsAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableSnmpEngineEndpointsAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableManaV2NullableSnmpEngineEndpointsAddress struct {
	value *ManaV2NullableSnmpEngineEndpointsAddress
	isSet bool
}

func (v NullableManaV2NullableSnmpEngineEndpointsAddress) Get() *ManaV2NullableSnmpEngineEndpointsAddress {
	return v.value
}

func (v *NullableManaV2NullableSnmpEngineEndpointsAddress) Set(val *ManaV2NullableSnmpEngineEndpointsAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableSnmpEngineEndpointsAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableSnmpEngineEndpointsAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableSnmpEngineEndpointsAddress(val *ManaV2NullableSnmpEngineEndpointsAddress) *NullableManaV2NullableSnmpEngineEndpointsAddress {
	return &NullableManaV2NullableSnmpEngineEndpointsAddress{value: val, isSet: true}
}

func (v NullableManaV2NullableSnmpEngineEndpointsAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableSnmpEngineEndpointsAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


