/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the Routingprefix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Routingprefix{}

// Routingprefix struct for Routingprefix
type Routingprefix struct {
	AfiSafiName *string `json:"afiSafiName,omitempty"`
	PrefixRcvd *int32 `json:"prefixRcvd,omitempty"`
	PrefixSent *int32 `json:"prefixSent,omitempty"`
}

// NewRoutingprefix instantiates a new Routingprefix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingprefix() *Routingprefix {
	this := Routingprefix{}
	return &this
}

// NewRoutingprefixWithDefaults instantiates a new Routingprefix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingprefixWithDefaults() *Routingprefix {
	this := Routingprefix{}
	return &this
}

// GetAfiSafiName returns the AfiSafiName field value if set, zero value otherwise.
func (o *Routingprefix) GetAfiSafiName() string {
	if o == nil || IsNil(o.AfiSafiName) {
		var ret string
		return ret
	}
	return *o.AfiSafiName
}

// GetAfiSafiNameOk returns a tuple with the AfiSafiName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Routingprefix) GetAfiSafiNameOk() (*string, bool) {
	if o == nil || IsNil(o.AfiSafiName) {
		return nil, false
	}
	return o.AfiSafiName, true
}

// HasAfiSafiName returns a boolean if a field has been set.
func (o *Routingprefix) HasAfiSafiName() bool {
	if o != nil && !IsNil(o.AfiSafiName) {
		return true
	}

	return false
}

// SetAfiSafiName gets a reference to the given string and assigns it to the AfiSafiName field.
func (o *Routingprefix) SetAfiSafiName(v string) {
	o.AfiSafiName = &v
}

// GetPrefixRcvd returns the PrefixRcvd field value if set, zero value otherwise.
func (o *Routingprefix) GetPrefixRcvd() int32 {
	if o == nil || IsNil(o.PrefixRcvd) {
		var ret int32
		return ret
	}
	return *o.PrefixRcvd
}

// GetPrefixRcvdOk returns a tuple with the PrefixRcvd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Routingprefix) GetPrefixRcvdOk() (*int32, bool) {
	if o == nil || IsNil(o.PrefixRcvd) {
		return nil, false
	}
	return o.PrefixRcvd, true
}

// HasPrefixRcvd returns a boolean if a field has been set.
func (o *Routingprefix) HasPrefixRcvd() bool {
	if o != nil && !IsNil(o.PrefixRcvd) {
		return true
	}

	return false
}

// SetPrefixRcvd gets a reference to the given int32 and assigns it to the PrefixRcvd field.
func (o *Routingprefix) SetPrefixRcvd(v int32) {
	o.PrefixRcvd = &v
}

// GetPrefixSent returns the PrefixSent field value if set, zero value otherwise.
func (o *Routingprefix) GetPrefixSent() int32 {
	if o == nil || IsNil(o.PrefixSent) {
		var ret int32
		return ret
	}
	return *o.PrefixSent
}

// GetPrefixSentOk returns a tuple with the PrefixSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Routingprefix) GetPrefixSentOk() (*int32, bool) {
	if o == nil || IsNil(o.PrefixSent) {
		return nil, false
	}
	return o.PrefixSent, true
}

// HasPrefixSent returns a boolean if a field has been set.
func (o *Routingprefix) HasPrefixSent() bool {
	if o != nil && !IsNil(o.PrefixSent) {
		return true
	}

	return false
}

// SetPrefixSent gets a reference to the given int32 and assigns it to the PrefixSent field.
func (o *Routingprefix) SetPrefixSent(v int32) {
	o.PrefixSent = &v
}

func (o Routingprefix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Routingprefix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AfiSafiName) {
		toSerialize["afiSafiName"] = o.AfiSafiName
	}
	if !IsNil(o.PrefixRcvd) {
		toSerialize["prefixRcvd"] = o.PrefixRcvd
	}
	if !IsNil(o.PrefixSent) {
		toSerialize["prefixSent"] = o.PrefixSent
	}
	return toSerialize, nil
}

type NullableRoutingprefix struct {
	value *Routingprefix
	isSet bool
}

func (v NullableRoutingprefix) Get() *Routingprefix {
	return v.value
}

func (v *NullableRoutingprefix) Set(val *Routingprefix) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingprefix) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingprefix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingprefix(val *Routingprefix) *NullableRoutingprefix {
	return &NullableRoutingprefix{value: val, isSet: true}
}

func (v NullableRoutingprefix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingprefix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


