/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DeviceRoutingBgpNbrStatsGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DeviceRoutingBgpNbrStatsGetRequest{}

// V1DeviceRoutingBgpNbrStatsGetRequest struct for V1DeviceRoutingBgpNbrStatsGetRequest
type V1DeviceRoutingBgpNbrStatsGetRequest struct {
	PageRequest *CommonPageRequest `json:"pageRequest,omitempty"`
}

// NewV1DeviceRoutingBgpNbrStatsGetRequest instantiates a new V1DeviceRoutingBgpNbrStatsGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DeviceRoutingBgpNbrStatsGetRequest() *V1DeviceRoutingBgpNbrStatsGetRequest {
	this := V1DeviceRoutingBgpNbrStatsGetRequest{}
	return &this
}

// NewV1DeviceRoutingBgpNbrStatsGetRequestWithDefaults instantiates a new V1DeviceRoutingBgpNbrStatsGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DeviceRoutingBgpNbrStatsGetRequestWithDefaults() *V1DeviceRoutingBgpNbrStatsGetRequest {
	this := V1DeviceRoutingBgpNbrStatsGetRequest{}
	return &this
}

// GetPageRequest returns the PageRequest field value if set, zero value otherwise.
func (o *V1DeviceRoutingBgpNbrStatsGetRequest) GetPageRequest() CommonPageRequest {
	if o == nil || IsNil(o.PageRequest) {
		var ret CommonPageRequest
		return ret
	}
	return *o.PageRequest
}

// GetPageRequestOk returns a tuple with the PageRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DeviceRoutingBgpNbrStatsGetRequest) GetPageRequestOk() (*CommonPageRequest, bool) {
	if o == nil || IsNil(o.PageRequest) {
		return nil, false
	}
	return o.PageRequest, true
}

// HasPageRequest returns a boolean if a field has been set.
func (o *V1DeviceRoutingBgpNbrStatsGetRequest) HasPageRequest() bool {
	if o != nil && !IsNil(o.PageRequest) {
		return true
	}

	return false
}

// SetPageRequest gets a reference to the given CommonPageRequest and assigns it to the PageRequest field.
func (o *V1DeviceRoutingBgpNbrStatsGetRequest) SetPageRequest(v CommonPageRequest) {
	o.PageRequest = &v
}

func (o V1DeviceRoutingBgpNbrStatsGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DeviceRoutingBgpNbrStatsGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageRequest) {
		toSerialize["pageRequest"] = o.PageRequest
	}
	return toSerialize, nil
}

type NullableV1DeviceRoutingBgpNbrStatsGetRequest struct {
	value *V1DeviceRoutingBgpNbrStatsGetRequest
	isSet bool
}

func (v NullableV1DeviceRoutingBgpNbrStatsGetRequest) Get() *V1DeviceRoutingBgpNbrStatsGetRequest {
	return v.value
}

func (v *NullableV1DeviceRoutingBgpNbrStatsGetRequest) Set(val *V1DeviceRoutingBgpNbrStatsGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DeviceRoutingBgpNbrStatsGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DeviceRoutingBgpNbrStatsGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DeviceRoutingBgpNbrStatsGetRequest(val *V1DeviceRoutingBgpNbrStatsGetRequest) *NullableV1DeviceRoutingBgpNbrStatsGetRequest {
	return &NullableV1DeviceRoutingBgpNbrStatsGetRequest{value: val, isSet: true}
}

func (v NullableV1DeviceRoutingBgpNbrStatsGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DeviceRoutingBgpNbrStatsGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


