/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the IpfixAppTopologySelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpfixAppTopologySelector{}

// IpfixAppTopologySelector struct for IpfixAppTopologySelector
type IpfixAppTopologySelector struct {
	// Filter by app ID
	AppId *int32 `json:"appId,omitempty"`
	// Filter by application name
	AppName *string `json:"appName,omitempty"`
	// Filter by SLA class
	SlaClass *string `json:"slaClass,omitempty"`
}

// NewIpfixAppTopologySelector instantiates a new IpfixAppTopologySelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpfixAppTopologySelector() *IpfixAppTopologySelector {
	this := IpfixAppTopologySelector{}
	return &this
}

// NewIpfixAppTopologySelectorWithDefaults instantiates a new IpfixAppTopologySelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpfixAppTopologySelectorWithDefaults() *IpfixAppTopologySelector {
	this := IpfixAppTopologySelector{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *IpfixAppTopologySelector) GetAppId() int32 {
	if o == nil || IsNil(o.AppId) {
		var ret int32
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpfixAppTopologySelector) GetAppIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *IpfixAppTopologySelector) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given int32 and assigns it to the AppId field.
func (o *IpfixAppTopologySelector) SetAppId(v int32) {
	o.AppId = &v
}

// GetAppName returns the AppName field value if set, zero value otherwise.
func (o *IpfixAppTopologySelector) GetAppName() string {
	if o == nil || IsNil(o.AppName) {
		var ret string
		return ret
	}
	return *o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpfixAppTopologySelector) GetAppNameOk() (*string, bool) {
	if o == nil || IsNil(o.AppName) {
		return nil, false
	}
	return o.AppName, true
}

// HasAppName returns a boolean if a field has been set.
func (o *IpfixAppTopologySelector) HasAppName() bool {
	if o != nil && !IsNil(o.AppName) {
		return true
	}

	return false
}

// SetAppName gets a reference to the given string and assigns it to the AppName field.
func (o *IpfixAppTopologySelector) SetAppName(v string) {
	o.AppName = &v
}

// GetSlaClass returns the SlaClass field value if set, zero value otherwise.
func (o *IpfixAppTopologySelector) GetSlaClass() string {
	if o == nil || IsNil(o.SlaClass) {
		var ret string
		return ret
	}
	return *o.SlaClass
}

// GetSlaClassOk returns a tuple with the SlaClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpfixAppTopologySelector) GetSlaClassOk() (*string, bool) {
	if o == nil || IsNil(o.SlaClass) {
		return nil, false
	}
	return o.SlaClass, true
}

// HasSlaClass returns a boolean if a field has been set.
func (o *IpfixAppTopologySelector) HasSlaClass() bool {
	if o != nil && !IsNil(o.SlaClass) {
		return true
	}

	return false
}

// SetSlaClass gets a reference to the given string and assigns it to the SlaClass field.
func (o *IpfixAppTopologySelector) SetSlaClass(v string) {
	o.SlaClass = &v
}

func (o IpfixAppTopologySelector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpfixAppTopologySelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.AppName) {
		toSerialize["appName"] = o.AppName
	}
	if !IsNil(o.SlaClass) {
		toSerialize["slaClass"] = o.SlaClass
	}
	return toSerialize, nil
}

type NullableIpfixAppTopologySelector struct {
	value *IpfixAppTopologySelector
	isSet bool
}

func (v NullableIpfixAppTopologySelector) Get() *IpfixAppTopologySelector {
	return v.value
}

func (v *NullableIpfixAppTopologySelector) Set(val *IpfixAppTopologySelector) {
	v.value = val
	v.isSet = true
}

func (v NullableIpfixAppTopologySelector) IsSet() bool {
	return v.isSet
}

func (v *NullableIpfixAppTopologySelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpfixAppTopologySelector(val *IpfixAppTopologySelector) *NullableIpfixAppTopologySelector {
	return &NullableIpfixAppTopologySelector{value: val, isSet: true}
}

func (v NullableIpfixAppTopologySelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpfixAppTopologySelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


