/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2TrafficPolicyRulesetConfigNullableRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2TrafficPolicyRulesetConfigNullableRule{}

// ManaV2TrafficPolicyRulesetConfigNullableRule struct for ManaV2TrafficPolicyRulesetConfigNullableRule
type ManaV2TrafficPolicyRulesetConfigNullableRule struct {
	Rule *ManaV2TrafficPolicyRulesetConfigNullableRuleRule `json:"rule,omitempty"`
}

// NewManaV2TrafficPolicyRulesetConfigNullableRule instantiates a new ManaV2TrafficPolicyRulesetConfigNullableRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2TrafficPolicyRulesetConfigNullableRule() *ManaV2TrafficPolicyRulesetConfigNullableRule {
	this := ManaV2TrafficPolicyRulesetConfigNullableRule{}
	return &this
}

// NewManaV2TrafficPolicyRulesetConfigNullableRuleWithDefaults instantiates a new ManaV2TrafficPolicyRulesetConfigNullableRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2TrafficPolicyRulesetConfigNullableRuleWithDefaults() *ManaV2TrafficPolicyRulesetConfigNullableRule {
	this := ManaV2TrafficPolicyRulesetConfigNullableRule{}
	return &this
}

// GetRule returns the Rule field value if set, zero value otherwise.
func (o *ManaV2TrafficPolicyRulesetConfigNullableRule) GetRule() ManaV2TrafficPolicyRulesetConfigNullableRuleRule {
	if o == nil || IsNil(o.Rule) {
		var ret ManaV2TrafficPolicyRulesetConfigNullableRuleRule
		return ret
	}
	return *o.Rule
}

// GetRuleOk returns a tuple with the Rule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2TrafficPolicyRulesetConfigNullableRule) GetRuleOk() (*ManaV2TrafficPolicyRulesetConfigNullableRuleRule, bool) {
	if o == nil || IsNil(o.Rule) {
		return nil, false
	}
	return o.Rule, true
}

// HasRule returns a boolean if a field has been set.
func (o *ManaV2TrafficPolicyRulesetConfigNullableRule) HasRule() bool {
	if o != nil && !IsNil(o.Rule) {
		return true
	}

	return false
}

// SetRule gets a reference to the given ManaV2TrafficPolicyRulesetConfigNullableRuleRule and assigns it to the Rule field.
func (o *ManaV2TrafficPolicyRulesetConfigNullableRule) SetRule(v ManaV2TrafficPolicyRulesetConfigNullableRuleRule) {
	o.Rule = &v
}

func (o ManaV2TrafficPolicyRulesetConfigNullableRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2TrafficPolicyRulesetConfigNullableRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rule) {
		toSerialize["rule"] = o.Rule
	}
	return toSerialize, nil
}

type NullableManaV2TrafficPolicyRulesetConfigNullableRule struct {
	value *ManaV2TrafficPolicyRulesetConfigNullableRule
	isSet bool
}

func (v NullableManaV2TrafficPolicyRulesetConfigNullableRule) Get() *ManaV2TrafficPolicyRulesetConfigNullableRule {
	return v.value
}

func (v *NullableManaV2TrafficPolicyRulesetConfigNullableRule) Set(val *ManaV2TrafficPolicyRulesetConfigNullableRule) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2TrafficPolicyRulesetConfigNullableRule) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2TrafficPolicyRulesetConfigNullableRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2TrafficPolicyRulesetConfigNullableRule(val *ManaV2TrafficPolicyRulesetConfigNullableRule) *NullableManaV2TrafficPolicyRulesetConfigNullableRule {
	return &NullableManaV2TrafficPolicyRulesetConfigNullableRule{value: val, isSet: true}
}

func (v NullableManaV2TrafficPolicyRulesetConfigNullableRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2TrafficPolicyRulesetConfigNullableRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


