/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalLanSegmentsVrfIdDevicesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalLanSegmentsVrfIdDevicesGet200Response{}

// V1GlobalLanSegmentsVrfIdDevicesGet200Response struct for V1GlobalLanSegmentsVrfIdDevicesGet200Response
type V1GlobalLanSegmentsVrfIdDevicesGet200Response struct {
	Entries []V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner `json:"entries,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewV1GlobalLanSegmentsVrfIdDevicesGet200Response instantiates a new V1GlobalLanSegmentsVrfIdDevicesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalLanSegmentsVrfIdDevicesGet200Response() *V1GlobalLanSegmentsVrfIdDevicesGet200Response {
	this := V1GlobalLanSegmentsVrfIdDevicesGet200Response{}
	return &this
}

// NewV1GlobalLanSegmentsVrfIdDevicesGet200ResponseWithDefaults instantiates a new V1GlobalLanSegmentsVrfIdDevicesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalLanSegmentsVrfIdDevicesGet200ResponseWithDefaults() *V1GlobalLanSegmentsVrfIdDevicesGet200Response {
	this := V1GlobalLanSegmentsVrfIdDevicesGet200Response{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) GetEntries() []V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner {
	if o == nil || IsNil(o.Entries) {
		var ret []V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) GetEntriesOk() ([]V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner and assigns it to the Entries field.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) SetEntries(v []V1GlobalLanSegmentsVrfIdDevicesGet200ResponseEntriesInner) {
	o.Entries = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1GlobalLanSegmentsVrfIdDevicesGet200Response) SetStatus(v string) {
	o.Status = &v
}

func (o V1GlobalLanSegmentsVrfIdDevicesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalLanSegmentsVrfIdDevicesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response struct {
	value *V1GlobalLanSegmentsVrfIdDevicesGet200Response
	isSet bool
}

func (v NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) Get() *V1GlobalLanSegmentsVrfIdDevicesGet200Response {
	return v.value
}

func (v *NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) Set(val *V1GlobalLanSegmentsVrfIdDevicesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalLanSegmentsVrfIdDevicesGet200Response(val *V1GlobalLanSegmentsVrfIdDevicesGet200Response) *NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response {
	return &NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response{value: val, isSet: true}
}

func (v NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalLanSegmentsVrfIdDevicesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


