/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceTopologyRegionSummaryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceTopologyRegionSummaryPostRequest{}

// V2AssuranceTopologyRegionSummaryPostRequest struct for V2AssuranceTopologyRegionSummaryPostRequest
type V2AssuranceTopologyRegionSummaryPostRequest struct {
	RegionId *int32 `json:"regionId,omitempty"`
}

// NewV2AssuranceTopologyRegionSummaryPostRequest instantiates a new V2AssuranceTopologyRegionSummaryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceTopologyRegionSummaryPostRequest() *V2AssuranceTopologyRegionSummaryPostRequest {
	this := V2AssuranceTopologyRegionSummaryPostRequest{}
	return &this
}

// NewV2AssuranceTopologyRegionSummaryPostRequestWithDefaults instantiates a new V2AssuranceTopologyRegionSummaryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceTopologyRegionSummaryPostRequestWithDefaults() *V2AssuranceTopologyRegionSummaryPostRequest {
	this := V2AssuranceTopologyRegionSummaryPostRequest{}
	return &this
}

// GetRegionId returns the RegionId field value if set, zero value otherwise.
func (o *V2AssuranceTopologyRegionSummaryPostRequest) GetRegionId() int32 {
	if o == nil || IsNil(o.RegionId) {
		var ret int32
		return ret
	}
	return *o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyRegionSummaryPostRequest) GetRegionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegionId) {
		return nil, false
	}
	return o.RegionId, true
}

// HasRegionId returns a boolean if a field has been set.
func (o *V2AssuranceTopologyRegionSummaryPostRequest) HasRegionId() bool {
	if o != nil && !IsNil(o.RegionId) {
		return true
	}

	return false
}

// SetRegionId gets a reference to the given int32 and assigns it to the RegionId field.
func (o *V2AssuranceTopologyRegionSummaryPostRequest) SetRegionId(v int32) {
	o.RegionId = &v
}

func (o V2AssuranceTopologyRegionSummaryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceTopologyRegionSummaryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RegionId) {
		toSerialize["regionId"] = o.RegionId
	}
	return toSerialize, nil
}

type NullableV2AssuranceTopologyRegionSummaryPostRequest struct {
	value *V2AssuranceTopologyRegionSummaryPostRequest
	isSet bool
}

func (v NullableV2AssuranceTopologyRegionSummaryPostRequest) Get() *V2AssuranceTopologyRegionSummaryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceTopologyRegionSummaryPostRequest) Set(val *V2AssuranceTopologyRegionSummaryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceTopologyRegionSummaryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceTopologyRegionSummaryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceTopologyRegionSummaryPostRequest(val *V2AssuranceTopologyRegionSummaryPostRequest) *NullableV2AssuranceTopologyRegionSummaryPostRequest {
	return &NullableV2AssuranceTopologyRegionSummaryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceTopologyRegionSummaryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceTopologyRegionSummaryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


