/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response{}

// V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response struct for V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response
type V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response struct {
	TopConsumers []V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner `json:"topConsumers,omitempty"`
	TotalCustomers *int64 `json:"totalCustomers,omitempty"`
	TotalUsage *float64 `json:"totalUsage,omitempty"`
}

// NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response instantiates a new V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response() *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response {
	this := V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response{}
	return &this
}

// NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseWithDefaults instantiates a new V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseWithDefaults() *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response {
	this := V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response{}
	return &this
}

// GetTopConsumers returns the TopConsumers field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTopConsumers() []V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner {
	if o == nil || IsNil(o.TopConsumers) {
		var ret []V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner
		return ret
	}
	return o.TopConsumers
}

// GetTopConsumersOk returns a tuple with the TopConsumers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTopConsumersOk() ([]V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner, bool) {
	if o == nil || IsNil(o.TopConsumers) {
		return nil, false
	}
	return o.TopConsumers, true
}

// HasTopConsumers returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) HasTopConsumers() bool {
	if o != nil && !IsNil(o.TopConsumers) {
		return true
	}

	return false
}

// SetTopConsumers gets a reference to the given []V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner and assigns it to the TopConsumers field.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) SetTopConsumers(v []V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200ResponseTopConsumersInner) {
	o.TopConsumers = v
}

// GetTotalCustomers returns the TotalCustomers field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTotalCustomers() int64 {
	if o == nil || IsNil(o.TotalCustomers) {
		var ret int64
		return ret
	}
	return *o.TotalCustomers
}

// GetTotalCustomersOk returns a tuple with the TotalCustomers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTotalCustomersOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCustomers) {
		return nil, false
	}
	return o.TotalCustomers, true
}

// HasTotalCustomers returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) HasTotalCustomers() bool {
	if o != nil && !IsNil(o.TotalCustomers) {
		return true
	}

	return false
}

// SetTotalCustomers gets a reference to the given int64 and assigns it to the TotalCustomers field.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) SetTotalCustomers(v int64) {
	o.TotalCustomers = &v
}

// GetTotalUsage returns the TotalUsage field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTotalUsage() float64 {
	if o == nil || IsNil(o.TotalUsage) {
		var ret float64
		return ret
	}
	return *o.TotalUsage
}

// GetTotalUsageOk returns a tuple with the TotalUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) GetTotalUsageOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalUsage) {
		return nil, false
	}
	return o.TotalUsage, true
}

// HasTotalUsage returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) HasTotalUsage() bool {
	if o != nil && !IsNil(o.TotalUsage) {
		return true
	}

	return false
}

// SetTotalUsage gets a reference to the given float64 and assigns it to the TotalUsage field.
func (o *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) SetTotalUsage(v float64) {
	o.TotalUsage = &v
}

func (o V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TopConsumers) {
		toSerialize["topConsumers"] = o.TopConsumers
	}
	if !IsNil(o.TotalCustomers) {
		toSerialize["totalCustomers"] = o.TotalCustomers
	}
	if !IsNil(o.TotalUsage) {
		toSerialize["totalUsage"] = o.TotalUsage
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response struct {
	value *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response
	isSet bool
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) Get() *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response {
	return v.value
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) Set(val *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response(val *V1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response {
	return &NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceConsumersUsageTopPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


