/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1TroubleshootingEnterprisePostRequestDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1TroubleshootingEnterprisePostRequestDimensions{}

// V1TroubleshootingEnterprisePostRequestDimensions struct for V1TroubleshootingEnterprisePostRequestDimensions
type V1TroubleshootingEnterprisePostRequestDimensions struct {
	CertificateExpiry *bool `json:"certificateExpiry,omitempty"`
	CoreConnectivity *bool `json:"coreConnectivity,omitempty"`
	CoreTransitions *bool `json:"coreTransitions,omitempty"`
	Cpu *bool `json:"cpu,omitempty"`
	Crashes *bool `json:"crashes,omitempty"`
	CreditExpiry *bool `json:"creditExpiry,omitempty"`
	Disk *bool `json:"disk,omitempty"`
	FanSpeed *bool `json:"fanSpeed,omitempty"`
	LicenseExpiry *bool `json:"licenseExpiry,omitempty"`
	Memory *bool `json:"memory,omitempty"`
	OdpConnectivity *bool `json:"odpConnectivity,omitempty"`
	OdpTransitions *bool `json:"odpTransitions,omitempty"`
	SlaPerformance *bool `json:"slaPerformance,omitempty"`
	T2Connectivity *bool `json:"t2Connectivity,omitempty"`
	T2Transitions *bool `json:"t2Transitions,omitempty"`
	Temperature *bool `json:"temperature,omitempty"`
}

// NewV1TroubleshootingEnterprisePostRequestDimensions instantiates a new V1TroubleshootingEnterprisePostRequestDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1TroubleshootingEnterprisePostRequestDimensions() *V1TroubleshootingEnterprisePostRequestDimensions {
	this := V1TroubleshootingEnterprisePostRequestDimensions{}
	return &this
}

// NewV1TroubleshootingEnterprisePostRequestDimensionsWithDefaults instantiates a new V1TroubleshootingEnterprisePostRequestDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1TroubleshootingEnterprisePostRequestDimensionsWithDefaults() *V1TroubleshootingEnterprisePostRequestDimensions {
	this := V1TroubleshootingEnterprisePostRequestDimensions{}
	return &this
}

// GetCertificateExpiry returns the CertificateExpiry field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCertificateExpiry() bool {
	if o == nil || IsNil(o.CertificateExpiry) {
		var ret bool
		return ret
	}
	return *o.CertificateExpiry
}

// GetCertificateExpiryOk returns a tuple with the CertificateExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCertificateExpiryOk() (*bool, bool) {
	if o == nil || IsNil(o.CertificateExpiry) {
		return nil, false
	}
	return o.CertificateExpiry, true
}

// HasCertificateExpiry returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCertificateExpiry() bool {
	if o != nil && !IsNil(o.CertificateExpiry) {
		return true
	}

	return false
}

// SetCertificateExpiry gets a reference to the given bool and assigns it to the CertificateExpiry field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCertificateExpiry(v bool) {
	o.CertificateExpiry = &v
}

// GetCoreConnectivity returns the CoreConnectivity field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCoreConnectivity() bool {
	if o == nil || IsNil(o.CoreConnectivity) {
		var ret bool
		return ret
	}
	return *o.CoreConnectivity
}

// GetCoreConnectivityOk returns a tuple with the CoreConnectivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCoreConnectivityOk() (*bool, bool) {
	if o == nil || IsNil(o.CoreConnectivity) {
		return nil, false
	}
	return o.CoreConnectivity, true
}

// HasCoreConnectivity returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCoreConnectivity() bool {
	if o != nil && !IsNil(o.CoreConnectivity) {
		return true
	}

	return false
}

// SetCoreConnectivity gets a reference to the given bool and assigns it to the CoreConnectivity field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCoreConnectivity(v bool) {
	o.CoreConnectivity = &v
}

// GetCoreTransitions returns the CoreTransitions field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCoreTransitions() bool {
	if o == nil || IsNil(o.CoreTransitions) {
		var ret bool
		return ret
	}
	return *o.CoreTransitions
}

// GetCoreTransitionsOk returns a tuple with the CoreTransitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCoreTransitionsOk() (*bool, bool) {
	if o == nil || IsNil(o.CoreTransitions) {
		return nil, false
	}
	return o.CoreTransitions, true
}

// HasCoreTransitions returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCoreTransitions() bool {
	if o != nil && !IsNil(o.CoreTransitions) {
		return true
	}

	return false
}

// SetCoreTransitions gets a reference to the given bool and assigns it to the CoreTransitions field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCoreTransitions(v bool) {
	o.CoreTransitions = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCpu() bool {
	if o == nil || IsNil(o.Cpu) {
		var ret bool
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCpuOk() (*bool, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given bool and assigns it to the Cpu field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCpu(v bool) {
	o.Cpu = &v
}

// GetCrashes returns the Crashes field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCrashes() bool {
	if o == nil || IsNil(o.Crashes) {
		var ret bool
		return ret
	}
	return *o.Crashes
}

// GetCrashesOk returns a tuple with the Crashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCrashesOk() (*bool, bool) {
	if o == nil || IsNil(o.Crashes) {
		return nil, false
	}
	return o.Crashes, true
}

// HasCrashes returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCrashes() bool {
	if o != nil && !IsNil(o.Crashes) {
		return true
	}

	return false
}

// SetCrashes gets a reference to the given bool and assigns it to the Crashes field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCrashes(v bool) {
	o.Crashes = &v
}

// GetCreditExpiry returns the CreditExpiry field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCreditExpiry() bool {
	if o == nil || IsNil(o.CreditExpiry) {
		var ret bool
		return ret
	}
	return *o.CreditExpiry
}

// GetCreditExpiryOk returns a tuple with the CreditExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetCreditExpiryOk() (*bool, bool) {
	if o == nil || IsNil(o.CreditExpiry) {
		return nil, false
	}
	return o.CreditExpiry, true
}

// HasCreditExpiry returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasCreditExpiry() bool {
	if o != nil && !IsNil(o.CreditExpiry) {
		return true
	}

	return false
}

// SetCreditExpiry gets a reference to the given bool and assigns it to the CreditExpiry field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetCreditExpiry(v bool) {
	o.CreditExpiry = &v
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetDisk() bool {
	if o == nil || IsNil(o.Disk) {
		var ret bool
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetDiskOk() (*bool, bool) {
	if o == nil || IsNil(o.Disk) {
		return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasDisk() bool {
	if o != nil && !IsNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given bool and assigns it to the Disk field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetDisk(v bool) {
	o.Disk = &v
}

// GetFanSpeed returns the FanSpeed field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetFanSpeed() bool {
	if o == nil || IsNil(o.FanSpeed) {
		var ret bool
		return ret
	}
	return *o.FanSpeed
}

// GetFanSpeedOk returns a tuple with the FanSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetFanSpeedOk() (*bool, bool) {
	if o == nil || IsNil(o.FanSpeed) {
		return nil, false
	}
	return o.FanSpeed, true
}

// HasFanSpeed returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasFanSpeed() bool {
	if o != nil && !IsNil(o.FanSpeed) {
		return true
	}

	return false
}

// SetFanSpeed gets a reference to the given bool and assigns it to the FanSpeed field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetFanSpeed(v bool) {
	o.FanSpeed = &v
}

// GetLicenseExpiry returns the LicenseExpiry field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetLicenseExpiry() bool {
	if o == nil || IsNil(o.LicenseExpiry) {
		var ret bool
		return ret
	}
	return *o.LicenseExpiry
}

// GetLicenseExpiryOk returns a tuple with the LicenseExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetLicenseExpiryOk() (*bool, bool) {
	if o == nil || IsNil(o.LicenseExpiry) {
		return nil, false
	}
	return o.LicenseExpiry, true
}

// HasLicenseExpiry returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasLicenseExpiry() bool {
	if o != nil && !IsNil(o.LicenseExpiry) {
		return true
	}

	return false
}

// SetLicenseExpiry gets a reference to the given bool and assigns it to the LicenseExpiry field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetLicenseExpiry(v bool) {
	o.LicenseExpiry = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetMemory() bool {
	if o == nil || IsNil(o.Memory) {
		var ret bool
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetMemoryOk() (*bool, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given bool and assigns it to the Memory field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetMemory(v bool) {
	o.Memory = &v
}

// GetOdpConnectivity returns the OdpConnectivity field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetOdpConnectivity() bool {
	if o == nil || IsNil(o.OdpConnectivity) {
		var ret bool
		return ret
	}
	return *o.OdpConnectivity
}

// GetOdpConnectivityOk returns a tuple with the OdpConnectivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetOdpConnectivityOk() (*bool, bool) {
	if o == nil || IsNil(o.OdpConnectivity) {
		return nil, false
	}
	return o.OdpConnectivity, true
}

// HasOdpConnectivity returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasOdpConnectivity() bool {
	if o != nil && !IsNil(o.OdpConnectivity) {
		return true
	}

	return false
}

// SetOdpConnectivity gets a reference to the given bool and assigns it to the OdpConnectivity field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetOdpConnectivity(v bool) {
	o.OdpConnectivity = &v
}

// GetOdpTransitions returns the OdpTransitions field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetOdpTransitions() bool {
	if o == nil || IsNil(o.OdpTransitions) {
		var ret bool
		return ret
	}
	return *o.OdpTransitions
}

// GetOdpTransitionsOk returns a tuple with the OdpTransitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetOdpTransitionsOk() (*bool, bool) {
	if o == nil || IsNil(o.OdpTransitions) {
		return nil, false
	}
	return o.OdpTransitions, true
}

// HasOdpTransitions returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasOdpTransitions() bool {
	if o != nil && !IsNil(o.OdpTransitions) {
		return true
	}

	return false
}

// SetOdpTransitions gets a reference to the given bool and assigns it to the OdpTransitions field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetOdpTransitions(v bool) {
	o.OdpTransitions = &v
}

// GetSlaPerformance returns the SlaPerformance field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetSlaPerformance() bool {
	if o == nil || IsNil(o.SlaPerformance) {
		var ret bool
		return ret
	}
	return *o.SlaPerformance
}

// GetSlaPerformanceOk returns a tuple with the SlaPerformance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetSlaPerformanceOk() (*bool, bool) {
	if o == nil || IsNil(o.SlaPerformance) {
		return nil, false
	}
	return o.SlaPerformance, true
}

// HasSlaPerformance returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasSlaPerformance() bool {
	if o != nil && !IsNil(o.SlaPerformance) {
		return true
	}

	return false
}

// SetSlaPerformance gets a reference to the given bool and assigns it to the SlaPerformance field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetSlaPerformance(v bool) {
	o.SlaPerformance = &v
}

// GetT2Connectivity returns the T2Connectivity field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetT2Connectivity() bool {
	if o == nil || IsNil(o.T2Connectivity) {
		var ret bool
		return ret
	}
	return *o.T2Connectivity
}

// GetT2ConnectivityOk returns a tuple with the T2Connectivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetT2ConnectivityOk() (*bool, bool) {
	if o == nil || IsNil(o.T2Connectivity) {
		return nil, false
	}
	return o.T2Connectivity, true
}

// HasT2Connectivity returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasT2Connectivity() bool {
	if o != nil && !IsNil(o.T2Connectivity) {
		return true
	}

	return false
}

// SetT2Connectivity gets a reference to the given bool and assigns it to the T2Connectivity field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetT2Connectivity(v bool) {
	o.T2Connectivity = &v
}

// GetT2Transitions returns the T2Transitions field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetT2Transitions() bool {
	if o == nil || IsNil(o.T2Transitions) {
		var ret bool
		return ret
	}
	return *o.T2Transitions
}

// GetT2TransitionsOk returns a tuple with the T2Transitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetT2TransitionsOk() (*bool, bool) {
	if o == nil || IsNil(o.T2Transitions) {
		return nil, false
	}
	return o.T2Transitions, true
}

// HasT2Transitions returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasT2Transitions() bool {
	if o != nil && !IsNil(o.T2Transitions) {
		return true
	}

	return false
}

// SetT2Transitions gets a reference to the given bool and assigns it to the T2Transitions field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetT2Transitions(v bool) {
	o.T2Transitions = &v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetTemperature() bool {
	if o == nil || IsNil(o.Temperature) {
		var ret bool
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) GetTemperatureOk() (*bool, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given bool and assigns it to the Temperature field.
func (o *V1TroubleshootingEnterprisePostRequestDimensions) SetTemperature(v bool) {
	o.Temperature = &v
}

func (o V1TroubleshootingEnterprisePostRequestDimensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1TroubleshootingEnterprisePostRequestDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CertificateExpiry) {
		toSerialize["certificateExpiry"] = o.CertificateExpiry
	}
	if !IsNil(o.CoreConnectivity) {
		toSerialize["coreConnectivity"] = o.CoreConnectivity
	}
	if !IsNil(o.CoreTransitions) {
		toSerialize["coreTransitions"] = o.CoreTransitions
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Crashes) {
		toSerialize["crashes"] = o.Crashes
	}
	if !IsNil(o.CreditExpiry) {
		toSerialize["creditExpiry"] = o.CreditExpiry
	}
	if !IsNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}
	if !IsNil(o.FanSpeed) {
		toSerialize["fanSpeed"] = o.FanSpeed
	}
	if !IsNil(o.LicenseExpiry) {
		toSerialize["licenseExpiry"] = o.LicenseExpiry
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.OdpConnectivity) {
		toSerialize["odpConnectivity"] = o.OdpConnectivity
	}
	if !IsNil(o.OdpTransitions) {
		toSerialize["odpTransitions"] = o.OdpTransitions
	}
	if !IsNil(o.SlaPerformance) {
		toSerialize["slaPerformance"] = o.SlaPerformance
	}
	if !IsNil(o.T2Connectivity) {
		toSerialize["t2Connectivity"] = o.T2Connectivity
	}
	if !IsNil(o.T2Transitions) {
		toSerialize["t2Transitions"] = o.T2Transitions
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	return toSerialize, nil
}

type NullableV1TroubleshootingEnterprisePostRequestDimensions struct {
	value *V1TroubleshootingEnterprisePostRequestDimensions
	isSet bool
}

func (v NullableV1TroubleshootingEnterprisePostRequestDimensions) Get() *V1TroubleshootingEnterprisePostRequestDimensions {
	return v.value
}

func (v *NullableV1TroubleshootingEnterprisePostRequestDimensions) Set(val *V1TroubleshootingEnterprisePostRequestDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableV1TroubleshootingEnterprisePostRequestDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableV1TroubleshootingEnterprisePostRequestDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1TroubleshootingEnterprisePostRequestDimensions(val *V1TroubleshootingEnterprisePostRequestDimensions) *NullableV1TroubleshootingEnterprisePostRequestDimensions {
	return &NullableV1TroubleshootingEnterprisePostRequestDimensions{value: val, isSet: true}
}

func (v NullableV1TroubleshootingEnterprisePostRequestDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1TroubleshootingEnterprisePostRequestDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


