/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetsB2bConsumerSummaryGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsB2bConsumerSummaryGetResponse{}

// V1ExtranetsB2bConsumerSummaryGetResponse struct for V1ExtranetsB2bConsumerSummaryGetResponse
type V1ExtranetsB2bConsumerSummaryGetResponse struct {
	Summary []ManaV2B2bExtranetConsumersSummary `json:"summary,omitempty"`
}

// NewV1ExtranetsB2bConsumerSummaryGetResponse instantiates a new V1ExtranetsB2bConsumerSummaryGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsB2bConsumerSummaryGetResponse() *V1ExtranetsB2bConsumerSummaryGetResponse {
	this := V1ExtranetsB2bConsumerSummaryGetResponse{}
	return &this
}

// NewV1ExtranetsB2bConsumerSummaryGetResponseWithDefaults instantiates a new V1ExtranetsB2bConsumerSummaryGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsB2bConsumerSummaryGetResponseWithDefaults() *V1ExtranetsB2bConsumerSummaryGetResponse {
	this := V1ExtranetsB2bConsumerSummaryGetResponse{}
	return &this
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *V1ExtranetsB2bConsumerSummaryGetResponse) GetSummary() []ManaV2B2bExtranetConsumersSummary {
	if o == nil || IsNil(o.Summary) {
		var ret []ManaV2B2bExtranetConsumersSummary
		return ret
	}
	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsB2bConsumerSummaryGetResponse) GetSummaryOk() ([]ManaV2B2bExtranetConsumersSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *V1ExtranetsB2bConsumerSummaryGetResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given []ManaV2B2bExtranetConsumersSummary and assigns it to the Summary field.
func (o *V1ExtranetsB2bConsumerSummaryGetResponse) SetSummary(v []ManaV2B2bExtranetConsumersSummary) {
	o.Summary = v
}

func (o V1ExtranetsB2bConsumerSummaryGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsB2bConsumerSummaryGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableV1ExtranetsB2bConsumerSummaryGetResponse struct {
	value *V1ExtranetsB2bConsumerSummaryGetResponse
	isSet bool
}

func (v NullableV1ExtranetsB2bConsumerSummaryGetResponse) Get() *V1ExtranetsB2bConsumerSummaryGetResponse {
	return v.value
}

func (v *NullableV1ExtranetsB2bConsumerSummaryGetResponse) Set(val *V1ExtranetsB2bConsumerSummaryGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsB2bConsumerSummaryGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsB2bConsumerSummaryGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsB2bConsumerSummaryGetResponse(val *V1ExtranetsB2bConsumerSummaryGetResponse) *NullableV1ExtranetsB2bConsumerSummaryGetResponse {
	return &NullableV1ExtranetsB2bConsumerSummaryGetResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetsB2bConsumerSummaryGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsB2bConsumerSummaryGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


