/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1PolicyRouteTagSetsTagsSummaryGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PolicyRouteTagSetsTagsSummaryGetResponse{}

// V1PolicyRouteTagSetsTagsSummaryGetResponse struct for V1PolicyRouteTagSetsTagsSummaryGetResponse
type V1PolicyRouteTagSetsTagsSummaryGetResponse struct {
	Tags []ManaV2RouteTagSummary `json:"tags,omitempty"`
}

// NewV1PolicyRouteTagSetsTagsSummaryGetResponse instantiates a new V1PolicyRouteTagSetsTagsSummaryGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PolicyRouteTagSetsTagsSummaryGetResponse() *V1PolicyRouteTagSetsTagsSummaryGetResponse {
	this := V1PolicyRouteTagSetsTagsSummaryGetResponse{}
	return &this
}

// NewV1PolicyRouteTagSetsTagsSummaryGetResponseWithDefaults instantiates a new V1PolicyRouteTagSetsTagsSummaryGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PolicyRouteTagSetsTagsSummaryGetResponseWithDefaults() *V1PolicyRouteTagSetsTagsSummaryGetResponse {
	this := V1PolicyRouteTagSetsTagsSummaryGetResponse{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *V1PolicyRouteTagSetsTagsSummaryGetResponse) GetTags() []ManaV2RouteTagSummary {
	if o == nil || IsNil(o.Tags) {
		var ret []ManaV2RouteTagSummary
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PolicyRouteTagSetsTagsSummaryGetResponse) GetTagsOk() ([]ManaV2RouteTagSummary, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *V1PolicyRouteTagSetsTagsSummaryGetResponse) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []ManaV2RouteTagSummary and assigns it to the Tags field.
func (o *V1PolicyRouteTagSetsTagsSummaryGetResponse) SetTags(v []ManaV2RouteTagSummary) {
	o.Tags = v
}

func (o V1PolicyRouteTagSetsTagsSummaryGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PolicyRouteTagSetsTagsSummaryGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableV1PolicyRouteTagSetsTagsSummaryGetResponse struct {
	value *V1PolicyRouteTagSetsTagsSummaryGetResponse
	isSet bool
}

func (v NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) Get() *V1PolicyRouteTagSetsTagsSummaryGetResponse {
	return v.value
}

func (v *NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) Set(val *V1PolicyRouteTagSetsTagsSummaryGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PolicyRouteTagSetsTagsSummaryGetResponse(val *V1PolicyRouteTagSetsTagsSummaryGetResponse) *NullableV1PolicyRouteTagSetsTagsSummaryGetResponse {
	return &NullableV1PolicyRouteTagSetsTagsSummaryGetResponse{value: val, isSet: true}
}

func (v NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PolicyRouteTagSetsTagsSummaryGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


