/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalSiteListsPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalSiteListsPostResponse{}

// V1GlobalSiteListsPostResponse struct for V1GlobalSiteListsPostResponse
type V1GlobalSiteListsPostResponse struct {
	Id *int64 `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewV1GlobalSiteListsPostResponse instantiates a new V1GlobalSiteListsPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalSiteListsPostResponse() *V1GlobalSiteListsPostResponse {
	this := V1GlobalSiteListsPostResponse{}
	return &this
}

// NewV1GlobalSiteListsPostResponseWithDefaults instantiates a new V1GlobalSiteListsPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalSiteListsPostResponseWithDefaults() *V1GlobalSiteListsPostResponse {
	this := V1GlobalSiteListsPostResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1GlobalSiteListsPostResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalSiteListsPostResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1GlobalSiteListsPostResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V1GlobalSiteListsPostResponse) SetId(v int64) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1GlobalSiteListsPostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalSiteListsPostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1GlobalSiteListsPostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1GlobalSiteListsPostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1GlobalSiteListsPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalSiteListsPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1GlobalSiteListsPostResponse struct {
	value *V1GlobalSiteListsPostResponse
	isSet bool
}

func (v NullableV1GlobalSiteListsPostResponse) Get() *V1GlobalSiteListsPostResponse {
	return v.value
}

func (v *NullableV1GlobalSiteListsPostResponse) Set(val *V1GlobalSiteListsPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalSiteListsPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalSiteListsPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalSiteListsPostResponse(val *V1GlobalSiteListsPostResponse) *NullableV1GlobalSiteListsPostResponse {
	return &NullableV1GlobalSiteListsPostResponse{value: val, isSet: true}
}

func (v NullableV1GlobalSiteListsPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalSiteListsPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


