/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2BgpNeighborAddressFamily type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2BgpNeighborAddressFamily{}

// ManaV2BgpNeighborAddressFamily struct for ManaV2BgpNeighborAddressFamily
type ManaV2BgpNeighborAddressFamily struct {
	AddressFamily *string `json:"addressFamily,omitempty"`
	Id *int64 `json:"id,omitempty"`
	InboundPolicy *string `json:"inboundPolicy,omitempty"`
	OutboundPolicy *string `json:"outboundPolicy,omitempty"`
}

// NewManaV2BgpNeighborAddressFamily instantiates a new ManaV2BgpNeighborAddressFamily object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2BgpNeighborAddressFamily() *ManaV2BgpNeighborAddressFamily {
	this := ManaV2BgpNeighborAddressFamily{}
	return &this
}

// NewManaV2BgpNeighborAddressFamilyWithDefaults instantiates a new ManaV2BgpNeighborAddressFamily object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2BgpNeighborAddressFamilyWithDefaults() *ManaV2BgpNeighborAddressFamily {
	this := ManaV2BgpNeighborAddressFamily{}
	return &this
}

// GetAddressFamily returns the AddressFamily field value if set, zero value otherwise.
func (o *ManaV2BgpNeighborAddressFamily) GetAddressFamily() string {
	if o == nil || IsNil(o.AddressFamily) {
		var ret string
		return ret
	}
	return *o.AddressFamily
}

// GetAddressFamilyOk returns a tuple with the AddressFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2BgpNeighborAddressFamily) GetAddressFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.AddressFamily) {
		return nil, false
	}
	return o.AddressFamily, true
}

// HasAddressFamily returns a boolean if a field has been set.
func (o *ManaV2BgpNeighborAddressFamily) HasAddressFamily() bool {
	if o != nil && !IsNil(o.AddressFamily) {
		return true
	}

	return false
}

// SetAddressFamily gets a reference to the given string and assigns it to the AddressFamily field.
func (o *ManaV2BgpNeighborAddressFamily) SetAddressFamily(v string) {
	o.AddressFamily = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManaV2BgpNeighborAddressFamily) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2BgpNeighborAddressFamily) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManaV2BgpNeighborAddressFamily) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ManaV2BgpNeighborAddressFamily) SetId(v int64) {
	o.Id = &v
}

// GetInboundPolicy returns the InboundPolicy field value if set, zero value otherwise.
func (o *ManaV2BgpNeighborAddressFamily) GetInboundPolicy() string {
	if o == nil || IsNil(o.InboundPolicy) {
		var ret string
		return ret
	}
	return *o.InboundPolicy
}

// GetInboundPolicyOk returns a tuple with the InboundPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2BgpNeighborAddressFamily) GetInboundPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.InboundPolicy) {
		return nil, false
	}
	return o.InboundPolicy, true
}

// HasInboundPolicy returns a boolean if a field has been set.
func (o *ManaV2BgpNeighborAddressFamily) HasInboundPolicy() bool {
	if o != nil && !IsNil(o.InboundPolicy) {
		return true
	}

	return false
}

// SetInboundPolicy gets a reference to the given string and assigns it to the InboundPolicy field.
func (o *ManaV2BgpNeighborAddressFamily) SetInboundPolicy(v string) {
	o.InboundPolicy = &v
}

// GetOutboundPolicy returns the OutboundPolicy field value if set, zero value otherwise.
func (o *ManaV2BgpNeighborAddressFamily) GetOutboundPolicy() string {
	if o == nil || IsNil(o.OutboundPolicy) {
		var ret string
		return ret
	}
	return *o.OutboundPolicy
}

// GetOutboundPolicyOk returns a tuple with the OutboundPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2BgpNeighborAddressFamily) GetOutboundPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.OutboundPolicy) {
		return nil, false
	}
	return o.OutboundPolicy, true
}

// HasOutboundPolicy returns a boolean if a field has been set.
func (o *ManaV2BgpNeighborAddressFamily) HasOutboundPolicy() bool {
	if o != nil && !IsNil(o.OutboundPolicy) {
		return true
	}

	return false
}

// SetOutboundPolicy gets a reference to the given string and assigns it to the OutboundPolicy field.
func (o *ManaV2BgpNeighborAddressFamily) SetOutboundPolicy(v string) {
	o.OutboundPolicy = &v
}

func (o ManaV2BgpNeighborAddressFamily) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2BgpNeighborAddressFamily) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressFamily) {
		toSerialize["addressFamily"] = o.AddressFamily
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InboundPolicy) {
		toSerialize["inboundPolicy"] = o.InboundPolicy
	}
	if !IsNil(o.OutboundPolicy) {
		toSerialize["outboundPolicy"] = o.OutboundPolicy
	}
	return toSerialize, nil
}

type NullableManaV2BgpNeighborAddressFamily struct {
	value *ManaV2BgpNeighborAddressFamily
	isSet bool
}

func (v NullableManaV2BgpNeighborAddressFamily) Get() *ManaV2BgpNeighborAddressFamily {
	return v.value
}

func (v *NullableManaV2BgpNeighborAddressFamily) Set(val *ManaV2BgpNeighborAddressFamily) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2BgpNeighborAddressFamily) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2BgpNeighborAddressFamily) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2BgpNeighborAddressFamily(val *ManaV2BgpNeighborAddressFamily) *NullableManaV2BgpNeighborAddressFamily {
	return &NullableManaV2BgpNeighborAddressFamily{value: val, isSet: true}
}

func (v NullableManaV2BgpNeighborAddressFamily) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2BgpNeighborAddressFamily) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


