/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DeviceStatusPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DeviceStatusPostResponse{}

// V1DeviceStatusPostResponse struct for V1DeviceStatusPostResponse
type V1DeviceStatusPostResponse struct {
	Mappings []PokedexDeviceMappingInfo `json:"mappings,omitempty"`
}

// NewV1DeviceStatusPostResponse instantiates a new V1DeviceStatusPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DeviceStatusPostResponse() *V1DeviceStatusPostResponse {
	this := V1DeviceStatusPostResponse{}
	return &this
}

// NewV1DeviceStatusPostResponseWithDefaults instantiates a new V1DeviceStatusPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DeviceStatusPostResponseWithDefaults() *V1DeviceStatusPostResponse {
	this := V1DeviceStatusPostResponse{}
	return &this
}

// GetMappings returns the Mappings field value if set, zero value otherwise.
func (o *V1DeviceStatusPostResponse) GetMappings() []PokedexDeviceMappingInfo {
	if o == nil || IsNil(o.Mappings) {
		var ret []PokedexDeviceMappingInfo
		return ret
	}
	return o.Mappings
}

// GetMappingsOk returns a tuple with the Mappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DeviceStatusPostResponse) GetMappingsOk() ([]PokedexDeviceMappingInfo, bool) {
	if o == nil || IsNil(o.Mappings) {
		return nil, false
	}
	return o.Mappings, true
}

// HasMappings returns a boolean if a field has been set.
func (o *V1DeviceStatusPostResponse) HasMappings() bool {
	if o != nil && !IsNil(o.Mappings) {
		return true
	}

	return false
}

// SetMappings gets a reference to the given []PokedexDeviceMappingInfo and assigns it to the Mappings field.
func (o *V1DeviceStatusPostResponse) SetMappings(v []PokedexDeviceMappingInfo) {
	o.Mappings = v
}

func (o V1DeviceStatusPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DeviceStatusPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mappings) {
		toSerialize["mappings"] = o.Mappings
	}
	return toSerialize, nil
}

type NullableV1DeviceStatusPostResponse struct {
	value *V1DeviceStatusPostResponse
	isSet bool
}

func (v NullableV1DeviceStatusPostResponse) Get() *V1DeviceStatusPostResponse {
	return v.value
}

func (v *NullableV1DeviceStatusPostResponse) Set(val *V1DeviceStatusPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DeviceStatusPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DeviceStatusPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DeviceStatusPostResponse(val *V1DeviceStatusPostResponse) *NullableV1DeviceStatusPostResponse {
	return &NullableV1DeviceStatusPostResponse{value: val, isSet: true}
}

func (v NullableV1DeviceStatusPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DeviceStatusPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


