/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesDeviceIdConnectivityGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesDeviceIdConnectivityGet200Response{}

// V1DevicesDeviceIdConnectivityGet200Response struct for V1DevicesDeviceIdConnectivityGet200Response
type V1DevicesDeviceIdConnectivityGet200Response struct {
	Edges []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner `json:"edges,omitempty"`
	Nodes []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner `json:"nodes,omitempty"`
}

// NewV1DevicesDeviceIdConnectivityGet200Response instantiates a new V1DevicesDeviceIdConnectivityGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesDeviceIdConnectivityGet200Response() *V1DevicesDeviceIdConnectivityGet200Response {
	this := V1DevicesDeviceIdConnectivityGet200Response{}
	return &this
}

// NewV1DevicesDeviceIdConnectivityGet200ResponseWithDefaults instantiates a new V1DevicesDeviceIdConnectivityGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesDeviceIdConnectivityGet200ResponseWithDefaults() *V1DevicesDeviceIdConnectivityGet200Response {
	this := V1DevicesDeviceIdConnectivityGet200Response{}
	return &this
}

// GetEdges returns the Edges field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdConnectivityGet200Response) GetEdges() []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner {
	if o == nil || IsNil(o.Edges) {
		var ret []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner
		return ret
	}
	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdConnectivityGet200Response) GetEdgesOk() ([]V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner, bool) {
	if o == nil || IsNil(o.Edges) {
		return nil, false
	}
	return o.Edges, true
}

// HasEdges returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdConnectivityGet200Response) HasEdges() bool {
	if o != nil && !IsNil(o.Edges) {
		return true
	}

	return false
}

// SetEdges gets a reference to the given []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner and assigns it to the Edges field.
func (o *V1DevicesDeviceIdConnectivityGet200Response) SetEdges(v []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInner) {
	o.Edges = v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdConnectivityGet200Response) GetNodes() []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner {
	if o == nil || IsNil(o.Nodes) {
		var ret []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdConnectivityGet200Response) GetNodesOk() ([]V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdConnectivityGet200Response) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner and assigns it to the Nodes field.
func (o *V1DevicesDeviceIdConnectivityGet200Response) SetNodes(v []V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaNodesAddedInner) {
	o.Nodes = v
}

func (o V1DevicesDeviceIdConnectivityGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesDeviceIdConnectivityGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Edges) {
		toSerialize["edges"] = o.Edges
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	return toSerialize, nil
}

type NullableV1DevicesDeviceIdConnectivityGet200Response struct {
	value *V1DevicesDeviceIdConnectivityGet200Response
	isSet bool
}

func (v NullableV1DevicesDeviceIdConnectivityGet200Response) Get() *V1DevicesDeviceIdConnectivityGet200Response {
	return v.value
}

func (v *NullableV1DevicesDeviceIdConnectivityGet200Response) Set(val *V1DevicesDeviceIdConnectivityGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesDeviceIdConnectivityGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesDeviceIdConnectivityGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesDeviceIdConnectivityGet200Response(val *V1DevicesDeviceIdConnectivityGet200Response) *NullableV1DevicesDeviceIdConnectivityGet200Response {
	return &NullableV1DevicesDeviceIdConnectivityGet200Response{value: val, isSet: true}
}

func (v NullableV1DevicesDeviceIdConnectivityGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesDeviceIdConnectivityGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


