/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner{}

// V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner struct for V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner
type V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner struct {
	Device *V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner `json:"device,omitempty"`
	SecurityPolicyRule *V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner `json:"securityPolicyRule,omitempty"`
	VrfName *string `json:"vrfName,omitempty"`
}

// NewV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner instantiates a new V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner() *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner {
	this := V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner{}
	return &this
}

// NewV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInnerWithDefaults instantiates a new V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInnerWithDefaults() *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner {
	this := V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetDevice() V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner {
	if o == nil || IsNil(o.Device) {
		var ret V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetDeviceOk() (*V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner and assigns it to the Device field.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) SetDevice(v V1ExtranetsGet200ResponsePoliciesInnerBranchesExcludedDevicesInnerSiteDevicesInner) {
	o.Device = &v
}

// GetSecurityPolicyRule returns the SecurityPolicyRule field value if set, zero value otherwise.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetSecurityPolicyRule() V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner {
	if o == nil || IsNil(o.SecurityPolicyRule) {
		var ret V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner
		return ret
	}
	return *o.SecurityPolicyRule
}

// GetSecurityPolicyRuleOk returns a tuple with the SecurityPolicyRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetSecurityPolicyRuleOk() (*V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner, bool) {
	if o == nil || IsNil(o.SecurityPolicyRule) {
		return nil, false
	}
	return o.SecurityPolicyRule, true
}

// HasSecurityPolicyRule returns a boolean if a field has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) HasSecurityPolicyRule() bool {
	if o != nil && !IsNil(o.SecurityPolicyRule) {
		return true
	}

	return false
}

// SetSecurityPolicyRule gets a reference to the given V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner and assigns it to the SecurityPolicyRule field.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) SetSecurityPolicyRule(v V1ExtranetsB2bConsumerPost200ResponsePolicyInnerInboundSecurityRulesInner) {
	o.SecurityPolicyRule = &v
}

// GetVrfName returns the VrfName field value if set, zero value otherwise.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetVrfName() string {
	if o == nil || IsNil(o.VrfName) {
		var ret string
		return ret
	}
	return *o.VrfName
}

// GetVrfNameOk returns a tuple with the VrfName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) GetVrfNameOk() (*string, bool) {
	if o == nil || IsNil(o.VrfName) {
		return nil, false
	}
	return o.VrfName, true
}

// HasVrfName returns a boolean if a field has been set.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) HasVrfName() bool {
	if o != nil && !IsNil(o.VrfName) {
		return true
	}

	return false
}

// SetVrfName gets a reference to the given string and assigns it to the VrfName field.
func (o *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) SetVrfName(v string) {
	o.VrfName = &v
}

func (o V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.SecurityPolicyRule) {
		toSerialize["securityPolicyRule"] = o.SecurityPolicyRule
	}
	if !IsNil(o.VrfName) {
		toSerialize["vrfName"] = o.VrfName
	}
	return toSerialize, nil
}

type NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner struct {
	value *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner
	isSet bool
}

func (v NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) Get() *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner {
	return v.value
}

func (v *NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) Set(val *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner(val *V1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) *NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner {
	return &NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner{value: val, isSet: true}
}

func (v NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetsMonitoringTrafficSecurityPolicyPost200ResponseSecurityRulesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


