/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner{}

// V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner struct for V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner
type V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner struct {
	CustomerName *string `json:"customerName,omitempty"`
	CustomerPrefixHealth *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth `json:"customerPrefixHealth,omitempty"`
	OverallHealth *string `json:"overallHealth,omitempty"`
	ProducerPrefixHealth *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth `json:"producerPrefixHealth,omitempty"`
}

// NewV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner instantiates a new V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner() *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner {
	this := V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner{}
	return &this
}

// NewV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerWithDefaults instantiates a new V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerWithDefaults() *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner {
	this := V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner{}
	return &this
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetCustomerPrefixHealth returns the CustomerPrefixHealth field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetCustomerPrefixHealth() V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth {
	if o == nil || IsNil(o.CustomerPrefixHealth) {
		var ret V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth
		return ret
	}
	return *o.CustomerPrefixHealth
}

// GetCustomerPrefixHealthOk returns a tuple with the CustomerPrefixHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetCustomerPrefixHealthOk() (*V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth, bool) {
	if o == nil || IsNil(o.CustomerPrefixHealth) {
		return nil, false
	}
	return o.CustomerPrefixHealth, true
}

// HasCustomerPrefixHealth returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) HasCustomerPrefixHealth() bool {
	if o != nil && !IsNil(o.CustomerPrefixHealth) {
		return true
	}

	return false
}

// SetCustomerPrefixHealth gets a reference to the given V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth and assigns it to the CustomerPrefixHealth field.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) SetCustomerPrefixHealth(v V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth) {
	o.CustomerPrefixHealth = &v
}

// GetOverallHealth returns the OverallHealth field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetOverallHealth() string {
	if o == nil || IsNil(o.OverallHealth) {
		var ret string
		return ret
	}
	return *o.OverallHealth
}

// GetOverallHealthOk returns a tuple with the OverallHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetOverallHealthOk() (*string, bool) {
	if o == nil || IsNil(o.OverallHealth) {
		return nil, false
	}
	return o.OverallHealth, true
}

// HasOverallHealth returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) HasOverallHealth() bool {
	if o != nil && !IsNil(o.OverallHealth) {
		return true
	}

	return false
}

// SetOverallHealth gets a reference to the given string and assigns it to the OverallHealth field.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) SetOverallHealth(v string) {
	o.OverallHealth = &v
}

// GetProducerPrefixHealth returns the ProducerPrefixHealth field value if set, zero value otherwise.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetProducerPrefixHealth() V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth {
	if o == nil || IsNil(o.ProducerPrefixHealth) {
		var ret V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth
		return ret
	}
	return *o.ProducerPrefixHealth
}

// GetProducerPrefixHealthOk returns a tuple with the ProducerPrefixHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) GetProducerPrefixHealthOk() (*V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth, bool) {
	if o == nil || IsNil(o.ProducerPrefixHealth) {
		return nil, false
	}
	return o.ProducerPrefixHealth, true
}

// HasProducerPrefixHealth returns a boolean if a field has been set.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) HasProducerPrefixHealth() bool {
	if o != nil && !IsNil(o.ProducerPrefixHealth) {
		return true
	}

	return false
}

// SetProducerPrefixHealth gets a reference to the given V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth and assigns it to the ProducerPrefixHealth field.
func (o *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) SetProducerPrefixHealth(v V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInnerCustomerPrefixHealth) {
	o.ProducerPrefixHealth = &v
}

func (o V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.CustomerPrefixHealth) {
		toSerialize["customerPrefixHealth"] = o.CustomerPrefixHealth
	}
	if !IsNil(o.OverallHealth) {
		toSerialize["overallHealth"] = o.OverallHealth
	}
	if !IsNil(o.ProducerPrefixHealth) {
		toSerialize["producerPrefixHealth"] = o.ProducerPrefixHealth
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner struct {
	value *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner
	isSet bool
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) Get() *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner {
	return v.value
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) Set(val *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner(val *V1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) *NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner {
	return &NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMonitoringPeeringServiceServiceHealthPost200ResponseServiceHealthInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


