/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2OspfRedistributeProtocolConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2OspfRedistributeProtocolConfig{}

// ManaV2OspfRedistributeProtocolConfig struct for ManaV2OspfRedistributeProtocolConfig
type ManaV2OspfRedistributeProtocolConfig struct {
	Metric *int32 `json:"metric,omitempty"`
	MetricType *string `json:"metricType,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewManaV2OspfRedistributeProtocolConfig instantiates a new ManaV2OspfRedistributeProtocolConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2OspfRedistributeProtocolConfig() *ManaV2OspfRedistributeProtocolConfig {
	this := ManaV2OspfRedistributeProtocolConfig{}
	return &this
}

// NewManaV2OspfRedistributeProtocolConfigWithDefaults instantiates a new ManaV2OspfRedistributeProtocolConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2OspfRedistributeProtocolConfigWithDefaults() *ManaV2OspfRedistributeProtocolConfig {
	this := ManaV2OspfRedistributeProtocolConfig{}
	return &this
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *ManaV2OspfRedistributeProtocolConfig) GetMetric() int32 {
	if o == nil || IsNil(o.Metric) {
		var ret int32
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) GetMetricOk() (*int32, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given int32 and assigns it to the Metric field.
func (o *ManaV2OspfRedistributeProtocolConfig) SetMetric(v int32) {
	o.Metric = &v
}

// GetMetricType returns the MetricType field value if set, zero value otherwise.
func (o *ManaV2OspfRedistributeProtocolConfig) GetMetricType() string {
	if o == nil || IsNil(o.MetricType) {
		var ret string
		return ret
	}
	return *o.MetricType
}

// GetMetricTypeOk returns a tuple with the MetricType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) GetMetricTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MetricType) {
		return nil, false
	}
	return o.MetricType, true
}

// HasMetricType returns a boolean if a field has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) HasMetricType() bool {
	if o != nil && !IsNil(o.MetricType) {
		return true
	}

	return false
}

// SetMetricType gets a reference to the given string and assigns it to the MetricType field.
func (o *ManaV2OspfRedistributeProtocolConfig) SetMetricType(v string) {
	o.MetricType = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ManaV2OspfRedistributeProtocolConfig) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ManaV2OspfRedistributeProtocolConfig) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ManaV2OspfRedistributeProtocolConfig) SetType(v string) {
	o.Type = &v
}

func (o ManaV2OspfRedistributeProtocolConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2OspfRedistributeProtocolConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !IsNil(o.MetricType) {
		toSerialize["metricType"] = o.MetricType
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableManaV2OspfRedistributeProtocolConfig struct {
	value *ManaV2OspfRedistributeProtocolConfig
	isSet bool
}

func (v NullableManaV2OspfRedistributeProtocolConfig) Get() *ManaV2OspfRedistributeProtocolConfig {
	return v.value
}

func (v *NullableManaV2OspfRedistributeProtocolConfig) Set(val *ManaV2OspfRedistributeProtocolConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2OspfRedistributeProtocolConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2OspfRedistributeProtocolConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2OspfRedistributeProtocolConfig(val *ManaV2OspfRedistributeProtocolConfig) *NullableManaV2OspfRedistributeProtocolConfig {
	return &NullableManaV2OspfRedistributeProtocolConfig{value: val, isSet: true}
}

func (v NullableManaV2OspfRedistributeProtocolConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2OspfRedistributeProtocolConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


