/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SyslogmonHistogram type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyslogmonHistogram{}

// SyslogmonHistogram struct for SyslogmonHistogram
type SyslogmonHistogram struct {
	Count *int32 `json:"count,omitempty"`
	Ts *GoogleProtobufTimestamp `json:"ts,omitempty"`
}

// NewSyslogmonHistogram instantiates a new SyslogmonHistogram object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyslogmonHistogram() *SyslogmonHistogram {
	this := SyslogmonHistogram{}
	return &this
}

// NewSyslogmonHistogramWithDefaults instantiates a new SyslogmonHistogram object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyslogmonHistogramWithDefaults() *SyslogmonHistogram {
	this := SyslogmonHistogram{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SyslogmonHistogram) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyslogmonHistogram) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SyslogmonHistogram) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SyslogmonHistogram) SetCount(v int32) {
	o.Count = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *SyslogmonHistogram) GetTs() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.Ts) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyslogmonHistogram) GetTsOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *SyslogmonHistogram) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given GoogleProtobufTimestamp and assigns it to the Ts field.
func (o *SyslogmonHistogram) SetTs(v GoogleProtobufTimestamp) {
	o.Ts = &v
}

func (o SyslogmonHistogram) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyslogmonHistogram) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	return toSerialize, nil
}

type NullableSyslogmonHistogram struct {
	value *SyslogmonHistogram
	isSet bool
}

func (v NullableSyslogmonHistogram) Get() *SyslogmonHistogram {
	return v.value
}

func (v *NullableSyslogmonHistogram) Set(val *SyslogmonHistogram) {
	v.value = val
	v.isSet = true
}

func (v NullableSyslogmonHistogram) IsSet() bool {
	return v.isSet
}

func (v *NullableSyslogmonHistogram) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyslogmonHistogram(val *SyslogmonHistogram) *NullableSyslogmonHistogram {
	return &NullableSyslogmonHistogram{value: val, isSet: true}
}

func (v NullableSyslogmonHistogram) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyslogmonHistogram) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


