/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane{}

// V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane struct for V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane
type V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane struct {
	DownTransitions []V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner `json:"downTransitions,omitempty"`
	SessionSlas []V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner `json:"sessionSlas,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane instantiates a new V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane() *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane {
	this := V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane{}
	return &this
}

// NewV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneWithDefaults instantiates a new V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneWithDefaults() *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane {
	this := V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane{}
	return &this
}

// GetDownTransitions returns the DownTransitions field value if set, zero value otherwise.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetDownTransitions() []V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner {
	if o == nil || IsNil(o.DownTransitions) {
		var ret []V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner
		return ret
	}
	return o.DownTransitions
}

// GetDownTransitionsOk returns a tuple with the DownTransitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetDownTransitionsOk() ([]V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner, bool) {
	if o == nil || IsNil(o.DownTransitions) {
		return nil, false
	}
	return o.DownTransitions, true
}

// HasDownTransitions returns a boolean if a field has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) HasDownTransitions() bool {
	if o != nil && !IsNil(o.DownTransitions) {
		return true
	}

	return false
}

// SetDownTransitions gets a reference to the given []V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner and assigns it to the DownTransitions field.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) SetDownTransitions(v []V1BackboneHealthDeviceDeviceIdPost200ResponseControlPlaneControlTransitionsTransitionsInner) {
	o.DownTransitions = v
}

// GetSessionSlas returns the SessionSlas field value if set, zero value otherwise.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetSessionSlas() []V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner {
	if o == nil || IsNil(o.SessionSlas) {
		var ret []V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner
		return ret
	}
	return o.SessionSlas
}

// GetSessionSlasOk returns a tuple with the SessionSlas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetSessionSlasOk() ([]V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner, bool) {
	if o == nil || IsNil(o.SessionSlas) {
		return nil, false
	}
	return o.SessionSlas, true
}

// HasSessionSlas returns a boolean if a field has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) HasSessionSlas() bool {
	if o != nil && !IsNil(o.SessionSlas) {
		return true
	}

	return false
}

// SetSessionSlas gets a reference to the given []V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner and assigns it to the SessionSlas field.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) SetSessionSlas(v []V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlaneSessionSlasInner) {
	o.SessionSlas = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) SetStatus(v string) {
	o.Status = &v
}

func (o V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownTransitions) {
		toSerialize["downTransitions"] = o.DownTransitions
	}
	if !IsNil(o.SessionSlas) {
		toSerialize["sessionSlas"] = o.SessionSlas
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane struct {
	value *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane
	isSet bool
}

func (v NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) Get() *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane {
	return v.value
}

func (v *NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) Set(val *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) {
	v.value = val
	v.isSet = true
}

func (v NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) IsSet() bool {
	return v.isSet
}

func (v *NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane(val *V1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) *NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane {
	return &NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane{value: val, isSet: true}
}

func (v NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1BackboneHealthDeviceDeviceIdPost200ResponseDataPlane) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


