/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceBucketAppsPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceBucketAppsPost200Response{}

// V2AssuranceBucketAppsPost200Response struct for V2AssuranceBucketAppsPost200Response
type V2AssuranceBucketAppsPost200Response struct {
	Apps []V2AssuranceBucketAppsPost200ResponseAppsInner `json:"apps,omitempty"`
}

// NewV2AssuranceBucketAppsPost200Response instantiates a new V2AssuranceBucketAppsPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceBucketAppsPost200Response() *V2AssuranceBucketAppsPost200Response {
	this := V2AssuranceBucketAppsPost200Response{}
	return &this
}

// NewV2AssuranceBucketAppsPost200ResponseWithDefaults instantiates a new V2AssuranceBucketAppsPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceBucketAppsPost200ResponseWithDefaults() *V2AssuranceBucketAppsPost200Response {
	this := V2AssuranceBucketAppsPost200Response{}
	return &this
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *V2AssuranceBucketAppsPost200Response) GetApps() []V2AssuranceBucketAppsPost200ResponseAppsInner {
	if o == nil || IsNil(o.Apps) {
		var ret []V2AssuranceBucketAppsPost200ResponseAppsInner
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceBucketAppsPost200Response) GetAppsOk() ([]V2AssuranceBucketAppsPost200ResponseAppsInner, bool) {
	if o == nil || IsNil(o.Apps) {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *V2AssuranceBucketAppsPost200Response) HasApps() bool {
	if o != nil && !IsNil(o.Apps) {
		return true
	}

	return false
}

// SetApps gets a reference to the given []V2AssuranceBucketAppsPost200ResponseAppsInner and assigns it to the Apps field.
func (o *V2AssuranceBucketAppsPost200Response) SetApps(v []V2AssuranceBucketAppsPost200ResponseAppsInner) {
	o.Apps = v
}

func (o V2AssuranceBucketAppsPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceBucketAppsPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}
	return toSerialize, nil
}

type NullableV2AssuranceBucketAppsPost200Response struct {
	value *V2AssuranceBucketAppsPost200Response
	isSet bool
}

func (v NullableV2AssuranceBucketAppsPost200Response) Get() *V2AssuranceBucketAppsPost200Response {
	return v.value
}

func (v *NullableV2AssuranceBucketAppsPost200Response) Set(val *V2AssuranceBucketAppsPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceBucketAppsPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceBucketAppsPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceBucketAppsPost200Response(val *V2AssuranceBucketAppsPost200Response) *NullableV2AssuranceBucketAppsPost200Response {
	return &NullableV2AssuranceBucketAppsPost200Response{value: val, isSet: true}
}

func (v NullableV2AssuranceBucketAppsPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceBucketAppsPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


