/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner{}

// V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner struct for V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner
type V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner struct {
	DestIp *string `json:"destIp,omitempty"`
	DestPort *int32 `json:"destPort,omitempty"`
	LastEstablishedTime *V1AlarmHistoryGet200ResponseHistoryInnerTime `json:"lastEstablishedTime,omitempty"`
	Quality *string `json:"quality,omitempty"`
	SourceIp *string `json:"sourceIp,omitempty"`
	SourcePort *int32 `json:"sourcePort,omitempty"`
}

// NewV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner instantiates a new V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner() *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner {
	this := V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner{}
	return &this
}

// NewV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInnerWithDefaults instantiates a new V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInnerWithDefaults() *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner {
	this := V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner{}
	return &this
}

// GetDestIp returns the DestIp field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetDestIp() string {
	if o == nil || IsNil(o.DestIp) {
		var ret string
		return ret
	}
	return *o.DestIp
}

// GetDestIpOk returns a tuple with the DestIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetDestIpOk() (*string, bool) {
	if o == nil || IsNil(o.DestIp) {
		return nil, false
	}
	return o.DestIp, true
}

// HasDestIp returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasDestIp() bool {
	if o != nil && !IsNil(o.DestIp) {
		return true
	}

	return false
}

// SetDestIp gets a reference to the given string and assigns it to the DestIp field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetDestIp(v string) {
	o.DestIp = &v
}

// GetDestPort returns the DestPort field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetDestPort() int32 {
	if o == nil || IsNil(o.DestPort) {
		var ret int32
		return ret
	}
	return *o.DestPort
}

// GetDestPortOk returns a tuple with the DestPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetDestPortOk() (*int32, bool) {
	if o == nil || IsNil(o.DestPort) {
		return nil, false
	}
	return o.DestPort, true
}

// HasDestPort returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasDestPort() bool {
	if o != nil && !IsNil(o.DestPort) {
		return true
	}

	return false
}

// SetDestPort gets a reference to the given int32 and assigns it to the DestPort field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetDestPort(v int32) {
	o.DestPort = &v
}

// GetLastEstablishedTime returns the LastEstablishedTime field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetLastEstablishedTime() V1AlarmHistoryGet200ResponseHistoryInnerTime {
	if o == nil || IsNil(o.LastEstablishedTime) {
		var ret V1AlarmHistoryGet200ResponseHistoryInnerTime
		return ret
	}
	return *o.LastEstablishedTime
}

// GetLastEstablishedTimeOk returns a tuple with the LastEstablishedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetLastEstablishedTimeOk() (*V1AlarmHistoryGet200ResponseHistoryInnerTime, bool) {
	if o == nil || IsNil(o.LastEstablishedTime) {
		return nil, false
	}
	return o.LastEstablishedTime, true
}

// HasLastEstablishedTime returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasLastEstablishedTime() bool {
	if o != nil && !IsNil(o.LastEstablishedTime) {
		return true
	}

	return false
}

// SetLastEstablishedTime gets a reference to the given V1AlarmHistoryGet200ResponseHistoryInnerTime and assigns it to the LastEstablishedTime field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetLastEstablishedTime(v V1AlarmHistoryGet200ResponseHistoryInnerTime) {
	o.LastEstablishedTime = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetQuality() string {
	if o == nil || IsNil(o.Quality) {
		var ret string
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetQualityOk() (*string, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given string and assigns it to the Quality field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetQuality(v string) {
	o.Quality = &v
}

// GetSourceIp returns the SourceIp field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetSourceIp() string {
	if o == nil || IsNil(o.SourceIp) {
		var ret string
		return ret
	}
	return *o.SourceIp
}

// GetSourceIpOk returns a tuple with the SourceIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetSourceIpOk() (*string, bool) {
	if o == nil || IsNil(o.SourceIp) {
		return nil, false
	}
	return o.SourceIp, true
}

// HasSourceIp returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasSourceIp() bool {
	if o != nil && !IsNil(o.SourceIp) {
		return true
	}

	return false
}

// SetSourceIp gets a reference to the given string and assigns it to the SourceIp field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetSourceIp(v string) {
	o.SourceIp = &v
}

// GetSourcePort returns the SourcePort field value if set, zero value otherwise.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetSourcePort() int32 {
	if o == nil || IsNil(o.SourcePort) {
		var ret int32
		return ret
	}
	return *o.SourcePort
}

// GetSourcePortOk returns a tuple with the SourcePort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) GetSourcePortOk() (*int32, bool) {
	if o == nil || IsNil(o.SourcePort) {
		return nil, false
	}
	return o.SourcePort, true
}

// HasSourcePort returns a boolean if a field has been set.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) HasSourcePort() bool {
	if o != nil && !IsNil(o.SourcePort) {
		return true
	}

	return false
}

// SetSourcePort gets a reference to the given int32 and assigns it to the SourcePort field.
func (o *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) SetSourcePort(v int32) {
	o.SourcePort = &v
}

func (o V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DestIp) {
		toSerialize["destIp"] = o.DestIp
	}
	if !IsNil(o.DestPort) {
		toSerialize["destPort"] = o.DestPort
	}
	if !IsNil(o.LastEstablishedTime) {
		toSerialize["lastEstablishedTime"] = o.LastEstablishedTime
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !IsNil(o.SourceIp) {
		toSerialize["sourceIp"] = o.SourceIp
	}
	if !IsNil(o.SourcePort) {
		toSerialize["sourcePort"] = o.SourcePort
	}
	return toSerialize, nil
}

type NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner struct {
	value *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner
	isSet bool
}

func (v NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) Get() *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner {
	return v.value
}

func (v *NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) Set(val *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner(val *V1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) *NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner {
	return &NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner{value: val, isSet: true}
}

func (v NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1FlowsTopologyPost200ResponseNetworkTopologyInnerDeltaEdgesAddedInnerConnectionsControlConnectionInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


