/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssistantAssistantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantAssistantResponse{}

// AssistantAssistantResponse struct for AssistantAssistantResponse
type AssistantAssistantResponse struct {
	ConversationId *string `json:"conversationId,omitempty"`
	DataframeDictionary []AssistantDataframeDictionary `json:"dataframeDictionary,omitempty"`
	OriginalQuestion *AssistantAssistantQuestion `json:"originalQuestion,omitempty"`
	ResponseId *string `json:"responseId,omitempty"`
	ResponseLanguage *string `json:"responseLanguage,omitempty"`
	ResponseText *string `json:"responseText,omitempty"`
	ResponseTimestamp *int64 `json:"responseTimestamp,omitempty"`
	ResponseType *string `json:"responseType,omitempty"`
	VisualizationSummary *string `json:"visualizationSummary,omitempty"`
}

// NewAssistantAssistantResponse instantiates a new AssistantAssistantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantAssistantResponse() *AssistantAssistantResponse {
	this := AssistantAssistantResponse{}
	return &this
}

// NewAssistantAssistantResponseWithDefaults instantiates a new AssistantAssistantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantAssistantResponseWithDefaults() *AssistantAssistantResponse {
	this := AssistantAssistantResponse{}
	return &this
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *AssistantAssistantResponse) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetDataframeDictionary returns the DataframeDictionary field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetDataframeDictionary() []AssistantDataframeDictionary {
	if o == nil || IsNil(o.DataframeDictionary) {
		var ret []AssistantDataframeDictionary
		return ret
	}
	return o.DataframeDictionary
}

// GetDataframeDictionaryOk returns a tuple with the DataframeDictionary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetDataframeDictionaryOk() ([]AssistantDataframeDictionary, bool) {
	if o == nil || IsNil(o.DataframeDictionary) {
		return nil, false
	}
	return o.DataframeDictionary, true
}

// HasDataframeDictionary returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasDataframeDictionary() bool {
	if o != nil && !IsNil(o.DataframeDictionary) {
		return true
	}

	return false
}

// SetDataframeDictionary gets a reference to the given []AssistantDataframeDictionary and assigns it to the DataframeDictionary field.
func (o *AssistantAssistantResponse) SetDataframeDictionary(v []AssistantDataframeDictionary) {
	o.DataframeDictionary = v
}

// GetOriginalQuestion returns the OriginalQuestion field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetOriginalQuestion() AssistantAssistantQuestion {
	if o == nil || IsNil(o.OriginalQuestion) {
		var ret AssistantAssistantQuestion
		return ret
	}
	return *o.OriginalQuestion
}

// GetOriginalQuestionOk returns a tuple with the OriginalQuestion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetOriginalQuestionOk() (*AssistantAssistantQuestion, bool) {
	if o == nil || IsNil(o.OriginalQuestion) {
		return nil, false
	}
	return o.OriginalQuestion, true
}

// HasOriginalQuestion returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasOriginalQuestion() bool {
	if o != nil && !IsNil(o.OriginalQuestion) {
		return true
	}

	return false
}

// SetOriginalQuestion gets a reference to the given AssistantAssistantQuestion and assigns it to the OriginalQuestion field.
func (o *AssistantAssistantResponse) SetOriginalQuestion(v AssistantAssistantQuestion) {
	o.OriginalQuestion = &v
}

// GetResponseId returns the ResponseId field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetResponseId() string {
	if o == nil || IsNil(o.ResponseId) {
		var ret string
		return ret
	}
	return *o.ResponseId
}

// GetResponseIdOk returns a tuple with the ResponseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetResponseIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseId) {
		return nil, false
	}
	return o.ResponseId, true
}

// HasResponseId returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasResponseId() bool {
	if o != nil && !IsNil(o.ResponseId) {
		return true
	}

	return false
}

// SetResponseId gets a reference to the given string and assigns it to the ResponseId field.
func (o *AssistantAssistantResponse) SetResponseId(v string) {
	o.ResponseId = &v
}

// GetResponseLanguage returns the ResponseLanguage field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetResponseLanguage() string {
	if o == nil || IsNil(o.ResponseLanguage) {
		var ret string
		return ret
	}
	return *o.ResponseLanguage
}

// GetResponseLanguageOk returns a tuple with the ResponseLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetResponseLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseLanguage) {
		return nil, false
	}
	return o.ResponseLanguage, true
}

// HasResponseLanguage returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasResponseLanguage() bool {
	if o != nil && !IsNil(o.ResponseLanguage) {
		return true
	}

	return false
}

// SetResponseLanguage gets a reference to the given string and assigns it to the ResponseLanguage field.
func (o *AssistantAssistantResponse) SetResponseLanguage(v string) {
	o.ResponseLanguage = &v
}

// GetResponseText returns the ResponseText field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetResponseText() string {
	if o == nil || IsNil(o.ResponseText) {
		var ret string
		return ret
	}
	return *o.ResponseText
}

// GetResponseTextOk returns a tuple with the ResponseText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetResponseTextOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseText) {
		return nil, false
	}
	return o.ResponseText, true
}

// HasResponseText returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasResponseText() bool {
	if o != nil && !IsNil(o.ResponseText) {
		return true
	}

	return false
}

// SetResponseText gets a reference to the given string and assigns it to the ResponseText field.
func (o *AssistantAssistantResponse) SetResponseText(v string) {
	o.ResponseText = &v
}

// GetResponseTimestamp returns the ResponseTimestamp field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetResponseTimestamp() int64 {
	if o == nil || IsNil(o.ResponseTimestamp) {
		var ret int64
		return ret
	}
	return *o.ResponseTimestamp
}

// GetResponseTimestampOk returns a tuple with the ResponseTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetResponseTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.ResponseTimestamp) {
		return nil, false
	}
	return o.ResponseTimestamp, true
}

// HasResponseTimestamp returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasResponseTimestamp() bool {
	if o != nil && !IsNil(o.ResponseTimestamp) {
		return true
	}

	return false
}

// SetResponseTimestamp gets a reference to the given int64 and assigns it to the ResponseTimestamp field.
func (o *AssistantAssistantResponse) SetResponseTimestamp(v int64) {
	o.ResponseTimestamp = &v
}

// GetResponseType returns the ResponseType field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetResponseType() string {
	if o == nil || IsNil(o.ResponseType) {
		var ret string
		return ret
	}
	return *o.ResponseType
}

// GetResponseTypeOk returns a tuple with the ResponseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetResponseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseType) {
		return nil, false
	}
	return o.ResponseType, true
}

// HasResponseType returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasResponseType() bool {
	if o != nil && !IsNil(o.ResponseType) {
		return true
	}

	return false
}

// SetResponseType gets a reference to the given string and assigns it to the ResponseType field.
func (o *AssistantAssistantResponse) SetResponseType(v string) {
	o.ResponseType = &v
}

// GetVisualizationSummary returns the VisualizationSummary field value if set, zero value otherwise.
func (o *AssistantAssistantResponse) GetVisualizationSummary() string {
	if o == nil || IsNil(o.VisualizationSummary) {
		var ret string
		return ret
	}
	return *o.VisualizationSummary
}

// GetVisualizationSummaryOk returns a tuple with the VisualizationSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantAssistantResponse) GetVisualizationSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.VisualizationSummary) {
		return nil, false
	}
	return o.VisualizationSummary, true
}

// HasVisualizationSummary returns a boolean if a field has been set.
func (o *AssistantAssistantResponse) HasVisualizationSummary() bool {
	if o != nil && !IsNil(o.VisualizationSummary) {
		return true
	}

	return false
}

// SetVisualizationSummary gets a reference to the given string and assigns it to the VisualizationSummary field.
func (o *AssistantAssistantResponse) SetVisualizationSummary(v string) {
	o.VisualizationSummary = &v
}

func (o AssistantAssistantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantAssistantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConversationId) {
		toSerialize["conversationId"] = o.ConversationId
	}
	if !IsNil(o.DataframeDictionary) {
		toSerialize["dataframeDictionary"] = o.DataframeDictionary
	}
	if !IsNil(o.OriginalQuestion) {
		toSerialize["originalQuestion"] = o.OriginalQuestion
	}
	if !IsNil(o.ResponseId) {
		toSerialize["responseId"] = o.ResponseId
	}
	if !IsNil(o.ResponseLanguage) {
		toSerialize["responseLanguage"] = o.ResponseLanguage
	}
	if !IsNil(o.ResponseText) {
		toSerialize["responseText"] = o.ResponseText
	}
	if !IsNil(o.ResponseTimestamp) {
		toSerialize["responseTimestamp"] = o.ResponseTimestamp
	}
	if !IsNil(o.ResponseType) {
		toSerialize["responseType"] = o.ResponseType
	}
	if !IsNil(o.VisualizationSummary) {
		toSerialize["visualizationSummary"] = o.VisualizationSummary
	}
	return toSerialize, nil
}

type NullableAssistantAssistantResponse struct {
	value *AssistantAssistantResponse
	isSet bool
}

func (v NullableAssistantAssistantResponse) Get() *AssistantAssistantResponse {
	return v.value
}

func (v *NullableAssistantAssistantResponse) Set(val *AssistantAssistantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantAssistantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantAssistantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantAssistantResponse(val *AssistantAssistantResponse) *NullableAssistantAssistantResponse {
	return &NullableAssistantAssistantResponse{value: val, isSet: true}
}

func (v NullableAssistantAssistantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantAssistantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


