/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1EdgesSummaryPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EdgesSummaryPostResponse{}

// V1EdgesSummaryPostResponse struct for V1EdgesSummaryPostResponse
type V1EdgesSummaryPostResponse struct {
	EdgesSummary []SearchEdgeSummary `json:"edgesSummary,omitempty"`
}

// NewV1EdgesSummaryPostResponse instantiates a new V1EdgesSummaryPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EdgesSummaryPostResponse() *V1EdgesSummaryPostResponse {
	this := V1EdgesSummaryPostResponse{}
	return &this
}

// NewV1EdgesSummaryPostResponseWithDefaults instantiates a new V1EdgesSummaryPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EdgesSummaryPostResponseWithDefaults() *V1EdgesSummaryPostResponse {
	this := V1EdgesSummaryPostResponse{}
	return &this
}

// GetEdgesSummary returns the EdgesSummary field value if set, zero value otherwise.
func (o *V1EdgesSummaryPostResponse) GetEdgesSummary() []SearchEdgeSummary {
	if o == nil || IsNil(o.EdgesSummary) {
		var ret []SearchEdgeSummary
		return ret
	}
	return o.EdgesSummary
}

// GetEdgesSummaryOk returns a tuple with the EdgesSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EdgesSummaryPostResponse) GetEdgesSummaryOk() ([]SearchEdgeSummary, bool) {
	if o == nil || IsNil(o.EdgesSummary) {
		return nil, false
	}
	return o.EdgesSummary, true
}

// HasEdgesSummary returns a boolean if a field has been set.
func (o *V1EdgesSummaryPostResponse) HasEdgesSummary() bool {
	if o != nil && !IsNil(o.EdgesSummary) {
		return true
	}

	return false
}

// SetEdgesSummary gets a reference to the given []SearchEdgeSummary and assigns it to the EdgesSummary field.
func (o *V1EdgesSummaryPostResponse) SetEdgesSummary(v []SearchEdgeSummary) {
	o.EdgesSummary = v
}

func (o V1EdgesSummaryPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EdgesSummaryPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EdgesSummary) {
		toSerialize["edgesSummary"] = o.EdgesSummary
	}
	return toSerialize, nil
}

type NullableV1EdgesSummaryPostResponse struct {
	value *V1EdgesSummaryPostResponse
	isSet bool
}

func (v NullableV1EdgesSummaryPostResponse) Get() *V1EdgesSummaryPostResponse {
	return v.value
}

func (v *NullableV1EdgesSummaryPostResponse) Set(val *V1EdgesSummaryPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EdgesSummaryPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EdgesSummaryPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EdgesSummaryPostResponse(val *V1EdgesSummaryPostResponse) *NullableV1EdgesSummaryPostResponse {
	return &NullableV1EdgesSummaryPostResponse{value: val, isSet: true}
}

func (v NullableV1EdgesSummaryPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EdgesSummaryPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


