/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2SlaInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2SlaInformation{}

// ManaV2SlaInformation struct for ManaV2SlaInformation
type ManaV2SlaInformation struct {
	BackupCircuit *string `json:"backupCircuit,omitempty"`
	Class *string `json:"class,omitempty"`
	PrimaryCircuit *string `json:"primaryCircuit,omitempty"`
}

// NewManaV2SlaInformation instantiates a new ManaV2SlaInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2SlaInformation() *ManaV2SlaInformation {
	this := ManaV2SlaInformation{}
	return &this
}

// NewManaV2SlaInformationWithDefaults instantiates a new ManaV2SlaInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2SlaInformationWithDefaults() *ManaV2SlaInformation {
	this := ManaV2SlaInformation{}
	return &this
}

// GetBackupCircuit returns the BackupCircuit field value if set, zero value otherwise.
func (o *ManaV2SlaInformation) GetBackupCircuit() string {
	if o == nil || IsNil(o.BackupCircuit) {
		var ret string
		return ret
	}
	return *o.BackupCircuit
}

// GetBackupCircuitOk returns a tuple with the BackupCircuit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaInformation) GetBackupCircuitOk() (*string, bool) {
	if o == nil || IsNil(o.BackupCircuit) {
		return nil, false
	}
	return o.BackupCircuit, true
}

// HasBackupCircuit returns a boolean if a field has been set.
func (o *ManaV2SlaInformation) HasBackupCircuit() bool {
	if o != nil && !IsNil(o.BackupCircuit) {
		return true
	}

	return false
}

// SetBackupCircuit gets a reference to the given string and assigns it to the BackupCircuit field.
func (o *ManaV2SlaInformation) SetBackupCircuit(v string) {
	o.BackupCircuit = &v
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *ManaV2SlaInformation) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaInformation) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *ManaV2SlaInformation) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *ManaV2SlaInformation) SetClass(v string) {
	o.Class = &v
}

// GetPrimaryCircuit returns the PrimaryCircuit field value if set, zero value otherwise.
func (o *ManaV2SlaInformation) GetPrimaryCircuit() string {
	if o == nil || IsNil(o.PrimaryCircuit) {
		var ret string
		return ret
	}
	return *o.PrimaryCircuit
}

// GetPrimaryCircuitOk returns a tuple with the PrimaryCircuit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SlaInformation) GetPrimaryCircuitOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryCircuit) {
		return nil, false
	}
	return o.PrimaryCircuit, true
}

// HasPrimaryCircuit returns a boolean if a field has been set.
func (o *ManaV2SlaInformation) HasPrimaryCircuit() bool {
	if o != nil && !IsNil(o.PrimaryCircuit) {
		return true
	}

	return false
}

// SetPrimaryCircuit gets a reference to the given string and assigns it to the PrimaryCircuit field.
func (o *ManaV2SlaInformation) SetPrimaryCircuit(v string) {
	o.PrimaryCircuit = &v
}

func (o ManaV2SlaInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2SlaInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupCircuit) {
		toSerialize["backupCircuit"] = o.BackupCircuit
	}
	if !IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !IsNil(o.PrimaryCircuit) {
		toSerialize["primaryCircuit"] = o.PrimaryCircuit
	}
	return toSerialize, nil
}

type NullableManaV2SlaInformation struct {
	value *ManaV2SlaInformation
	isSet bool
}

func (v NullableManaV2SlaInformation) Get() *ManaV2SlaInformation {
	return v.value
}

func (v *NullableManaV2SlaInformation) Set(val *ManaV2SlaInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2SlaInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2SlaInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2SlaInformation(val *ManaV2SlaInformation) *NullableManaV2SlaInformation {
	return &NullableManaV2SlaInformation{value: val, isSet: true}
}

func (v NullableManaV2SlaInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2SlaInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


