/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceTopologyClientSessionDetailsPost200ResponseSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceTopologyClientSessionDetailsPost200ResponseSession{}

// V2AssuranceTopologyClientSessionDetailsPost200ResponseSession struct for V2AssuranceTopologyClientSessionDetailsPost200ResponseSession
type V2AssuranceTopologyClientSessionDetailsPost200ResponseSession struct {
	AppName *string `json:"appName,omitempty"`
	Bucket *string `json:"bucket,omitempty"`
	ClientEndpoint *V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint `json:"clientEndpoint,omitempty"`
	ClientFlexAlgo *string `json:"clientFlexAlgo,omitempty"`
	ClientIp *string `json:"clientIp,omitempty"`
	ClientLinks []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner `json:"clientLinks,omitempty"`
	FirstSeenTs *V1AlarmHistoryGet200ResponseHistoryInnerTime `json:"firstSeenTs,omitempty"`
	LanSegment []string `json:"lanSegment,omitempty"`
	LastSeenTs *V1AlarmHistoryGet200ResponseHistoryInnerTime `json:"lastSeenTs,omitempty"`
	LocalDiaLinks []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner `json:"localDiaLinks,omitempty"`
	PopLinks []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner `json:"popLinks,omitempty"`
	RemoteDiaLinks []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner `json:"remoteDiaLinks,omitempty"`
	RiskStatus *string `json:"riskStatus,omitempty"`
	ServerEndpoint *V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint `json:"serverEndpoint,omitempty"`
	ServerFlexAlgos []string `json:"serverFlexAlgos,omitempty"`
	ServerIp *string `json:"serverIp,omitempty"`
	ServerLinks []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner `json:"serverLinks,omitempty"`
	ServerPort *int32 `json:"serverPort,omitempty"`
	SessionId *string `json:"sessionId,omitempty"`
	Sla *string `json:"sla,omitempty"`
	SlaClass *string `json:"slaClass,omitempty"`
}

// NewV2AssuranceTopologyClientSessionDetailsPost200ResponseSession instantiates a new V2AssuranceTopologyClientSessionDetailsPost200ResponseSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceTopologyClientSessionDetailsPost200ResponseSession() *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession {
	this := V2AssuranceTopologyClientSessionDetailsPost200ResponseSession{}
	return &this
}

// NewV2AssuranceTopologyClientSessionDetailsPost200ResponseSessionWithDefaults instantiates a new V2AssuranceTopologyClientSessionDetailsPost200ResponseSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceTopologyClientSessionDetailsPost200ResponseSessionWithDefaults() *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession {
	this := V2AssuranceTopologyClientSessionDetailsPost200ResponseSession{}
	return &this
}

// GetAppName returns the AppName field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetAppName() string {
	if o == nil || IsNil(o.AppName) {
		var ret string
		return ret
	}
	return *o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetAppNameOk() (*string, bool) {
	if o == nil || IsNil(o.AppName) {
		return nil, false
	}
	return o.AppName, true
}

// HasAppName returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasAppName() bool {
	if o != nil && !IsNil(o.AppName) {
		return true
	}

	return false
}

// SetAppName gets a reference to the given string and assigns it to the AppName field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetAppName(v string) {
	o.AppName = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetBucket(v string) {
	o.Bucket = &v
}

// GetClientEndpoint returns the ClientEndpoint field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientEndpoint() V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint {
	if o == nil || IsNil(o.ClientEndpoint) {
		var ret V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint
		return ret
	}
	return *o.ClientEndpoint
}

// GetClientEndpointOk returns a tuple with the ClientEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientEndpointOk() (*V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint, bool) {
	if o == nil || IsNil(o.ClientEndpoint) {
		return nil, false
	}
	return o.ClientEndpoint, true
}

// HasClientEndpoint returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasClientEndpoint() bool {
	if o != nil && !IsNil(o.ClientEndpoint) {
		return true
	}

	return false
}

// SetClientEndpoint gets a reference to the given V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint and assigns it to the ClientEndpoint field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetClientEndpoint(v V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint) {
	o.ClientEndpoint = &v
}

// GetClientFlexAlgo returns the ClientFlexAlgo field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientFlexAlgo() string {
	if o == nil || IsNil(o.ClientFlexAlgo) {
		var ret string
		return ret
	}
	return *o.ClientFlexAlgo
}

// GetClientFlexAlgoOk returns a tuple with the ClientFlexAlgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientFlexAlgoOk() (*string, bool) {
	if o == nil || IsNil(o.ClientFlexAlgo) {
		return nil, false
	}
	return o.ClientFlexAlgo, true
}

// HasClientFlexAlgo returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasClientFlexAlgo() bool {
	if o != nil && !IsNil(o.ClientFlexAlgo) {
		return true
	}

	return false
}

// SetClientFlexAlgo gets a reference to the given string and assigns it to the ClientFlexAlgo field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetClientFlexAlgo(v string) {
	o.ClientFlexAlgo = &v
}

// GetClientIp returns the ClientIp field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientIp() string {
	if o == nil || IsNil(o.ClientIp) {
		var ret string
		return ret
	}
	return *o.ClientIp
}

// GetClientIpOk returns a tuple with the ClientIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientIpOk() (*string, bool) {
	if o == nil || IsNil(o.ClientIp) {
		return nil, false
	}
	return o.ClientIp, true
}

// HasClientIp returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasClientIp() bool {
	if o != nil && !IsNil(o.ClientIp) {
		return true
	}

	return false
}

// SetClientIp gets a reference to the given string and assigns it to the ClientIp field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetClientIp(v string) {
	o.ClientIp = &v
}

// GetClientLinks returns the ClientLinks field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientLinks() []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner {
	if o == nil || IsNil(o.ClientLinks) {
		var ret []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner
		return ret
	}
	return o.ClientLinks
}

// GetClientLinksOk returns a tuple with the ClientLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetClientLinksOk() ([]V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner, bool) {
	if o == nil || IsNil(o.ClientLinks) {
		return nil, false
	}
	return o.ClientLinks, true
}

// HasClientLinks returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasClientLinks() bool {
	if o != nil && !IsNil(o.ClientLinks) {
		return true
	}

	return false
}

// SetClientLinks gets a reference to the given []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner and assigns it to the ClientLinks field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetClientLinks(v []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner) {
	o.ClientLinks = v
}

// GetFirstSeenTs returns the FirstSeenTs field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetFirstSeenTs() V1AlarmHistoryGet200ResponseHistoryInnerTime {
	if o == nil || IsNil(o.FirstSeenTs) {
		var ret V1AlarmHistoryGet200ResponseHistoryInnerTime
		return ret
	}
	return *o.FirstSeenTs
}

// GetFirstSeenTsOk returns a tuple with the FirstSeenTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetFirstSeenTsOk() (*V1AlarmHistoryGet200ResponseHistoryInnerTime, bool) {
	if o == nil || IsNil(o.FirstSeenTs) {
		return nil, false
	}
	return o.FirstSeenTs, true
}

// HasFirstSeenTs returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasFirstSeenTs() bool {
	if o != nil && !IsNil(o.FirstSeenTs) {
		return true
	}

	return false
}

// SetFirstSeenTs gets a reference to the given V1AlarmHistoryGet200ResponseHistoryInnerTime and assigns it to the FirstSeenTs field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetFirstSeenTs(v V1AlarmHistoryGet200ResponseHistoryInnerTime) {
	o.FirstSeenTs = &v
}

// GetLanSegment returns the LanSegment field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLanSegment() []string {
	if o == nil || IsNil(o.LanSegment) {
		var ret []string
		return ret
	}
	return o.LanSegment
}

// GetLanSegmentOk returns a tuple with the LanSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLanSegmentOk() ([]string, bool) {
	if o == nil || IsNil(o.LanSegment) {
		return nil, false
	}
	return o.LanSegment, true
}

// HasLanSegment returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasLanSegment() bool {
	if o != nil && !IsNil(o.LanSegment) {
		return true
	}

	return false
}

// SetLanSegment gets a reference to the given []string and assigns it to the LanSegment field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetLanSegment(v []string) {
	o.LanSegment = v
}

// GetLastSeenTs returns the LastSeenTs field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLastSeenTs() V1AlarmHistoryGet200ResponseHistoryInnerTime {
	if o == nil || IsNil(o.LastSeenTs) {
		var ret V1AlarmHistoryGet200ResponseHistoryInnerTime
		return ret
	}
	return *o.LastSeenTs
}

// GetLastSeenTsOk returns a tuple with the LastSeenTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLastSeenTsOk() (*V1AlarmHistoryGet200ResponseHistoryInnerTime, bool) {
	if o == nil || IsNil(o.LastSeenTs) {
		return nil, false
	}
	return o.LastSeenTs, true
}

// HasLastSeenTs returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasLastSeenTs() bool {
	if o != nil && !IsNil(o.LastSeenTs) {
		return true
	}

	return false
}

// SetLastSeenTs gets a reference to the given V1AlarmHistoryGet200ResponseHistoryInnerTime and assigns it to the LastSeenTs field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetLastSeenTs(v V1AlarmHistoryGet200ResponseHistoryInnerTime) {
	o.LastSeenTs = &v
}

// GetLocalDiaLinks returns the LocalDiaLinks field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLocalDiaLinks() []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner {
	if o == nil || IsNil(o.LocalDiaLinks) {
		var ret []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner
		return ret
	}
	return o.LocalDiaLinks
}

// GetLocalDiaLinksOk returns a tuple with the LocalDiaLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetLocalDiaLinksOk() ([]V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner, bool) {
	if o == nil || IsNil(o.LocalDiaLinks) {
		return nil, false
	}
	return o.LocalDiaLinks, true
}

// HasLocalDiaLinks returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasLocalDiaLinks() bool {
	if o != nil && !IsNil(o.LocalDiaLinks) {
		return true
	}

	return false
}

// SetLocalDiaLinks gets a reference to the given []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner and assigns it to the LocalDiaLinks field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetLocalDiaLinks(v []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner) {
	o.LocalDiaLinks = v
}

// GetPopLinks returns the PopLinks field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetPopLinks() []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner {
	if o == nil || IsNil(o.PopLinks) {
		var ret []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner
		return ret
	}
	return o.PopLinks
}

// GetPopLinksOk returns a tuple with the PopLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetPopLinksOk() ([]V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner, bool) {
	if o == nil || IsNil(o.PopLinks) {
		return nil, false
	}
	return o.PopLinks, true
}

// HasPopLinks returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasPopLinks() bool {
	if o != nil && !IsNil(o.PopLinks) {
		return true
	}

	return false
}

// SetPopLinks gets a reference to the given []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner and assigns it to the PopLinks field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetPopLinks(v []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionPopLinksInner) {
	o.PopLinks = v
}

// GetRemoteDiaLinks returns the RemoteDiaLinks field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetRemoteDiaLinks() []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner {
	if o == nil || IsNil(o.RemoteDiaLinks) {
		var ret []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner
		return ret
	}
	return o.RemoteDiaLinks
}

// GetRemoteDiaLinksOk returns a tuple with the RemoteDiaLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetRemoteDiaLinksOk() ([]V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner, bool) {
	if o == nil || IsNil(o.RemoteDiaLinks) {
		return nil, false
	}
	return o.RemoteDiaLinks, true
}

// HasRemoteDiaLinks returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasRemoteDiaLinks() bool {
	if o != nil && !IsNil(o.RemoteDiaLinks) {
		return true
	}

	return false
}

// SetRemoteDiaLinks gets a reference to the given []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner and assigns it to the RemoteDiaLinks field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetRemoteDiaLinks(v []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionLocalDiaLinksInner) {
	o.RemoteDiaLinks = v
}

// GetRiskStatus returns the RiskStatus field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetRiskStatus() string {
	if o == nil || IsNil(o.RiskStatus) {
		var ret string
		return ret
	}
	return *o.RiskStatus
}

// GetRiskStatusOk returns a tuple with the RiskStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetRiskStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RiskStatus) {
		return nil, false
	}
	return o.RiskStatus, true
}

// HasRiskStatus returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasRiskStatus() bool {
	if o != nil && !IsNil(o.RiskStatus) {
		return true
	}

	return false
}

// SetRiskStatus gets a reference to the given string and assigns it to the RiskStatus field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetRiskStatus(v string) {
	o.RiskStatus = &v
}

// GetServerEndpoint returns the ServerEndpoint field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerEndpoint() V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint {
	if o == nil || IsNil(o.ServerEndpoint) {
		var ret V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint
		return ret
	}
	return *o.ServerEndpoint
}

// GetServerEndpointOk returns a tuple with the ServerEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerEndpointOk() (*V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint, bool) {
	if o == nil || IsNil(o.ServerEndpoint) {
		return nil, false
	}
	return o.ServerEndpoint, true
}

// HasServerEndpoint returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasServerEndpoint() bool {
	if o != nil && !IsNil(o.ServerEndpoint) {
		return true
	}

	return false
}

// SetServerEndpoint gets a reference to the given V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint and assigns it to the ServerEndpoint field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetServerEndpoint(v V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientEndpoint) {
	o.ServerEndpoint = &v
}

// GetServerFlexAlgos returns the ServerFlexAlgos field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerFlexAlgos() []string {
	if o == nil || IsNil(o.ServerFlexAlgos) {
		var ret []string
		return ret
	}
	return o.ServerFlexAlgos
}

// GetServerFlexAlgosOk returns a tuple with the ServerFlexAlgos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerFlexAlgosOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerFlexAlgos) {
		return nil, false
	}
	return o.ServerFlexAlgos, true
}

// HasServerFlexAlgos returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasServerFlexAlgos() bool {
	if o != nil && !IsNil(o.ServerFlexAlgos) {
		return true
	}

	return false
}

// SetServerFlexAlgos gets a reference to the given []string and assigns it to the ServerFlexAlgos field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetServerFlexAlgos(v []string) {
	o.ServerFlexAlgos = v
}

// GetServerIp returns the ServerIp field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerIp() string {
	if o == nil || IsNil(o.ServerIp) {
		var ret string
		return ret
	}
	return *o.ServerIp
}

// GetServerIpOk returns a tuple with the ServerIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerIpOk() (*string, bool) {
	if o == nil || IsNil(o.ServerIp) {
		return nil, false
	}
	return o.ServerIp, true
}

// HasServerIp returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasServerIp() bool {
	if o != nil && !IsNil(o.ServerIp) {
		return true
	}

	return false
}

// SetServerIp gets a reference to the given string and assigns it to the ServerIp field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetServerIp(v string) {
	o.ServerIp = &v
}

// GetServerLinks returns the ServerLinks field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerLinks() []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner {
	if o == nil || IsNil(o.ServerLinks) {
		var ret []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner
		return ret
	}
	return o.ServerLinks
}

// GetServerLinksOk returns a tuple with the ServerLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerLinksOk() ([]V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner, bool) {
	if o == nil || IsNil(o.ServerLinks) {
		return nil, false
	}
	return o.ServerLinks, true
}

// HasServerLinks returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasServerLinks() bool {
	if o != nil && !IsNil(o.ServerLinks) {
		return true
	}

	return false
}

// SetServerLinks gets a reference to the given []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner and assigns it to the ServerLinks field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetServerLinks(v []V2AssuranceTopologyClientSessionDetailsPost200ResponseSessionClientLinksInner) {
	o.ServerLinks = v
}

// GetServerPort returns the ServerPort field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerPort() int32 {
	if o == nil || IsNil(o.ServerPort) {
		var ret int32
		return ret
	}
	return *o.ServerPort
}

// GetServerPortOk returns a tuple with the ServerPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetServerPortOk() (*int32, bool) {
	if o == nil || IsNil(o.ServerPort) {
		return nil, false
	}
	return o.ServerPort, true
}

// HasServerPort returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasServerPort() bool {
	if o != nil && !IsNil(o.ServerPort) {
		return true
	}

	return false
}

// SetServerPort gets a reference to the given int32 and assigns it to the ServerPort field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetServerPort(v int32) {
	o.ServerPort = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetSessionId(v string) {
	o.SessionId = &v
}

// GetSla returns the Sla field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSla() string {
	if o == nil || IsNil(o.Sla) {
		var ret string
		return ret
	}
	return *o.Sla
}

// GetSlaOk returns a tuple with the Sla field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSlaOk() (*string, bool) {
	if o == nil || IsNil(o.Sla) {
		return nil, false
	}
	return o.Sla, true
}

// HasSla returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasSla() bool {
	if o != nil && !IsNil(o.Sla) {
		return true
	}

	return false
}

// SetSla gets a reference to the given string and assigns it to the Sla field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetSla(v string) {
	o.Sla = &v
}

// GetSlaClass returns the SlaClass field value if set, zero value otherwise.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSlaClass() string {
	if o == nil || IsNil(o.SlaClass) {
		var ret string
		return ret
	}
	return *o.SlaClass
}

// GetSlaClassOk returns a tuple with the SlaClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) GetSlaClassOk() (*string, bool) {
	if o == nil || IsNil(o.SlaClass) {
		return nil, false
	}
	return o.SlaClass, true
}

// HasSlaClass returns a boolean if a field has been set.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) HasSlaClass() bool {
	if o != nil && !IsNil(o.SlaClass) {
		return true
	}

	return false
}

// SetSlaClass gets a reference to the given string and assigns it to the SlaClass field.
func (o *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) SetSlaClass(v string) {
	o.SlaClass = &v
}

func (o V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppName) {
		toSerialize["appName"] = o.AppName
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.ClientEndpoint) {
		toSerialize["clientEndpoint"] = o.ClientEndpoint
	}
	if !IsNil(o.ClientFlexAlgo) {
		toSerialize["clientFlexAlgo"] = o.ClientFlexAlgo
	}
	if !IsNil(o.ClientIp) {
		toSerialize["clientIp"] = o.ClientIp
	}
	if !IsNil(o.ClientLinks) {
		toSerialize["clientLinks"] = o.ClientLinks
	}
	if !IsNil(o.FirstSeenTs) {
		toSerialize["firstSeenTs"] = o.FirstSeenTs
	}
	if !IsNil(o.LanSegment) {
		toSerialize["lanSegment"] = o.LanSegment
	}
	if !IsNil(o.LastSeenTs) {
		toSerialize["lastSeenTs"] = o.LastSeenTs
	}
	if !IsNil(o.LocalDiaLinks) {
		toSerialize["localDiaLinks"] = o.LocalDiaLinks
	}
	if !IsNil(o.PopLinks) {
		toSerialize["popLinks"] = o.PopLinks
	}
	if !IsNil(o.RemoteDiaLinks) {
		toSerialize["remoteDiaLinks"] = o.RemoteDiaLinks
	}
	if !IsNil(o.RiskStatus) {
		toSerialize["riskStatus"] = o.RiskStatus
	}
	if !IsNil(o.ServerEndpoint) {
		toSerialize["serverEndpoint"] = o.ServerEndpoint
	}
	if !IsNil(o.ServerFlexAlgos) {
		toSerialize["serverFlexAlgos"] = o.ServerFlexAlgos
	}
	if !IsNil(o.ServerIp) {
		toSerialize["serverIp"] = o.ServerIp
	}
	if !IsNil(o.ServerLinks) {
		toSerialize["serverLinks"] = o.ServerLinks
	}
	if !IsNil(o.ServerPort) {
		toSerialize["serverPort"] = o.ServerPort
	}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Sla) {
		toSerialize["sla"] = o.Sla
	}
	if !IsNil(o.SlaClass) {
		toSerialize["slaClass"] = o.SlaClass
	}
	return toSerialize, nil
}

type NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession struct {
	value *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession
	isSet bool
}

func (v NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) Get() *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession {
	return v.value
}

func (v *NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) Set(val *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession(val *V2AssuranceTopologyClientSessionDetailsPost200ResponseSession) *NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession {
	return &NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession{value: val, isSet: true}
}

func (v NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceTopologyClientSessionDetailsPost200ResponseSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


